export const inboxActionTypes = {
    SET_CFB_NOTIFICATIONS: 'SET_CFB_NOTIFICATIONS',
    SET_NFL_NOTIFICATIONS: 'SET_NFL_NOTIFICATIONS',
    SET_CBB_NOTIFICATIONS: 'SET_CBB_NOTIFICATIONS',
    SET_NBA_NOTIFICATIONS: 'SET_NBA_NOTIFICATIONS'
};
