const SampleContent = [
  {
    id: 1,
    name: "Aaron Kotar",
    position: "QB",
    archtype: "Scrambler",
    overall: "B",
    year: "(Sr.)",
    height: "6'2\"",
    weight: "205 lbs",
    state: "Ohio",
    school: "Buckeye High",
    potential: "C",
    jersey: "12",
    team: "Washington State Cougars",
    designation: "QB1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 40 },
      agility: { name: "Agility", value: 35 },
      catching: { name: "Catching", value: 20 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 0 },
      football_iq: { name: "Football IQ", value: 40 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 100 },
      pass_block: { name: "Pass Blocking", value: 0 },
      pass_rush: { name: "Pass Rush", value: 0 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 5 },
      run_block: { name: "Run Blocking", value: 0 },
      run_defense: { name: "Run Defense", value: 0 },
      speed: { name: "Speed", value: 69 },
      strength: { name: "Strength", value: 30 },
      tackle: { name: "Tackle", value: 0 },
      throw_power: { name: "Throw Power", value: 43 },
      throw_accuracy: { name: "Throw Accuracy", value: 43 },
      stamina: { name: "Stamina", value: 40 }
    }
  },
  {
    id: 2,
    name: "Marquise Mariota",
    position: "QB",
    archtype: "Balanced",
    overall: "A",
    year: "(Fr.)",
    height: "6'4\"",
    weight: "235 lbs",
    state: "Hawaii",
    school: "St. Louis HS",
    potential: "C",
    jersey: "2",
    team: "Washington State Cougars",
    designation: "QB2",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 40 },
      agility: { name: "Agility", value: 35 },
      catching: { name: "Catching", value: 20 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 0 },
      football_iq: { name: "Football IQ", value: 40 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 100 },
      pass_block: { name: "Pass Blocking", value: 0 },
      pass_rush: { name: "Pass Rush", value: 0 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 5 },
      run_block: { name: "Run Blocking", value: 0 },
      run_defense: { name: "Run Defense", value: 0 },
      speed: { name: "Speed", value: 69, priority: 3 },
      strength: { name: "Strength", value: 30 },
      tackle: { name: "Tackle", value: 0 },
      throw_power: { name: "Throw Power", value: 43 },
      throw_accuracy: { name: "Throw Accuracy", value: 43 },
      stamina: { name: "Stamina", value: 40 }
    }
  },
  {
    id: 3,
    name: "Cal Beckam Jr",
    position: "WR",
    archtype: "Speed",
    overall: "C+",
    year: "So.",
    height: "6'5\"",
    weight: "200 lbs",
    state: "Texas",
    school: "Midway Highschool",
    potential: "B-",
    jersey: "15",
    team: "Washington State Cougars",
    designation: "WR1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 40 },
      agility: { name: "Agility", value: 45 },
      catching: { name: "Catching", value: 55 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 0 },
      football_iq: { name: "Football IQ", value: 52 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 100 },
      pass_block: { name: "Pass Blocking", value: 0 },
      pass_rush: { name: "Pass Rush", value: 0 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 33 },
      run_block: { name: "Run Blocking", value: 0 },
      run_defense: { name: "Run Defense", value: 0 },
      speed: { name: "Speed", value: 77 },
      strength: { name: "Strength", value: 22 },
      tackle: { name: "Tackle", value: 0 },
      throw_power: { name: "Throw Power", value: 12 },
      throw_accuracy: { name: "Throw Accuracy", value: 5 },
      stamina: { name: "Stamina", value: 40 }
    }
  },
  {
    id: 4,
    name: "Chris Cross",
    position: "DE",
    archtype: "Speed Rusher",
    overall: "A",
    year: "Jr.",
    height: "6'7\"",
    weight: "261 lbs",
    state: "Georgia",
    school: "George Southwest CC",
    potential: "A",
    jersey: "72",
    team: "Washington State Cougars",
    designation: "LE1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 40 },
      agility: { name: "Agility", value: 55 },
      catching: { name: "Catching", value: 20 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 20 },
      football_iq: { name: "Football IQ", value: 38 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 5 },
      pass_block: { name: "Pass Blocking", value: 0 },
      pass_rush: { name: "Pass Rush", value: 52 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 5 },
      run_block: { name: "Run Blocking", value: 0 },
      run_defense: { name: "Run Defense", value: 37 },
      speed: { name: "Speed", value: 60 },
      strength: { name: "Strength", value: 41 },
      tackle: { name: "Tackle", value: 54 },
      throw_power: { name: "Throw Power", value: 1 },
      throw_accuracy: { name: "Throw Accuracy", value: 1 },
      stamina: { name: "Stamina", value: 40 }
    }
  },
  {
    id: 5,
    name: "Quincy Sanford",
    position: "CB",
    archtype: "Ball Hawk",
    overall: "D",
    year: "Sr.",
    height: "5'9\"",
    weight: "110 lbs",
    state: "Delaware",
    school: "Barack Obama HS",
    potential: "D",
    jersey: "30",
    team: "Washington State Cougars",
    designation: "CB1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 22 },
      agility: { name: "Agility", value: 42 },
      catching: { name: "Catching", value: 35 },
      zone_coverage: { name: "Zone Coverage", value: 37 },
      man_coverage: { name: "Man Coverage", value: 39 },
      football_iq: { name: "Football IQ", value: 23 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 100 },
      pass_block: { name: "Pass Blocking", value: 0 },
      pass_rush: { name: "Pass Rush", value: 0 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 5 },
      run_block: { name: "Run Blocking", value: 0 },
      run_defense: { name: "Run Defense", value: 0 },
      speed: { name: "Speed", value: 41 },
      strength: { name: "Strength", value: 7 },
      tackle: { name: "Tackle", value: 11 },
      throw_power: { name: "Throw Power", value: 1 },
      throw_accuracy: { name: "Throw Accuracy", value: 1 },
      stamina: { name: "Stamina", value: 40 }
    }
  },
  {
    id: 6,
    name: "Beau Allen",
    position: "DT",
    archtype: "Nose Tackle",
    overall: "A",
    year: "(Sr.)",
    height: "6'5\"",
    weight: "291 lbs",
    state: "Minnesota",
    school: "Minnetonka High School",
    potential: "B",
    jersey: "30",
    team: "Washington State Cougars",
    designation: "DT1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 24 },
      agility: { name: "Agility", value: 35 },
      catching: { name: "Catching", value: 21 },
      zone_coverage: { name: "Zone Coverage", value: 8 },
      man_coverage: { name: "Man Coverage", value: 6 },
      football_iq: { name: "Football IQ", value: 26 },
      kick_accuracy: { name: "Kick Accuracy", value: 1 },
      kick_power: { name: "Kick Power", value: 1 },
      pass_block: { name: "Pass Blocking", value: 1 },
      pass_rush: { name: "Pass Rush", value: 33 },
      punt_accuracy: { name: "Punt Accuracy", value: 2 },
      punt_power: { name: "Punt Power", value: 2 },
      route_running: { name: "Route Running", value: 3 },
      run_block: { name: "Run Blocking", value: 10 },
      run_defense: { name: "Run Defense", value: 50 },
      speed: { name: "Speed", value: 28 },
      strength: { name: "Strength", value: 50 },
      tackle: { name: "Tackle", value: 40 },
      throw_power: { name: "Throw Power", value: 23 },
      throw_accuracy: { name: "Throw Accuracy", value: 16 },
      stamina: { name: "Stamina", value: 40 }
    }
  },
  {
    id: 7,
    name: "Rob Adams",
    position: "OT",
    archtype: "Run Blocking",
    overall: "A",
    year: "Sr.",
    height: "6'3\"",
    weight: "219 lbs",
    state: "Florida",
    school: "Harmony",
    potential: "C",
    jersey: "61",
    team: "Washington State Cougars",
    designation: "LT1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 16 },
      agility: { name: "Agility", value: 29 },
      catching: { name: "Catching", value: 16 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 0 },
      football_iq: { name: "Football IQ", value: 26 },
      kick_accuracy: { name: "Kick Accuracy", value: 1 },
      kick_power: { name: "Kick Power", value: 3 },
      pass_block: { name: "Pass Blocking", value: 30 },
      pass_rush: { name: "Pass Rush", value: 16 },
      punt_accuracy: { name: "Punt Accuracy", value: 5 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 10 },
      run_block: { name: "Run Blocking", value: 45 },
      run_defense: { name: "Run Defense", value: 6 },
      speed: { name: "Speed", value: 23 },
      strength: { name: "Strength", value: 47 },
      tackle: { name: "Tackle", value: 20 },
      throw_power: { name: "Throw Power", value: 3 },
      throw_accuracy: { name: "Throw Accuracy", value: 3 },
      stamina: { name: "Stamina", value: 40 }
    }
  },
  {
    id: 8,
    name: "Jonas Skipper",
    position: "OG",
    archtype: "Balanced",
    overall: "A",
    year: "Sr.",
    height: "6'5\"",
    weight: "294 lbs",
    state: "Missouri",
    school: "Cassville",
    potential: "C+",
    jersey: "51",
    team: "Washington State Cougars",
    designation: "LG1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 20 },
      agility: { name: "Agility", value: 23 },
      catching: { name: "Catching", value: 26 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 0 },
      football_iq: { name: "Football IQ", value: 31 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 1 },
      pass_block: { name: "Pass Blocking", value: 37 },
      pass_rush: { name: "Pass Rush", value: 12 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 5 },
      run_block: { name: "Run Blocking", value: 33 },
      run_defense: { name: "Run Defense", value: 0 },
      speed: { name: "Speed", value: 30 },
      strength: { name: "Strength", value: 58 },
      tackle: { name: "Tackle", value: 0 },
      throw_power: { name: "Throw Power", value: 2 },
      throw_accuracy: { name: "Throw Accuracy", value: 2 },
      stamina: { name: "Stamina", value: 40 }
    }
  },
  {
    id: 9,
    name: "Chris Butera",
    position: "OG",
    archtype: "Run Blocking",
    overall: "A",
    year: "Jr.",
    height: "6'5\"",
    weight: "306 lbs",
    state: "TX",
    school: "Manvel",
    potential: "B+",
    jersey: "63",
    team: "Washington State Cougars",
    designation: "RG1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 20 },
      agility: { name: "Agility", value: 23 },
      catching: { name: "Catching", value: 26 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 0 },
      football_iq: { name: "Football IQ", value: 31 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 1 },
      pass_block: { name: "Pass Blocking", value: 37 },
      pass_rush: { name: "Pass Rush", value: 12 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 5 },
      run_block: { name: "Run Blocking", value: 57 },
      run_defense: { name: "Run Defense", value: 0 },
      speed: { name: "Speed", value: 30 },
      strength: { name: "Strength", value: 58 },
      tackle: { name: "Tackle", value: 0 },
      throw_power: { name: "Throw Power", value: 2 },
      throw_accuracy: { name: "Throw Accuracy", value: 2 },
      stamina: { name: "Stamina", value: 40 }
    }
  },
  {
    id: 10,
    name: "Chris Hinojosa",
    position: "ILB",
    archtype: "Field General",
    overall: "B",
    year: "Sr.",
    height: "6'0\"",
    weight: "234 lbs",
    state: "NJ",
    school: "West Long Branch",
    potential: "C+",
    jersey: "53",
    team: "Washington State Cougars",
    designation: "ILB1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 20 },
      agility: { name: "Agility", value: 37 },
      catching: { name: "Catching", value: 18 },
      zone_coverage: { name: "Zone Coverage", value: 39 },
      man_coverage: { name: "Man Coverage", value: 30 },
      football_iq: { name: "Football IQ", value: 40 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 0 },
      pass_block: { name: "Pass Blocking", value: 0 },
      pass_rush: { name: "Pass Rush", value: 17 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 5 },
      run_block: { name: "Run Blocking", value: 0 },
      run_defense: { name: "Run Defense", value: 30 },
      speed: { name: "Speed", value: 42 },
      strength: { name: "Strength", value: 32 },
      tackle: { name: "Tackle", value: 38 },
      throw_power: { name: "Throw Power", value: 43 },
      throw_accuracy: { name: "Throw Accuracy", value: 43 },
      stamina: { name: "Stamina", value: 40 }
    }
  },
  {
    id: 11,
    name: "Bobby Hammel",
    position: "OLB",
    archtype: "Pass Rush",
    overall: "B",
    year: "Sr.",
    height: "6'3\"",
    weight: "246 lbs",
    state: "NC",
    school: "Kinston",
    potential: "C+",
    jersey: "50",
    team: "Washington State Cougars",
    designation: "LOLB1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 20 },
      agility: { name: "Agility", value: 39 },
      catching: { name: "Catching", value: 18 },
      zone_coverage: { name: "Zone Coverage", value: 26 },
      man_coverage: { name: "Man Coverage", value: 25 },
      football_iq: { name: "Football IQ", value: 28 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 0 },
      pass_block: { name: "Pass Blocking", value: 10 },
      pass_rush: { name: "Pass Rush", value: 43 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 5 },
      run_block: { name: "Run Blocking", value: 1 },
      run_defense: { name: "Run Defense", value: 26 },
      speed: { name: "Speed", value: 45 },
      strength: { name: "Strength", value: 32 },
      tackle: { name: "Tackle", value: 37 },
      throw_power: { name: "Throw Power", value: 1 },
      throw_accuracy: { name: "Throw Accuracy", value: 1 },
      stamina: { name: "Stamina", value: 40 }
    }
  },
  {
    id: 12,
    name: "Darin Howard",
    position: "K",
    archtype: "Accuracy",
    overall: "B",
    year: "Sr.",
    height: "5'11\"",
    weight: "193 lbs",
    state: "WA",
    school: "Seattle Prep",
    potential: "C+",
    jersey: "40",
    team: "Washington State Cougars",
    designation: "K1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 10 },
      agility: { name: "Agility", value: 10 },
      catching: { name: "Catching", value: 10 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 10 },
      football_iq: { name: "Football IQ", value: 23 },
      kick_accuracy: { name: "Kick Accuracy", value: 39 },
      kick_power: { name: "Kick Power", value: 22 },
      pass_block: { name: "Pass Blocking", value: 10 },
      pass_rush: { name: "Pass Rush", value: 10 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 10 },
      run_block: { name: "Run Blocking", value: 10 },
      run_defense: { name: "Run Defense", value: 10 },
      speed: { name: "Speed", value: 10 },
      strength: { name: "Strength", value: 10 },
      tackle: { name: "Tackle", value: 10 },
      throw_power: { name: "Throw Power", value: 10 },
      throw_accuracy: { name: "Throw Accuracy", value: 10 },
      stamina: { name: "Stamina", value: 40 }
    }
  },
  {
    id: 13,
    name: "Chris Tilson",
    position: "RB",
    archtype: "Speed",
    overall: "B",
    year: "Jr.",
    height: "5'11\"",
    weight: "203 lbs",
    state: "OK",
    school: "Victory Christian",
    potential: "C+",
    jersey: "24",
    team: "Washington State Cougars",
    designation: "RB1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 19 },
      agility: { name: "Agility", value: 23 },
      catching: { name: "Catching", value: 15 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 10 },
      football_iq: { name: "Football IQ", value: 21 },
      kick_accuracy: { name: "Kick Accuracy", value: 39 },
      kick_power: { name: "Kick Power", value: 22 },
      pass_block: { name: "Pass Blocking", value: 17 },
      pass_rush: { name: "Pass Rush", value: 10 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 10 },
      run_block: { name: "Run Blocking", value: 10 },
      run_defense: { name: "Run Defense", value: 10 },
      speed: { name: "Speed", value: 58 },
      strength: { name: "Strength", value: 22 },
      tackle: { name: "Tackle", value: 10 },
      throw_power: { name: "Throw Power", value: 10 },
      throw_accuracy: { name: "Throw Accuracy", value: 10 },
      stamina: { name: "Stamina", value: 40 },
      potential: { name: "Potential", value: "C+" }
    }
  },
  {
    id: 14,
    name: "Nick Mazzaro",
    position: "QB",
    archtype: "Field General",
    overall: "A",
    year: "Sr.",
    height: "6'3\"",
    weight: "206 lbs",
    state: "NE",
    school: "Skutt Catholic",
    potential: "B-",
    jersey: "17",
    team: "California Golden Bears",
    designation: "QB1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 30 },
      agility: { name: "Agility", value: 28 },
      catching: { name: "Catching", value: 18 },
      zone_coverage: { name: "Zone Coverage", value: 20 },
      man_coverage: { name: "Man Coverage", value: 30 },
      football_iq: { name: "Football IQ", value: 50 },
      kick_accuracy: { name: "Kick Accuracy", value: 1 },
      kick_power: { name: "Kick Power", value: 1 },
      pass_block: { name: "Pass Blocking", value: 1 },
      pass_rush: { name: "Pass Rush", value: 1 },
      punt_accuracy: { name: "Punt Accuracy", value: 1 },
      punt_power: { name: "Punt Power", value: 1 },
      route_running: { name: "Route Running", value: 16 },
      run_block: { name: "Run Blocking", value: 1 },
      run_defense: { name: "Run Defense", value: 18 },
      speed: { name: "Speed", value: 55 },
      strength: { name: "Strength", value: 33 },
      tackle: { name: "Tackle", value: 19 },
      throw_power: { name: "Throw Power", value: 60 },
      throw_accuracy: { name: "Throw Accuracy", value: 50 },
      stamina: { name: "Stamina", value: 40 },
      potential: { name: "Potential", value: "B-" }
    }
  },
  {
    id: 15,
    name: "Morgan King",
    position: "ILB",
    archtype: "Field General",
    overall: "A",
    year: "Sr.",
    height: "6'1\"",
    weight: "228 lbs",
    state: "LA",
    school: "Opelousas",
    potential: "B",
    jersey: "46",
    team: "California Golden Bears",
    designation: "ILB1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 19 },
      agility: { name: "Agility", value: 46 },
      catching: { name: "Catching", value: 17 },
      zone_coverage: { name: "Zone Coverage", value: 48 },
      man_coverage: { name: "Man Coverage", value: 42 },
      football_iq: { name: "Football IQ", value: 54 },
      kick_accuracy: { name: "Kick Accuracy", value: 1 },
      kick_power: { name: "Kick Power", value: 1 },
      pass_block: { name: "Pass Blocking", value: 17 },
      pass_rush: { name: "Pass Rush", value: 26 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 10 },
      run_block: { name: "Run Blocking", value: 10 },
      run_defense: { name: "Run Defense", value: 51 },
      speed: { name: "Speed", value: 58 },
      strength: { name: "Strength", value: 53 },
      tackle: { name: "Tackle", value: 50 },
      throw_power: { name: "Throw Power", value: 16 },
      throw_accuracy: { name: "Throw Accuracy", value: 16 },
      stamina: { name: "Stamina", value: 60 },
      potential: { name: "Potential", value: "B" }
    }
  },
  {
    id: 16,
    name: "Jordan Toussaint",
    position: "DE",
    archtype: "Balanced",
    overall: "A",
    year: "Sr.",
    height: "6'3\"",
    weight: "273 lbs",
    state: "CA",
    school: "Eisenhower",
    potential: "C+",
    jersey: "60",
    team: "California Golden Bears",
    designation: "LE1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 19 },
      agility: { name: "Agility", value: 49 },
      catching: { name: "Catching", value: 16 },
      zone_coverage: { name: "Zone Coverage", value: 18 },
      man_coverage: { name: "Man Coverage", value: 17 },
      football_iq: { name: "Football IQ", value: 28 },
      kick_accuracy: { name: "Kick Accuracy", value: 10 },
      kick_power: { name: "Kick Power", value: 18 },
      pass_block: { name: "Pass Blocking", value: 7 },
      pass_rush: { name: "Pass Rush", value: 50 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 10 },
      run_block: { name: "Run Blocking", value: 10 },
      run_defense: { name: "Run Defense", value: 47 },
      speed: { name: "Speed", value: 58 },
      strength: { name: "Strength", value: 52 },
      tackle: { name: "Tackle", value: 47 },
      throw_power: { name: "Throw Power", value: 16 },
      throw_accuracy: { name: "Throw Accuracy", value: 16 },
      stamina: { name: "Stamina", value: 50 },
      potential: { name: "Potential", value: "C+" }
    }
  },
  {
    id: 17,
    name: "Adam Ijalana",
    position: "CB",
    archtype: "Man Coverage",
    overall: "A",
    year: "Sr.",
    height: "5'11\"",
    weight: "190 lbs",
    state: "TN",
    school: "Davidson Academy",
    potential: "A+",
    jersey: "43",
    team: "California Golden Bears",
    designation: "CB1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 19 },
      agility: { name: "Agility", value: 49 },
      catching: { name: "Catching", value: 22 },
      zone_coverage: { name: "Zone Coverage", value: 50 },
      man_coverage: { name: "Man Coverage", value: 53 },
      football_iq: { name: "Football IQ", value: 38 },
      kick_accuracy: { name: "Kick Accuracy", value: 10 },
      kick_power: { name: "Kick Power", value: 10 },
      pass_block: { name: "Pass Blocking", value: 10 },
      pass_rush: { name: "Pass Rush", value: 10 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 19 },
      run_block: { name: "Run Blocking", value: 10 },
      run_defense: { name: "Run Defense", value: 16 },
      speed: { name: "Speed", value: 58 },
      strength: { name: "Strength", value: 27 },
      tackle: { name: "Tackle", value: 29 },
      throw_power: { name: "Throw Power", value: 16 },
      throw_accuracy: { name: "Throw Accuracy", value: 16 },
      stamina: { name: "Stamina", value: 58 },
      potential: { name: "Potential", value: "A+" }
    }
  },
  {
    id: 18,
    name: "Tony Macura",
    position: "DT",
    archtype: "Balanced",
    overall: "A",
    year: "Jr.",
    height: "6'2\"",
    weight: "297 lbs",
    state: "FL",
    school: "Bishop Kenny",
    potential: "A-",
    jersey: "64",
    team: "California Golden Bears",
    designation: "DT1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 19 },
      agility: { name: "Agility", value: 27 },
      catching: { name: "Catching", value: 27 },
      zone_coverage: { name: "Zone Coverage", value: 26 },
      man_coverage: { name: "Man Coverage", value: 26 },
      football_iq: { name: "Football IQ", value: 40 },
      kick_accuracy: { name: "Kick Accuracy", value: 10 },
      kick_power: { name: "Kick Power", value: 10 },
      pass_block: { name: "Pass Blocking", value: 10 },
      pass_rush: { name: "Pass Rush", value: 56 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 16 },
      route_running: { name: "Route Running", value: 10 },
      run_block: { name: "Run Blocking", value: 10 },
      run_defense: { name: "Run Defense", value: 56 },
      speed: { name: "Speed", value: 58 },
      strength: { name: "Strength", value: 50 },
      tackle: { name: "Tackle", value: 50 },
      throw_power: { name: "Throw Power", value: 26 },
      throw_accuracy: { name: "Throw Accuracy", value: 17 },
      stamina: { name: "Stamina", value: 30 },
      potential: { name: "Potential", value: "A-" }
    }
  },
  {
    id: 19,
    name: "Brandon Adams",
    position: "OT",
    archtype: "Run Blocking",
    overall: "A",
    year: "Sr.",
    height: "6'3\"",
    weight: "286 lbs",
    state: "PA",
    school: "Garnet Valley",
    potential: "C",
    jersey: "61",
    team: "Michigan Wolverines",
    designation: "LT1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 18 },
      agility: { name: "Agility", value: 26 },
      catching: { name: "Catching", value: 17 },
      zone_coverage: { name: "Zone Coverage", value: 26 },
      man_coverage: { name: "Man Coverage", value: 26 },
      football_iq: { name: "Football IQ", value: 30 },
      kick_accuracy: { name: "Kick Accuracy", value: 10 },
      kick_power: { name: "Kick Power", value: 10 },
      pass_block: { name: "Pass Blocking", value: 44 },
      pass_rush: { name: "Pass Rush", value: 31 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 10 },
      run_block: { name: "Run Blocking", value: 49 },
      run_defense: { name: "Run Defense", value: 1 },
      speed: { name: "Speed", value: 28 },
      strength: { name: "Strength", value: 52 },
      tackle: { name: "Tackle", value: 18 },
      throw_power: { name: "Throw Power", value: 16 },
      throw_accuracy: { name: "Throw Accuracy", value: 17 },
      stamina: { name: "Stamina", value: 30 },
      potential: { name: "Potential", value: "C" }
    }
  },
  {
    id: 20,
    name: "Miguel Simon",
    position: "DE",
    archtype: "Balanced",
    overall: "A",
    year: "Sr.",
    height: "6'4\"",
    weight: "264 lbs",
    state: "OH",
    school: "Bread Boy",
    potential: "C+",
    jersey: "00",
    team: "Michigan Wolverines",
    designation: "LE1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 26 },
      agility: { name: "Agility", value: 52 },
      catching: { name: "Catching", value: 27 },
      zone_coverage: { name: "Zone Coverage", value: 16 },
      man_coverage: { name: "Man Coverage", value: 16 },
      football_iq: { name: "Football IQ", value: 40 },
      kick_accuracy: { name: "Kick Accuracy", value: 10 },
      kick_power: { name: "Kick Power", value: 10 },
      pass_block: { name: "Pass Blocking", value: 10 },
      pass_rush: { name: "Pass Rush", value: 55 },
      punt_accuracy: { name: "Punt Accuracy", value: 16 },
      punt_power: { name: "Punt Power", value: 16 },
      route_running: { name: "Route Running", value: 10 },
      run_block: { name: "Run Blocking", value: 12 },
      run_defense: { name: "Run Defense", value: 43 },
      speed: { name: "Speed", value: 52 },
      strength: { name: "Strength", value: 48 },
      tackle: { name: "Tackle", value: 56 },
      throw_power: { name: "Throw Power", value: 26 },
      throw_accuracy: { name: "Throw Accuracy", value: 18 },
      stamina: { name: "Stamina", value: 49 },
      potential: { name: "Potential", value: "C+" }
    }
  },
  {
    id: 21,
    name: "DaVonte Logan",
    position: "OT",
    archtype: "Run Blocking",
    overall: "A",
    year: "So.",
    height: "6'4\"",
    weight: "289 lbs",
    state: "FL",
    school: "Lake Gibson",
    potential: "C+",
    jersey: "58",
    team: "Michigan Wolverines",
    designation: "RT1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 28 },
      agility: { name: "Agility", value: 47 },
      catching: { name: "Catching", value: 28 },
      zone_coverage: { name: "Zone Coverage", value: 16 },
      man_coverage: { name: "Man Coverage", value: 16 },
      football_iq: { name: "Football IQ", value: 44 },
      kick_accuracy: { name: "Kick Accuracy", value: 10 },
      kick_power: { name: "Kick Power", value: 10 },
      pass_block: { name: "Pass Blocking", value: 43 },
      pass_rush: { name: "Pass Rush", value: 26 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 17 },
      run_block: { name: "Run Blocking", value: 46 },
      run_defense: { name: "Run Defense", value: 22 },
      speed: { name: "Speed", value: 53 },
      strength: { name: "Strength", value: 50 },
      tackle: { name: "Tackle", value: 29 },
      throw_power: { name: "Throw Power", value: 16 },
      throw_accuracy: { name: "Throw Accuracy", value: 17 },
      stamina: { name: "Stamina", value: 50 },
      potential: { name: "Potential", value: "C+" }
    }
  },
  {
    id: 22,
    name: "Blake Toussaint",
    position: "SS",
    archtype: "Zone Coverage",
    overall: "B",
    year: "Sr.",
    height: "5'11\"",
    weight: "196 lbs",
    state: "NJ",
    school: "Red Bank Regional",
    potential: "C",
    jersey: "36",
    team: "Michigan Wolverines",
    designation: "SS1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 18 },
      agility: { name: "Agility", value: 54 },
      catching: { name: "Catching", value: 17 },
      zone_coverage: { name: "Zone Coverage", value: 49 },
      man_coverage: { name: "Man Coverage", value: 46 },
      football_iq: { name: "Football IQ", value: 41 },
      kick_accuracy: { name: "Kick Accuracy", value: 10 },
      kick_power: { name: "Kick Power", value: 10 },
      pass_block: { name: "Pass Blocking", value: 10 },
      pass_rush: { name: "Pass Rush", value: 56 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 16 },
      route_running: { name: "Route Running", value: 19 },
      run_block: { name: "Run Blocking", value: 10 },
      run_defense: { name: "Run Defense", value: 51 },
      speed: { name: "Speed", value: 55 },
      strength: { name: "Strength", value: 20 },
      tackle: { name: "Tackle", value: 27 },
      throw_power: { name: "Throw Power", value: 16 },
      throw_accuracy: { name: "Throw Accuracy", value: 17 },
      stamina: { name: "Stamina", value: 60 },
      potential: { name: "Potential", value: "C" }
    }
  },
  {
    id: 23,
    name: "Cody Hankins",
    position: "OLB",
    archtype: "Pass Rush",
    overall: "B",
    year: "Sr.",
    height: "6'4\"",
    weight: "245 lbs",
    state: "MD",
    school: "St. Mary's",
    potential: "B",
    jersey: "44",
    team: "Michigan Wolverines",
    designation: "LOLB1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 21 },
      agility: { name: "Agility", value: 47 },
      catching: { name: "Catching", value: 16 },
      zone_coverage: { name: "Zone Coverage", value: 28 },
      man_coverage: { name: "Man Coverage", value: 29 },
      football_iq: { name: "Football IQ", value: 31 },
      kick_accuracy: { name: "Kick Accuracy", value: 10 },
      kick_power: { name: "Kick Power", value: 10 },
      pass_block: { name: "Pass Blocking", value: 10 },
      pass_rush: { name: "Pass Rush", value: 59 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 10 },
      run_block: { name: "Run Blocking", value: 10 },
      run_defense: { name: "Run Defense", value: 36 },
      speed: { name: "Speed", value: 53 },
      strength: { name: "Strength", value: 40 },
      tackle: { name: "Tackle", value: 49 },
      throw_power: { name: "Throw Power", value: 10 },
      throw_accuracy: { name: "Throw Accuracy", value: 10 },
      stamina: { name: "Stamina", value: 59 },
      potential: { name: "Potential", value: "B" }
    }
  },
  {
    id: 24,
    name: "Noah Pillar",
    position: "DE",
    archtype: "Speed Rusher",
    overall: "A",
    year: "Sr.",
    height: "6'4\"",
    weight: "231 lbs",
    state: "FL",
    school: "Sebastian River",
    potential: "B",
    jersey: "68",
    team: "New Mexico Lobos",
    designation: "LE1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 28 },
      agility: { name: "Agility", value: 53 },
      catching: { name: "Catching", value: 16 },
      zone_coverage: { name: "Zone Coverage", value: 18 },
      man_coverage: { name: "Man Coverage", value: 19 },
      football_iq: { name: "Football IQ", value: 34 },
      kick_accuracy: { name: "Kick Accuracy", value: 10 },
      kick_power: { name: "Kick Power", value: 17 },
      pass_block: { name: "Pass Blocking", value: 10 },
      pass_rush: { name: "Pass Rush", value: 63 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 16 },
      run_block: { name: "Run Blocking", value: 16 },
      run_defense: { name: "Run Defense", value: 50 },
      speed: { name: "Speed", value: 53 },
      strength: { name: "Strength", value: 48 },
      tackle: { name: "Tackle", value: 47 },
      throw_power: { name: "Throw Power", value: 10 },
      throw_accuracy: { name: "Throw Accuracy", value: 10 },
      stamina: { name: "Stamina", value: 33 },
      potential: { name: "Potential", value: "B" }
    }
  },
  {
    id: 25,
    name: "Arthur Dominguez",
    position: "OT",
    archtype: "Run Blocking",
    overall: "A",
    year: "Sr.",
    height: "6'4\"",
    weight: "310 lbs",
    state: "FL",
    school: "Berkeley Prep",
    potential: "B-",
    jersey: "72",
    team: "New Mexico Lobos",
    designation: "LT1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 21 },
      agility: { name: "Agility", value: 27 },
      catching: { name: "Catching", value: 16 },
      zone_coverage: { name: "Zone Coverage", value: 18 },
      man_coverage: { name: "Man Coverage", value: 19 },
      football_iq: { name: "Football IQ", value: 36 },
      kick_accuracy: { name: "Kick Accuracy", value: 10 },
      kick_power: { name: "Kick Power", value: 10 },
      pass_block: { name: "Pass Blocking", value: 40 },
      pass_rush: { name: "Pass Rush", value: 19 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 17 },
      route_running: { name: "Route Running", value: 16 },
      run_block: { name: "Run Blocking", value: 45 },
      run_defense: { name: "Run Defense", value: 17 },
      speed: { name: "Speed", value: 46 },
      strength: { name: "Strength", value: 55 },
      tackle: { name: "Tackle", value: 23 },
      throw_power: { name: "Throw Power", value: 10 },
      throw_accuracy: { name: "Throw Accuracy", value: 10 },
      stamina: { name: "Stamina", value: 60 },
      potential: { name: "Potential", value: "B-" }
    }
  },
  {
    id: 26,
    name: "Luis Wong",
    position: "CB",
    archtype: "Ball Hawk",
    overall: "A",
    year: "Sr.",
    height: "5'11\"",
    weight: "189 lbs",
    state: "TX",
    school: "John Tyler",
    potential: "B+",
    jersey: "25",
    team: "New Mexico Lobos",
    designation: "CB1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 21 },
      agility: { name: "Agility", value: 47 },
      catching: { name: "Catching", value: 38 },
      zone_coverage: { name: "Zone Coverage", value: 46 },
      man_coverage: { name: "Man Coverage", value: 48 },
      football_iq: { name: "Football IQ", value: 39 },
      kick_accuracy: { name: "Kick Accuracy", value: 10 },
      kick_power: { name: "Kick Power", value: 10 },
      pass_block: { name: "Pass Blocking", value: 10 },
      pass_rush: { name: "Pass Rush", value: 19 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 10 },
      run_block: { name: "Run Blocking", value: 10 },
      run_defense: { name: "Run Defense", value: 16 },
      speed: { name: "Speed", value: 50 },
      strength: { name: "Strength", value: 18 },
      tackle: { name: "Tackle", value: 28 },
      throw_power: { name: "Throw Power", value: 20 },
      throw_accuracy: { name: "Throw Accuracy", value: 21 },
      stamina: { name: "Stamina", value: 46 },
      potential: { name: "Potential", value: "B+" }
    }
  },
  {
    id: 27,
    name: "Hyun-Jin Robinson",
    position: "FB",
    archtype: "Balanced",
    overall: "A",
    year: "Sr.",
    height: "5'11\"",
    weight: "232 lbs",
    state: "FL",
    school: "",
    potential: "C+",
    jersey: "33",
    team: "New Mexico Lobos",
    designation: "FB1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 31 },
      agility: { name: "Agility", value: 37 },
      catching: { name: "Catching", value: 26 },
      zone_coverage: { name: "Zone Coverage", value: 18 },
      man_coverage: { name: "Man Coverage", value: 18 },
      football_iq: { name: "Football IQ", value: 41 },
      kick_accuracy: { name: "Kick Accuracy", value: 10 },
      kick_power: { name: "Kick Power", value: 10 },
      pass_block: { name: "Pass Blocking", value: 49 },
      pass_rush: { name: "Pass Rush", value: 29 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 10 },
      run_block: { name: "Run Blocking", value: 51 },
      run_defense: { name: "Run Defense", value: 36 },
      speed: { name: "Speed", value: 33 },
      strength: { name: "Strength", value: 50 },
      tackle: { name: "Tackle", value: 19 },
      throw_power: { name: "Throw Power", value: 18 },
      throw_accuracy: { name: "Throw Accuracy", value: 18 },
      stamina: { name: "Stamina", value: 32 },
      potential: { name: "Potential", value: "C+" }
    }
  },
  {
    id: 28,
    name: "Melky Hughes",
    position: "OG",
    archtype: "Pass Blocking",
    overall: "A",
    year: "Sr.",
    height: "6'2\"",
    weight: "296 lbs",
    state: "VA",
    school: "Abingdon",
    potential: "B+",
    jersey: "66",
    team: "New Mexico Lobos",
    designation: "LG1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 20 },
      agility: { name: "Agility", value: 27 },
      catching: { name: "Catching", value: 18 },
      zone_coverage: { name: "Zone Coverage", value: 18 },
      man_coverage: { name: "Man Coverage", value: 10 },
      football_iq: { name: "Football IQ", value: 33 },
      kick_accuracy: { name: "Kick Accuracy", value: 10 },
      kick_power: { name: "Kick Power", value: 10 },
      pass_block: { name: "Pass Blocking", value: 49 },
      pass_rush: { name: "Pass Rush", value: 10 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 10 },
      run_block: { name: "Run Blocking", value: 42 },
      run_defense: { name: "Run Defense", value: 10 },
      speed: { name: "Speed", value: 23 },
      strength: { name: "Strength", value: 50 },
      tackle: { name: "Tackle", value: 19 },
      throw_power: { name: "Throw Power", value: 10 },
      throw_accuracy: { name: "Throw Accuracy", value: 10 },
      stamina: { name: "Stamina", value: 70 },
      potential: { name: "Potential", value: "B+" }
    }
  },
  {
    id: 29,
    name: "Nathan Burke",
    position: "ILB",
    archtype: "Field General",
    overall: "A",
    year: "Sr.",
    height: "6'1\"",
    weight: "229 lbs",
    state: "OR",
    school: "Jesuit",
    potential: "A-",
    jersey: "46",
    team: "LSU Tigers",
    designation: "ILB1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 30 },
      agility: { name: "Agility", value: 57 },
      catching: { name: "Catching", value: 18 },
      zone_coverage: { name: "Zone Coverage", value: 48 },
      man_coverage: { name: "Man Coverage", value: 37 },
      football_iq: { name: "Football IQ", value: 53 },
      kick_accuracy: { name: "Kick Accuracy", value: 10 },
      kick_power: { name: "Kick Power", value: 16 },
      pass_block: { name: "Pass Blocking", value: 19 },
      pass_rush: { name: "Pass Rush", value: 33 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 17 },
      run_block: { name: "Run Blocking", value: 19 },
      run_defense: { name: "Run Defense", value: 44 },
      speed: { name: "Speed", value: 53 },
      strength: { name: "Strength", value: 50 },
      tackle: { name: "Tackle", value: 59 },
      throw_power: { name: "Throw Power", value: 19 },
      throw_accuracy: { name: "Throw Accuracy", value: 18 },
      stamina: { name: "Stamina", value: 60 },
      potential: { name: "Potential", value: "A-" }
    }
  },
  {
    id: 30,
    name: "Marchie Pedroia",
    position: "FS",
    archtype: "Man Coverage",
    overall: "A",
    year: "Sr.",
    height: "6'0\"",
    weight: "205 lbs",
    state: "OK",
    school: "Berryhill",
    potential: "C+",
    jersey: "93",
    team: "LSU Tigers",
    designation: "FS1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 20 },
      agility: { name: "Agility", value: 47 },
      catching: { name: "Catching", value: 18 },
      zone_coverage: { name: "Zone Coverage", value: 40 },
      man_coverage: { name: "Man Coverage", value: 50 },
      football_iq: { name: "Football IQ", value: 38 },
      kick_accuracy: { name: "Kick Accuracy", value: 10 },
      kick_power: { name: "Kick Power", value: 18 },
      pass_block: { name: "Pass Blocking", value: 10 },
      pass_rush: { name: "Pass Rush", value: 10 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 30 },
      run_block: { name: "Run Blocking", value: 10 },
      run_defense: { name: "Run Defense", value: 40 },
      speed: { name: "Speed", value: 47 },
      strength: { name: "Strength", value: 46 },
      tackle: { name: "Tackle", value: 39 },
      throw_power: { name: "Throw Power", value: 10 },
      throw_accuracy: { name: "Throw Accuracy", value: 10 },
      stamina: { name: "Stamina", value: 50 },
      potential: { name: "Potential", value: "C+" }
    }
  },
  {
    id: 31,
    name: "Jeremy Moreland",
    position: "CB",
    archtype: "Zone Coverage",
    overall: "A",
    year: "Sr.",
    height: "5'11\"",
    weight: "186 lbs",
    state: "LA",
    school: "Central Catholic",
    potential: "B-",
    jersey: "35",
    team: "LSU Tigers",
    designation: "CB1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 29 },
      agility: { name: "Agility", value: 57 },
      catching: { name: "Catching", value: 10 },
      zone_coverage: { name: "Zone Coverage", value: 38 },
      man_coverage: { name: "Man Coverage", value: 40 },
      football_iq: { name: "Football IQ", value: 43 },
      kick_accuracy: { name: "Kick Accuracy", value: 10 },
      kick_power: { name: "Kick Power", value: 10 },
      pass_block: { name: "Pass Blocking", value: 19 },
      pass_rush: { name: "Pass Rush", value: 17 },
      punt_accuracy: { name: "Punt Accuracy", value: 15 },
      punt_power: { name: "Punt Power", value: 16 },
      route_running: { name: "Route Running", value: 10 },
      run_block: { name: "Run Blocking", value: 16 },
      run_defense: { name: "Run Defense", value: 16 },
      speed: { name: "Speed", value: 53 },
      strength: { name: "Strength", value: 20 },
      tackle: { name: "Tackle", value: 29 },
      throw_power: { name: "Throw Power", value: 10 },
      throw_accuracy: { name: "Throw Accuracy", value: 10 },
      stamina: { name: "Stamina", value: 60 },
      potential: { name: "Potential", value: "B-" }
    }
  },
  {
    id: 32,
    name: "Jose Smith",
    position: "OG",
    archtype: "Balanced",
    overall: "A",
    year: "Sr.",
    height: "6'3\"",
    weight: "303 lbs",
    state: "NC",
    school: "Watauga",
    potential: "C",
    jersey: "68",
    team: "LSU Tigers",
    designation: "LG1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 20 },
      agility: { name: "Agility", value: 29 },
      catching: { name: "Catching", value: 28 },
      zone_coverage: { name: "Zone Coverage", value: 18 },
      man_coverage: { name: "Man Coverage", value: 18 },
      football_iq: { name: "Football IQ", value: 31 },
      kick_accuracy: { name: "Kick Accuracy", value: 10 },
      kick_power: { name: "Kick Power", value: 10 },
      pass_block: { name: "Pass Blocking", value: 49 },
      pass_rush: { name: "Pass Rush", value: 18 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 20 },
      run_block: { name: "Run Blocking", value: 42 },
      run_defense: { name: "Run Defense", value: 10 },
      speed: { name: "Speed", value: 33 },
      strength: { name: "Strength", value: 50 },
      tackle: { name: "Tackle", value: 19 },
      throw_power: { name: "Throw Power", value: 16 },
      throw_accuracy: { name: "Throw Accuracy", value: 16 },
      stamina: { name: "Stamina", value: 40 },
      potential: { name: "Potential", value: "C" }
    }
  },
  {
    id: 33,
    name: "Garrison Hoes",
    position: "DE",
    archtype: "Balanced",
    overall: "A",
    year: "Jr.",
    height: "6'4\"",
    weight: "262 lbs",
    state: "CO",
    school: "Grandview",
    potential: "B-",
    jersey: "69",
    team: "LSU Tigers",
    designation: "LE1",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 20 },
      agility: { name: "Agility", value: 47 },
      catching: { name: "Catching", value: 28 },
      zone_coverage: { name: "Zone Coverage", value: 32 },
      man_coverage: { name: "Man Coverage", value: 20 },
      football_iq: { name: "Football IQ", value: 39 },
      kick_accuracy: { name: "Kick Accuracy", value: 18 },
      kick_power: { name: "Kick Power", value: 10 },
      pass_block: { name: "Pass Blocking", value: 19 },
      pass_rush: { name: "Pass Rush", value: 54 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 10 },
      run_block: { name: "Run Blocking", value: 12 },
      run_defense: { name: "Run Defense", value: 50 },
      speed: { name: "Speed", value: 53 },
      strength: { name: "Strength", value: 50 },
      tackle: { name: "Tackle", value: 48 },
      throw_power: { name: "Throw Power", value: 20 },
      throw_accuracy: { name: "Throw Accuracy", value: 28 },
      stamina: { name: "Stamina", value: 60 },
      potential: { name: "Potential", value: "B-" }
    }
  }
];

export default SampleContent;
