const SampleContent = [
  {
    id: 1,
    name: "Aaron Kotar",
    position: "QB",
    archtype: "Scrambler",
    overall: "B",
    year: "(Sr.)",
    height: "6'2\"",
    weight: "205 lbs",
    state: "Ohio",
    school: "Buckeye High",
    potential: "C",
    jersey: "12",
    team: "Washington State Cougars",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 40 },
      agility: { name: "Agility", value: 35 },
      catching: { name: "Catching", value: 20 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 0 },
      football_iq: { name: "Football IQ", value: 40 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 100 },
      pass_block: { name: "Pass Blocking", value: 0 },
      pass_rush: { name: "Pass Rush", value: 0 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 5 },
      run_block: { name: "Run Blocking", value: 0 },
      run_defense: { name: "Run Defense", value: 0 },
      speed: { name: "Speed", value: 69, priority: 4 },
      strength: { name: "Strength", value: 30, priority: 2 },
      tackle: { name: "Tackle", value: 0 },
      throw_power: { name: "Throw Power", value: 43, priority: 5 },
      throw_accuracy: { name: "Throw Accuracy", value: 43, priority: 6 }
    }
  },
  {
    id: 2,
    name: "Marquise Mariota",
    position: "QB",
    archtype: "Balanced",
    overall: "A",
    year: "(Fr.)",
    height: "6'4\"",
    weight: "235 lbs",
    state: "Hawaii",
    school: "St. Louis HS",
    potential: "C",
    jersey: "2",
    team: "Washington State Cougars",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 40 },
      agility: { name: "Agility", value: 35 },
      catching: { name: "Catching", value: 20 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 0 },
      football_iq: { name: "Football IQ", value: 40 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 100 },
      pass_block: { name: "Pass Blocking", value: 0 },
      pass_rush: { name: "Pass Rush", value: 0 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 5 },
      run_block: { name: "Run Blocking", value: 0 },
      run_defense: { name: "Run Defense", value: 0 },
      speed: { name: "Speed", value: 69, priority: 3 },
      strength: { name: "Strength", value: 30 },
      tackle: { name: "Tackle", value: 0 },
      throw_power: { name: "Throw Power", value: 43 },
      throw_accuracy: { name: "Throw Accuracy", value: 43 }
    }
  },
  {
    id: 3,
    name: "Cal Beckam Jr",
    position: "WR",
    archtype: "Speed",
    overall: "C+",
    year: "So.",
    height: "6'5\"",
    weight: "200 lbs",
    state: "Texas",
    school: "Midway Highschool",
    potential: "B-",
    jersey: "15",
    team: "Washington State Cougars",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 40 },
      agility: { name: "Agility", value: 45 },
      catching: { name: "Catching", value: 55 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 0 },
      football_iq: { name: "Football IQ", value: 52 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 100 },
      pass_block: { name: "Pass Blocking", value: 0 },
      pass_rush: { name: "Pass Rush", value: 0 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 33 },
      run_block: { name: "Run Blocking", value: 0 },
      run_defense: { name: "Run Defense", value: 0 },
      speed: { name: "Speed", value: 77 },
      strength: { name: "Strength", value: 22 },
      tackle: { name: "Tackle", value: 0 },
      throw_power: { name: "Throw Power", value: 12 },
      throw_accuracy: { name: "Throw Accuracy", value: 5 }
    }
  },
  {
    id: 4,
    name: "Chris Cross",
    position: "DE",
    archtype: "Speed Rusher",
    overall: "A",
    year: "Jr.",
    height: "6'7\"",
    weight: "261 lbs",
    state: "Georgia",
    school: "George Southwest CC",
    potential: "A",
    jersey: "72",
    team: "Washington State Cougars",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 40 },
      agility: { name: "Agility", value: 55 },
      catching: { name: "Catching", value: 20 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 20 },
      football_iq: { name: "Football IQ", value: 38 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 5 },
      pass_block: { name: "Pass Blocking", value: 0 },
      pass_rush: { name: "Pass Rush", value: 52 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 5 },
      run_block: { name: "Run Blocking", value: 0 },
      run_defense: { name: "Run Defense", value: 37 },
      speed: { name: "Speed", value: 60 },
      strength: { name: "Strength", value: 41 },
      tackle: { name: "Tackle", value: 54 },
      throw_power: { name: "Throw Power", value: 1 },
      throw_accuracy: { name: "Throw Accuracy", value: 1 }
    }
  },
  {
    id: 5,
    name: "Quincy Sanford",
    position: "CB",
    archtype: "Ball Hawk",
    overall: "D",
    year: "Sr.",
    height: "5'9\"",
    weight: "110 lbs",
    state: "Delaware",
    school: "Barack Obama HS",
    potential: "D",
    jersey: "30",
    team: "Washington State Cougars",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 22 },
      agility: { name: "Agility", value: 42 },
      catching: { name: "Catching", value: 35 },
      zone_coverage: { name: "Zone Coverage", value: 37 },
      man_coverage: { name: "Man Coverage", value: 39 },
      football_iq: { name: "Football IQ", value: 23 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 100 },
      pass_block: { name: "Pass Blocking", value: 0 },
      pass_rush: { name: "Pass Rush", value: 0 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 5 },
      run_block: { name: "Run Blocking", value: 0 },
      run_defense: { name: "Run Defense", value: 0 },
      speed: { name: "Speed", value: 41 },
      strength: { name: "Strength", value: 7 },
      tackle: { name: "Tackle", value: 11 },
      throw_power: { name: "Throw Power", value: 1 },
      throw_accuracy: { name: "Throw Accuracy", value: 1 }
    }
  },
  {
    id: 6,
    name: "Beau Allen",
    position: "DT",
    archtype: "Nose Tackle",
    overall: "A",
    year: "(Sr.)",
    height: "6'5\"",
    weight: "291 lbs",
    state: "Minnesota",
    school: "Minnetonka High School",
    potential: "B",
    jersey: "30",
    team: "Washington State Cougars",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 24 },
      agility: { name: "Agility", value: 35 },
      catching: { name: "Catching", value: 21 },
      zone_coverage: { name: "Zone Coverage", value: 8 },
      man_coverage: { name: "Man Coverage", value: 6 },
      football_iq: { name: "Football IQ", value: 26 },
      kick_accuracy: { name: "Kick Accuracy", value: 1 },
      kick_power: { name: "Kick Power", value: 1 },
      pass_block: { name: "Pass Blocking", value: 1 },
      pass_rush: { name: "Pass Rush", value: 33 },
      punt_accuracy: { name: "Punt Accuracy", value: 2 },
      punt_power: { name: "Punt Power", value: 2 },
      route_running: { name: "Route Running", value: 3 },
      run_block: { name: "Run Blocking", value: 10 },
      run_defense: { name: "Run Defense", value: 50 },
      speed: { name: "Speed", value: 28 },
      strength: { name: "Strength", value: 50 },
      tackle: { name: "Tackle", value: 40 },
      throw_power: { name: "Throw Power", value: 23 },
      throw_accuracy: { name: "Throw Accuracy", value: 16 }
    }
  },
  {
    id: 7,
    name: "Rob Adams",
    position: "OT",
    archtype: "Run Blocking",
    overall: "A",
    year: "Sr.",
    height: "6'3\"",
    weight: "219 lbs",
    state: "Florida",
    school: "Harmony",
    potential: "C",
    jersey: "61",
    team: "Washington State Cougars",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 16 },
      agility: { name: "Agility", value: 29 },
      catching: { name: "Catching", value: 16 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 0 },
      football_iq: { name: "Football IQ", value: 26 },
      kick_accuracy: { name: "Kick Accuracy", value: 1 },
      kick_power: { name: "Kick Power", value: 3 },
      pass_block: { name: "Pass Blocking", value: 30 },
      pass_rush: { name: "Pass Rush", value: 16 },
      punt_accuracy: { name: "Punt Accuracy", value: 5 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 10 },
      run_block: { name: "Run Blocking", value: 45 },
      run_defense: { name: "Run Defense", value: 6 },
      speed: { name: "Speed", value: 23 },
      strength: { name: "Strength", value: 47 },
      tackle: { name: "Tackle", value: 20 },
      throw_power: { name: "Throw Power", value: 3 },
      throw_accuracy: { name: "Throw Accuracy", value: 3 }
    }
  },
  {
    id: 8,
    name: "Jonas Skipper",
    position: "OG",
    archtype: "Balanced",
    overall: "A",
    year: "Sr.",
    height: "6'5\"",
    weight: "294 lbs",
    state: "Missouri",
    school: "Cassville",
    potential: "C+",
    jersey: "51",
    team: "Washington State Cougars",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 20 },
      agility: { name: "Agility", value: 23 },
      catching: { name: "Catching", value: 26 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 0 },
      football_iq: { name: "Football IQ", value: 31 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 1 },
      pass_block: { name: "Pass Blocking", value: 37 },
      pass_rush: { name: "Pass Rush", value: 12 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 5 },
      run_block: { name: "Run Blocking", value: 33 },
      run_defense: { name: "Run Defense", value: 0 },
      speed: { name: "Speed", value: 30 },
      strength: { name: "Strength", value: 58 },
      tackle: { name: "Tackle", value: 0 },
      throw_power: { name: "Throw Power", value: 2 },
      throw_accuracy: { name: "Throw Accuracy", value: 2 }
    }
  },
  {
    id: 9,
    name: "Chris Butera",
    position: "OG",
    archtype: "Run Blocking",
    overall: "A",
    year: "Jr.",
    height: "6'5\"",
    weight: "306 lbs",
    state: "TX",
    school: "Manvel",
    potential: "B+",
    jersey: "63",
    team: "Washington State Cougars",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 20 },
      agility: { name: "Agility", value: 23 },
      catching: { name: "Catching", value: 26 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 0 },
      football_iq: { name: "Football IQ", value: 31 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 1 },
      pass_block: { name: "Pass Blocking", value: 37 },
      pass_rush: { name: "Pass Rush", value: 12 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 5 },
      run_block: { name: "Run Blocking", value: 57 },
      run_defense: { name: "Run Defense", value: 0 },
      speed: { name: "Speed", value: 30 },
      strength: { name: "Strength", value: 58 },
      tackle: { name: "Tackle", value: 0 },
      throw_power: { name: "Throw Power", value: 2 },
      throw_accuracy: { name: "Throw Accuracy", value: 2 }
    }
  },
  {
    id: 10,
    name: "Chris Hinojosa",
    position: "ILB",
    archtype: "Field General",
    overall: "B",
    year: "Sr.",
    height: "6'0\"",
    weight: "234 lbs",
    state: "NJ",
    school: "West Long Branch",
    potential: "C+",
    jersey: "53",
    team: "Washington State Cougars",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 20 },
      agility: { name: "Agility", value: 37 },
      catching: { name: "Catching", value: 18 },
      zone_coverage: { name: "Zone Coverage", value: 39 },
      man_coverage: { name: "Man Coverage", value: 30 },
      football_iq: { name: "Football IQ", value: 40 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 0 },
      pass_block: { name: "Pass Blocking", value: 0 },
      pass_rush: { name: "Pass Rush", value: 17 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 5 },
      run_block: { name: "Run Blocking", value: 0 },
      run_defense: { name: "Run Defense", value: 30 },
      speed: { name: "Speed", value: 42 },
      strength: { name: "Strength", value: 32 },
      tackle: { name: "Tackle", value: 38 },
      throw_power: { name: "Throw Power", value: 43 },
      throw_accuracy: { name: "Throw Accuracy", value: 43 }
    }
  },
  {
    id: 11,
    name: "Bobby Hammel",
    position: "OLB",
    archtype: "Pass Rush",
    overall: "B",
    year: "Sr.",
    height: "6'3\"",
    weight: "246 lbs",
    state: "NC",
    school: "Kinston",
    potential: "C+",
    jersey: "50",
    team: "Washington State Cougars",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 20 },
      agility: { name: "Agility", value: 39 },
      catching: { name: "Catching", value: 18 },
      zone_coverage: { name: "Zone Coverage", value: 26 },
      man_coverage: { name: "Man Coverage", value: 25 },
      football_iq: { name: "Football IQ", value: 28 },
      kick_accuracy: { name: "Kick Accuracy", value: 0 },
      kick_power: { name: "Kick Power", value: 0 },
      pass_block: { name: "Pass Blocking", value: 10 },
      pass_rush: { name: "Pass Rush", value: 43 },
      punt_accuracy: { name: "Punt Accuracy", value: 0 },
      punt_power: { name: "Punt Power", value: 5 },
      route_running: { name: "Route Running", value: 5 },
      run_block: { name: "Run Blocking", value: 1 },
      run_defense: { name: "Run Defense", value: 26 },
      speed: { name: "Speed", value: 45 },
      strength: { name: "Strength", value: 32 },
      tackle: { name: "Tackle", value: 37 },
      throw_power: { name: "Throw Power", value: 1 },
      throw_accuracy: { name: "Throw Accuracy", value: 1 }
    }
  },
  {
    id: 12,
    name: "Darin Howard",
    position: "K",
    archtype: "Accuracy",
    overall: "B",
    year: "Sr.",
    height: "5'11\"",
    weight: "193 lbs",
    state: "WA",
    school: "Seattle Prep",
    potential: "C+",
    jersey: "40",
    team: "Washington State Cougars",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 10 },
      agility: { name: "Agility", value: 10 },
      catching: { name: "Catching", value: 10 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 10 },
      football_iq: { name: "Football IQ", value: 23 },
      kick_accuracy: { name: "Kick Accuracy", value: 39 },
      kick_power: { name: "Kick Power", value: 22 },
      pass_block: { name: "Pass Blocking", value: 10 },
      pass_rush: { name: "Pass Rush", value: 10 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 10 },
      run_block: { name: "Run Blocking", value: 10 },
      run_defense: { name: "Run Defense", value: 10 },
      speed: { name: "Speed", value: 10 },
      strength: { name: "Strength", value: 10 },
      tackle: { name: "Tackle", value: 10 },
      throw_power: { name: "Throw Power", value: 10 },
      throw_accuracy: { name: "Throw Accuracy", value: 10 }
    }
  },
  {
    id: 13,
    name: "Chris Tilson",
    position: "RB",
    archtype: "Speed",
    overall: "B",
    year: "Jr.",
    height: "5'11\"",
    weight: "203 lbs",
    state: "OK",
    school: "Victory Christian",
    potential: "C+",
    jersey: "24",
    team: "Washington State Cougars",
    // Attributes === attr
    attr: {
      carrying: { name: "Carrying", value: 19 },
      agility: { name: "Agility", value: 23 },
      catching: { name: "Catching", value: 15 },
      zone_coverage: { name: "Zone Coverage", value: 10 },
      man_coverage: { name: "Man Coverage", value: 10 },
      football_iq: { name: "Football IQ", value: 21 },
      kick_accuracy: { name: "Kick Accuracy", value: 39 },
      kick_power: { name: "Kick Power", value: 22 },
      pass_block: { name: "Pass Blocking", value: 17 },
      pass_rush: { name: "Pass Rush", value: 10 },
      punt_accuracy: { name: "Punt Accuracy", value: 10 },
      punt_power: { name: "Punt Power", value: 10 },
      route_running: { name: "Route Running", value: 10 },
      run_block: { name: "Run Blocking", value: 10 },
      run_defense: { name: "Run Defense", value: 10 },
      speed: { name: "Speed", value: 58 },
      strength: { name: "Strength", value: 22 },
      tackle: { name: "Tackle", value: 10 },
      throw_power: { name: "Throw Power", value: 10 },
      throw_accuracy: { name: "Throw Accuracy", value: 10 }
    }
  }
];

export default SampleContent;
