export const PositionList = [
    { name: 'Point Guards', abbr: 'PG' },
    { name: 'Shooting Guards', abbr: 'SG' },
    { name: 'Power Forwards', abbr: 'PF' },
    { name: 'Small Forwards', abbr: 'SF' },
    { name: 'Centers', abbr: 'C' }
];

export const CountryList = [
    'USA',
    'Canada',
    'Algeria',
    'Argentina',
    'Austria',
    'Bangladesh',
    'Belgium',
    'Belize',
    'Brazil',
    'Bulgaria',
    'Cambodia',
    'Cameroon',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'DCR',
    'Democratic Republic of Congo',
    'Denmark',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'Finland',
    'France',
    'French Guiana',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guinea',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'India',
    'Indonesia',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Kenya',
    'Liberia',
    'Luxembourg',
    'Malawi',
    'Malaysia',
    'Mexico',
    'Montenegro',
    'Morocco',
    'Nicaragua',
    'Nigeria',
    'North Korea',
    'Norway',
    'Panama',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Romania',
    'Russia',
    'Senegal',
    'Serbia',
    'South Africa',
    'South Korea',
    'Spain',
    'Suriname',
    'Sweden',
    'Taiwan',
    'Tanzania',
    'Thailand',
    'Turkey',
    'Uganda',
    'Ukraine',
    'Uruguay',
    'Venezuela',
    'Vietnam',
    'Zambia',
    'Zimbabwe',
    'Antarctica'
];

export const StatesList = [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'District of Columbia',
    'Florida',
    'Georgia',
    'Guam',
    "Hawai'i",
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachussetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Puerto Rico',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
    'American Samoa',
    'Guam'
];

export const LetterGradesList = [
    'A+',
    'A',
    'A-',
    'B+',
    'B',
    'B-',
    'C+',
    'C',
    'C-',
    'D+',
    'D',
    'D-',
    'F'
];

export const SimpleLetterGrades = ['A', 'B', 'C', 'D', 'F'];
export const StarsList = [1, 2, 3, 4, 5];
