export const PositionList = [
    { name: 'Quarterbacks', abbr: 'QB' },
    { name: 'Runningbacks', abbr: 'RB' },
    { name: 'Fullbacks', abbr: 'FB' },
    { name: 'Tight Ends', abbr: 'TE' },
    { name: 'Wide Receivers', abbr: 'WR' },
    { name: 'Offensive Tackles', abbr: 'OT' },
    { name: 'Offensive Guards', abbr: 'OG' },
    { name: 'Centers', abbr: 'C' },
    { name: 'Defensive Tackles', abbr: 'DT' },
    { name: 'Defensive Ends', abbr: 'DE' },
    { name: 'Outside Linebackers', abbr: 'OLB' },
    { name: 'Inside Linebackers', abbr: 'ILB' },
    { name: 'Cornerbacks', abbr: 'CB' },
    { name: 'Free Safeties', abbr: 'FS' },
    { name: 'Strong Safeties', abbr: 'SS' },
    { name: 'Punters', abbr: 'P' },
    { name: 'Kickers', abbr: 'K' }
];

export const ArchetypeList = [
    { pos: 'QB', archetype: 'Pocket' },
    { pos: 'QB', archetype: 'Scrambling' },
    { pos: 'QB', archetype: 'Balanced' },
    { pos: 'QB', archetype: 'Field General' },
    { pos: 'RB', archetype: 'Balanced' },
    { pos: 'RB', archetype: 'Power' },
    { pos: 'RB', archetype: 'Receiving' },
    { pos: 'RB', archetype: 'Speed' },
    { pos: 'FB', archetype: 'Balanced' },
    { pos: 'FB', archetype: 'Blocking' },
    { pos: 'FB', archetype: 'Receiving' },
    { pos: 'FB', archetype: 'Rushing' },
    { pos: 'TE', archetype: 'Blocking' },
    { pos: 'TE', archetype: 'Receiving' },
    { pos: 'TE', archetype: 'Vertical Threat' },
    { pos: 'WR', archetype: 'Possession' },
    { pos: 'WR', archetype: 'Red Zone Threat' },
    { pos: 'WR', archetype: 'Route Runner' },
    { pos: 'WR', archetype: 'Speed' },
    { pos: 'OT', archetype: 'Balanced' },
    { pos: 'OT', archetype: 'Pass Blocking' },
    { pos: 'OT', archetype: 'Run Blocking' },
    { pos: 'OG', archetype: 'Balanced' },
    { pos: 'OG', archetype: 'Pass Blocking' },
    { pos: 'OG', archetype: 'Run Blocking' },
    { pos: 'C', archetype: 'Balanced' },
    { pos: 'C', archetype: 'Line Captain' },
    { pos: 'C', archetype: 'Pass Blocking' },
    { pos: 'C', archetype: 'Run Blocking' },
    { pos: 'DT', archetype: 'Balanced' },
    { pos: 'DT', archetype: 'Nose Tackle' },
    { pos: 'DT', archetype: 'Pass Rusher' },
    { pos: 'DE', archetype: 'Balanced' },
    { pos: 'DE', archetype: 'Run Stopper' },
    { pos: 'DE', archetype: 'Speed Rusher' },
    { pos: 'OLB', archetype: 'Coverage' },
    { pos: 'OLB', archetype: 'Pass Rush' },
    { pos: 'OLB', archetype: 'Run Stopper' },
    { pos: 'OLB', archetype: 'Speed' },
    { pos: 'ILB', archetype: 'Coverage' },
    { pos: 'ILB', archetype: 'Field General' },
    { pos: 'ILB', archetype: 'Run Stopper' },
    { pos: 'ILB', archetype: 'Speed' },
    { pos: 'CB', archetype: 'Ball Hawk' },
    { pos: 'CB', archetype: 'Man Coverage' },
    { pos: 'CB', archetype: 'Zone Coverage' },
    { pos: 'FS', archetype: 'Ball Hawk' },
    { pos: 'FS', archetype: 'Man Coverage' },
    { pos: 'FS', archetype: 'Zone Coverage' },
    { pos: 'SS', archetype: 'Ball Hawk' },
    { pos: 'SS', archetype: 'Man Coverage' },
    { pos: 'SS', archetype: 'Zone Coverage' },
    { pos: 'P', archetype: 'Accuracy' },
    { pos: 'P', archetype: 'Balanced' },
    { pos: 'P', archetype: 'Power' },
    { pos: 'K', archetype: 'Accuracy' },
    { pos: 'K', archetype: 'Balanced' },
    { pos: 'K', archetype: 'Power' }
];

export const StatesList = [
    'AL',
    'AK',
    'AZ',
    'AR',
    'CA',
    'CO',
    'CT',
    'DE',
    'FL',
    'GA',
    'HI',
    'ID',
    'IL',
    'IN',
    'IA',
    'KS',
    'KY',
    'LA',
    'ME',
    'MD',
    'MA',
    'MI',
    'MN',
    'MS',
    'MO',
    'MT',
    'NE',
    'NV',
    'NH',
    'NJ',
    'NM',
    'NY',
    'NC',
    'ND',
    'OH',
    'OK',
    'OR',
    'PA',
    'RI',
    'SC',
    'SD',
    'TN',
    'TX',
    'UT',
    'VT',
    'VA',
    'WA',
    'WV',
    'WI',
    'WY'
];

export const RegionList = [
    { state: 'CA', region: '(North)' },
    { state: 'CA', region: '(South)' },
    { state: 'FL', region: '(North)' },
    { state: 'FL', region: '(South)' },
    { state: 'TX', region: '(North)' },
    { state: 'TX', region: '(South)' },
    { state: 'TX', region: '(West)' }
];

export const WorkEthicList = [
    'Persistant',
    'Lazy',
    'Footwork king',
    'Hard-working',
    'Complacent',
    'Skips Leg Day',
    'Working-Class mentality',
    'Film Room Genius',
    'Focuses on Max Weight',
    'Track Athlete',
    'Average',
    'Center of Attention',
    'Gym Rat',
    'Focuses on Max Reps',
    'Loud',
    'Quiet',
    'Streams too much',
    'Trolls on Discord'
];

export const FreeAgencyList = [
    "I'm the starter",
    'Market-driven',
    'Wants extensions',
    'Drafted team discount',
    'Highest bidder',
    'Championship seeking',
    'Loyal',
    'Average',
    'Hometown hero',
    'Money motivated',
    'Hates Tags',
    'Adversarial',
    'Hates Cleveland'
];

export const RecruitingBiasList = [
    'Prefers to play in a different state',
    'Prefers to play for an up-and-coming team',
    'Open-Minded',
    'Prefers to play with former teammates',
    'Fanboy',
    'Multi-Sport',
    'Prefers to play for a team where he can start immediately',
    'Is going to school mainly for academics',
    'Prefers to be close to home',
    'Prefers to play for a national championship contender',
    'Prefers to play for a specific coach',
    'Average',
    'Legacy',
    'Prefers to play for a team with a rich history',
    'Wants that NIL money'
];

export const AcademicBiasList = [
    'Takes AP classes',
    'Sits at the front of the class',
    'Seeks out tutoring',
    'Tutor',
    'Wants to finish degree',
    "Teacher's Pet",
    'Sits at the back of the class',
    'Values academics',
    'Studious',
    'Frequent visits to the principal',
    'Class Clown',
    'More likely to get academic probation',
    'Has other priorities',
    'Distracted',
    'Loves Learning',
    'Studies hard',
    'Less likely to get academic probation',
    'Never Studies',
    'Average',
    'Naturally book smart',
    'Borderline failing',
    'Skips classes often'
];

export const PersonalitiesList = [
    'Reserved',
    'Eccentric',
    'Motivational',
    'Disloyal',
    'Cooperative',
    'Irrational',
    'Focused',
    'Book Worm',
    'Motivation',
    'Abrasive',
    'Absent Minded',
    'Uncooperative',
    'Introvert',
    'Disruptive',
    'Outgoing',
    'Tough',
    'Paranoid',
    'Stoic',
    'Dramatic',
    'Extroverted',
    'Selfish',
    'Impatient',
    'Reliable',
    'Frail',
    'Relaxed',
    'Average',
    'Flamboyant',
    'Perfectionist',
    'Popular',
    'Jokester'
];

export const CloseToHome = 'Close to Home';
export const Academics = 'Academics';
export const Service = 'Service';
export const Religion = 'Religion';
export const LargeCrowds = 'Large Crowds';
export const SmallSchool = 'Small School';
export const Frontrunner = 'Frontrunner';

export const AffinitiesList = [
    CloseToHome,
    Academics,
    Service,
    Religion,
    LargeCrowds,
    SmallSchool,
    Frontrunner
];

export const LetterGradesList = [
    'A+',
    'A',
    'A-',
    'B+',
    'B',
    'B-',
    'C+',
    'C',
    'C-',
    'D+',
    'D',
    'D-',
    'F'
];

export const SimpleLetterGrades = ['A', 'B', 'C', 'D', 'F'];
