export const DefaultSchemes = {
    'Power Run': {
        OffFormation1Name: '',
        OffForm1Weight: 34,
        OffForm1TraditionalRun: 20,
        OffForm1OptionRun: 0,
        OffForm1Pass: 20,
        OffForm1RPO: 0,
        OffFormation2Name: '',
        OffForm2Weight: 33,
        OffForm2TraditionalRun: 20,
        OffForm2OptionRun: 0,
        OffForm2Pass: 10,
        OffForm2RPO: 0,
        OffFormation3Name: '',
        OffForm3Weight: 33,
        OffForm3TraditionalRun: 20,
        OffForm3OptionRun: 0,
        OffForm3Pass: 10,
        OffForm3RPO: 0,
        OffFormation4Name: '',
        OffForm4Weight: 0,
        OffForm4TraditionalRun: 0,
        OffForm4OptionRun: 0,
        OffForm4Pass: 0,
        OffForm4RPO: 0,
        OffFormation5Name: '',
        OffForm5Weight: 0,
        OffForm5TraditionalRun: 0,
        OffForm5OptionRun: 0,
        OffForm5Pass: 0,
        OffForm5RPO: 0,
        RunnerDistributionQB: 0,
        RunnerDistributionRB1: 10,
        RunnerDistributionRB2: 5,
        RunnerDistributionRB3: 1,
        RunnerDistributionFB1: 1,
        RunnerDistributionFB2: 1,
        RunnerDistributionWR: 0,
        RunnerDistributionWRPosition: 'WR1',
        RunOutsideLeft: 15,
        RunOutsideRight: 15,
        RunInsideLeft: 15,
        RunInsideRight: 15,
        RunPowerLeft: 17,
        RunPowerRight: 18,
        RunDrawLeft: 2,
        RunDrawRight: 3,
        ReadOptionLeft: 13,
        ReadOptionRight: 12,
        SpeedOptionLeft: 13,
        SpeedOptionRight: 12,
        InvertedOptionLeft: 12,
        InvertedOptionRight: 13,
        TripleOptionLeft: 12,
        TripleOptionRight: 13,
        PassQuick: 10,
        PassShort: 15,
        PassLong: 20,
        PassScreen: 5,
        PassPAShort: 25,
        PassPALong: 25,
        LeftVsRight: 50,
        ChoiceOutside: 15,
        ChoiceInside: 15,
        ChoicePower: 20,
        PeekOutside: 15,
        PeekInside: 15,
        PeekPower: 20,
        TargetingWR1: 6,
        TargetDepthWR1: 'None',
        TargetingWR2: 5,
        TargetDepthWR2: 'None',
        TargetingWR3: 3,
        TargetDepthWR3: 'None',
        TargetingWR4: 2,
        TargetDepthWR4: 'None',
        TargetingWR5: 2,
        TargetDepthWR5: 'None',
        TargetingTE1: 3,
        TargetDepthTE1: 'None',
        TargetingTE2: 2,
        TargetDepthTE2: 'None',
        TargetingTE3: 1,
        TargetDepthTE3: 'None',
        TargetingRB1: 2,
        TargetDepthRB1: 'None',
        TargetingRB2: 1,
        TargetDepthRB2: 'None',
        TargetingFB1: 1,
        TargetDepthFB1: 'None'
    },
    Vertical: {
        OffFormation1Name: '',
        OffForm1Weight: 34,
        OffForm1TraditionalRun: 15,
        OffForm1OptionRun: 0,
        OffForm1Pass: 20,
        OffForm1RPO: 0,
        OffFormation2Name: '',
        OffForm2Weight: 33,
        OffForm2TraditionalRun: 15,
        OffForm2OptionRun: 0,
        OffForm2Pass: 20,
        OffForm2RPO: 0,
        OffFormation3Name: '',
        OffForm3Weight: 33,
        OffForm3TraditionalRun: 15,
        OffForm3OptionRun: 0,
        OffForm3Pass: 15,
        OffForm3RPO: 0,
        OffFormation4Name: '',
        OffForm4Weight: 0,
        OffForm4TraditionalRun: 0,
        OffForm4OptionRun: 0,
        OffForm4Pass: 0,
        OffForm4RPO: 0,
        OffFormation5Name: '',
        OffForm5Weight: 0,
        OffForm5TraditionalRun: 0,
        OffForm5OptionRun: 0,
        OffForm5Pass: 0,
        OffForm5RPO: 0,
        RunnerDistributionQB: 0,
        RunnerDistributionRB1: 7,
        RunnerDistributionRB2: 1,
        RunnerDistributionRB3: 1,
        RunnerDistributionFB1: 1,
        RunnerDistributionFB2: 1,
        RunnerDistributionWR: 0,
        RunnerDistributionWRPosition: 'WR1',
        RunOutsideLeft: 18,
        RunOutsideRight: 17,
        RunInsideLeft: 17,
        RunInsideRight: 18,
        RunPowerLeft: 12,
        RunPowerRight: 13,
        RunDrawLeft: 3,
        RunDrawRight: 2,
        ReadOptionLeft: 13,
        ReadOptionRight: 12,
        SpeedOptionLeft: 13,
        SpeedOptionRight: 12,
        InvertedOptionLeft: 12,
        InvertedOptionRight: 13,
        TripleOptionLeft: 12,
        TripleOptionRight: 13,
        PassQuick: 15,
        PassShort: 25,
        PassLong: 25,
        PassScreen: 5,
        PassPAShort: 10,
        PassPALong: 20,
        LeftVsRight: 50,
        ChoiceOutside: 15,
        ChoiceInside: 15,
        ChoicePower: 20,
        PeekOutside: 15,
        PeekInside: 15,
        PeekPower: 20,
        TargetingWR1: 6,
        TargetDepthWR1: 'None',
        TargetingWR2: 5,
        TargetDepthWR2: 'None',
        TargetingWR3: 3,
        TargetDepthWR3: 'None',
        TargetingWR4: 2,
        TargetDepthWR4: 'None',
        TargetingWR5: 2,
        TargetDepthWR5: 'None',
        TargetingTE1: 3,
        TargetDepthTE1: 'None',
        TargetingTE2: 2,
        TargetDepthTE2: 'None',
        TargetingTE3: 1,
        TargetDepthTE3: 'None',
        TargetingRB1: 2,
        TargetDepthRB1: 'None',
        TargetingRB2: 1,
        TargetDepthRB2: 'None',
        TargetingFB1: 1,
        TargetDepthFB1: 'None'
    },
    'West Coast': {
        OffFormation1Name: '',
        OffForm1Weight: 34,
        OffForm1TraditionalRun: 15,
        OffForm1OptionRun: 0,
        OffForm1Pass: 20,
        OffForm1RPO: 0,
        OffFormation2Name: '',
        OffForm2Weight: 33,
        OffForm2TraditionalRun: 15,
        OffForm2OptionRun: 0,
        OffForm2Pass: 20,
        OffForm2RPO: 0,
        OffFormation3Name: '',
        OffForm3Weight: 33,
        OffForm3TraditionalRun: 15,
        OffForm3OptionRun: 0,
        OffForm3Pass: 15,
        OffForm3RPO: 0,
        OffFormation4Name: '',
        OffForm4Weight: 0,
        OffForm4TraditionalRun: 0,
        OffForm4OptionRun: 0,
        OffForm4Pass: 0,
        OffForm4RPO: 0,
        OffFormation5Name: '',
        OffForm5Weight: 0,
        OffForm5TraditionalRun: 0,
        OffForm5OptionRun: 0,
        OffForm5Pass: 0,
        OffForm5RPO: 0,
        RunnerDistributionQB: 0,
        RunnerDistributionRB1: 7,
        RunnerDistributionRB2: 1,
        RunnerDistributionRB3: 1,
        RunnerDistributionFB1: 1,
        RunnerDistributionFB2: 1,
        RunnerDistributionWR: 0,
        RunnerDistributionWRPosition: 'WR1',
        RunOutsideLeft: 20,
        RunOutsideRight: 20,
        RunInsideLeft: 20,
        RunInsideRight: 20,
        RunPowerLeft: 5,
        RunPowerRight: 5,
        RunDrawLeft: 5,
        RunDrawRight: 5,
        ReadOptionLeft: 13,
        ReadOptionRight: 12,
        SpeedOptionLeft: 13,
        SpeedOptionRight: 12,
        InvertedOptionLeft: 12,
        InvertedOptionRight: 13,
        TripleOptionLeft: 12,
        TripleOptionRight: 13,
        PassQuick: 30,
        PassShort: 30,
        PassLong: 10,
        PassScreen: 10,
        PassPAShort: 10,
        PassPALong: 10,
        LeftVsRight: 50,
        ChoiceOutside: 15,
        ChoiceInside: 15,
        ChoicePower: 20,
        PeekOutside: 15,
        PeekInside: 15,
        PeekPower: 20,
        TargetingWR1: 6,
        TargetDepthWR1: 'None',
        TargetingWR2: 5,
        TargetDepthWR2: 'None',
        TargetingWR3: 3,
        TargetDepthWR3: 'None',
        TargetingWR4: 2,
        TargetDepthWR4: 'None',
        TargetingWR5: 2,
        TargetDepthWR5: 'None',
        TargetingTE1: 5,
        TargetDepthTE1: 'None',
        TargetingTE2: 2,
        TargetDepthTE2: 'None',
        TargetingTE3: 1,
        TargetDepthTE3: 'None',
        TargetingRB1: 2,
        TargetDepthRB1: 'None',
        TargetingRB2: 1,
        TargetDepthRB2: 'None',
        TargetingFB1: 1,
        TargetDepthFB1: 'None'
    },
    'I Option': {
        OffFormation1Name: '',
        OffForm1Weight: 34,
        OffForm1TraditionalRun: 5,
        OffForm1OptionRun: 20,
        OffForm1Pass: 5,
        OffForm1RPO: 5,
        OffFormation2Name: '',
        OffForm2Weight: 33,
        OffForm2TraditionalRun: 7,
        OffForm2OptionRun: 15,
        OffForm2Pass: 7,
        OffForm2RPO: 2,
        OffFormation3Name: '',
        OffForm3Weight: 33,
        OffForm3TraditionalRun: 8,
        OffForm3OptionRun: 15,
        OffForm3Pass: 8,
        OffForm3RPO: 3,
        OffFormation4Name: '',
        OffForm4Weight: 0,
        OffForm4TraditionalRun: 0,
        OffForm4OptionRun: 0,
        OffForm4Pass: 0,
        OffForm4RPO: 0,
        OffFormation5Name: '',
        OffForm5Weight: 0,
        OffForm5TraditionalRun: 0,
        OffForm5OptionRun: 0,
        OffForm5Pass: 0,
        OffForm5RPO: 0,
        RunnerDistributionQB: 2,
        RunnerDistributionRB1: 5,
        RunnerDistributionRB2: 1,
        RunnerDistributionRB3: 1,
        RunnerDistributionFB1: 1,
        RunnerDistributionFB2: 1,
        RunnerDistributionWR: 0,
        RunnerDistributionWRPosition: 'WR1',
        RunOutsideLeft: 11,
        RunOutsideRight: 11,
        RunInsideLeft: 12,
        RunInsideRight: 11,
        RunPowerLeft: 23,
        RunPowerRight: 22,
        RunDrawLeft: 5,
        RunDrawRight: 5,
        ReadOptionLeft: 8,
        ReadOptionRight: 7,
        SpeedOptionLeft: 8,
        SpeedOptionRight: 7,
        InvertedOptionLeft: 7,
        InvertedOptionRight: 8,
        TripleOptionLeft: 28,
        TripleOptionRight: 27,
        PassQuick: 15,
        PassShort: 20,
        PassLong: 20,
        PassScreen: 5,
        PassPAShort: 20,
        PassPALong: 20,
        LeftVsRight: 50,
        ChoiceOutside: 16,
        ChoiceInside: 17,
        ChoicePower: 17,
        PeekOutside: 16,
        PeekInside: 17,
        PeekPower: 17,
        TargetingWR1: 6,
        TargetDepthWR1: 'None',
        TargetingWR2: 5,
        TargetDepthWR2: 'None',
        TargetingWR3: 3,
        TargetDepthWR3: 'None',
        TargetingWR4: 2,
        TargetDepthWR4: 'None',
        TargetingWR5: 2,
        TargetDepthWR5: 'None',
        TargetingTE1: 5,
        TargetDepthTE1: 'None',
        TargetingTE2: 2,
        TargetDepthTE2: 'None',
        TargetingTE3: 1,
        TargetDepthTE3: 'None',
        TargetingRB1: 2,
        TargetDepthRB1: 'None',
        TargetingRB2: 1,
        TargetDepthRB2: 'None',
        TargetingFB1: 1,
        TargetDepthFB1: 'None'
    },
    'Run and Shoot': {
        OffFormation1Name: '',
        OffForm1Weight: 34,
        OffForm1TraditionalRun: 15,
        OffForm1OptionRun: 0,
        OffForm1Pass: 20,
        OffForm1RPO: 2,
        OffFormation2Name: '',
        OffForm2Weight: 33,
        OffForm2TraditionalRun: 10,
        OffForm2OptionRun: 0,
        OffForm2Pass: 20,
        OffForm2RPO: 2,
        OffFormation3Name: '',
        OffForm3Weight: 33,
        OffForm3TraditionalRun: 10,
        OffForm3OptionRun: 0,
        OffForm3Pass: 20,
        OffForm3RPO: 1,
        OffFormation4Name: '',
        OffForm4Weight: 0,
        OffForm4TraditionalRun: 0,
        OffForm4OptionRun: 0,
        OffForm4Pass: 0,
        OffForm4RPO: 0,
        OffFormation5Name: '',
        OffForm5Weight: 0,
        OffForm5TraditionalRun: 0,
        OffForm5OptionRun: 0,
        OffForm5Pass: 0,
        OffForm5RPO: 0,
        RunnerDistributionQB: 1,
        RunnerDistributionRB1: 5,
        RunnerDistributionRB2: 1,
        RunnerDistributionRB3: 1,
        RunnerDistributionFB1: 1,
        RunnerDistributionFB2: 1,
        RunnerDistributionWR: 0,
        RunnerDistributionWRPosition: 'WR1',
        RunOutsideLeft: 20,
        RunOutsideRight: 20,
        RunInsideLeft: 20,
        RunInsideRight: 20,
        RunPowerLeft: 3,
        RunPowerRight: 2,
        RunDrawLeft: 8,
        RunDrawRight: 7,
        ReadOptionLeft: 13,
        ReadOptionRight: 12,
        SpeedOptionLeft: 13,
        SpeedOptionRight: 12,
        InvertedOptionLeft: 12,
        InvertedOptionRight: 13,
        TripleOptionLeft: 12,
        TripleOptionRight: 13,
        PassQuick: 15,
        PassShort: 25,
        PassLong: 25,
        PassScreen: 15,
        PassPAShort: 10,
        PassPALong: 10,
        LeftVsRight: 50,
        ChoiceOutside: 17,
        ChoiceInside: 17,
        ChoicePower: 17,
        PeekOutside: 17,
        PeekInside: 16,
        PeekPower: 16,
        TargetingWR1: 5,
        TargetDepthWR1: 'None',
        TargetingWR2: 5,
        TargetDepthWR2: 'None',
        TargetingWR3: 3,
        TargetDepthWR3: 'None',
        TargetingWR4: 3,
        TargetDepthWR4: 'None',
        TargetingWR5: 2,
        TargetDepthWR5: 'None',
        TargetingTE1: 3,
        TargetDepthTE1: 'None',
        TargetingTE2: 2,
        TargetDepthTE2: 'None',
        TargetingTE3: 1,
        TargetDepthTE3: 'None',
        TargetingRB1: 2,
        TargetDepthRB1: 'None',
        TargetingRB2: 1,
        TargetDepthRB2: 'None',
        TargetingFB1: 1,
        TargetDepthFB1: 'None'
    },
    'Air Raid': {
        OffFormation1Name: '',
        OffForm1Weight: 34,
        OffForm1TraditionalRun: 10,
        OffForm1OptionRun: 0,
        OffForm1Pass: 25,
        OffForm1RPO: 0,
        OffFormation2Name: '',
        OffForm2Weight: 33,
        OffForm2TraditionalRun: 10,
        OffForm2OptionRun: 0,
        OffForm2Pass: 25,
        OffForm2RPO: 0,
        OffFormation3Name: '',
        OffForm3Weight: 33,
        OffForm3TraditionalRun: 5,
        OffForm3OptionRun: 0,
        OffForm3Pass: 25,
        OffForm3RPO: 0,
        OffFormation4Name: '',
        OffForm4Weight: 0,
        OffForm4TraditionalRun: 0,
        OffForm4OptionRun: 0,
        OffForm4Pass: 0,
        OffForm4RPO: 0,
        OffFormation5Name: '',
        OffForm5Weight: 0,
        OffForm5TraditionalRun: 0,
        OffForm5OptionRun: 0,
        OffForm5Pass: 0,
        OffForm5RPO: 0,
        RunnerDistributionQB: 0,
        RunnerDistributionRB1: 5,
        RunnerDistributionRB2: 1,
        RunnerDistributionRB3: 1,
        RunnerDistributionFB1: 1,
        RunnerDistributionFB2: 1,
        RunnerDistributionWR: 0,
        RunnerDistributionWRPosition: 'WR1',
        RunOutsideLeft: 13,
        RunOutsideRight: 12,
        RunInsideLeft: 25,
        RunInsideRight: 25,
        RunPowerLeft: 0,
        RunPowerRight: 0,
        RunDrawLeft: 12,
        RunDrawRight: 13,
        ReadOptionLeft: 13,
        ReadOptionRight: 12,
        SpeedOptionLeft: 25,
        SpeedOptionRight: 25,
        InvertedOptionLeft: 12,
        InvertedOptionRight: 13,
        TripleOptionLeft: 0,
        TripleOptionRight: 0,
        PassQuick: 35,
        PassShort: 25,
        PassLong: 15,
        PassScreen: 10,
        PassPAShort: 5,
        PassPALong: 10,
        LeftVsRight: 50,
        ChoiceOutside: 10,
        ChoiceInside: 10,
        ChoicePower: 20,
        PeekOutside: 35,
        PeekInside: 15,
        PeekPower: 10,
        TargetingWR1: 5,
        TargetDepthWR1: 'None',
        TargetingWR2: 4,
        TargetDepthWR2: 'None',
        TargetingWR3: 3,
        TargetDepthWR3: 'None',
        TargetingWR4: 3,
        TargetDepthWR4: 'None',
        TargetingWR5: 3,
        TargetDepthWR5: 'None',
        TargetingTE1: 3,
        TargetDepthTE1: 'None',
        TargetingTE2: 2,
        TargetDepthTE2: 'None',
        TargetingTE3: 1,
        TargetDepthTE3: 'None',
        TargetingRB1: 2,
        TargetDepthRB1: 'None',
        TargetingRB2: 1,
        TargetDepthRB2: 'None',
        TargetingFB1: 1,
        TargetDepthFB1: 'None'
    },
    Pistol: {
        OffFormation1Name: '',
        OffForm1Weight: 34,
        OffForm1TraditionalRun: 10,
        OffForm1OptionRun: 10,
        OffForm1Pass: 20,
        OffForm1RPO: 5,
        OffFormation2Name: '',
        OffForm2Weight: 33,
        OffForm2TraditionalRun: 5,
        OffForm2OptionRun: 5,
        OffForm2Pass: 20,
        OffForm2RPO: 5,
        OffFormation3Name: '',
        OffForm3Weight: 33,
        OffForm3TraditionalRun: 5,
        OffForm3OptionRun: 0,
        OffForm3Pass: 10,
        OffForm3RPO: 5,
        OffFormation4Name: '',
        OffForm4Weight: 0,
        OffForm4TraditionalRun: 0,
        OffForm4OptionRun: 0,
        OffForm4Pass: 0,
        OffForm4RPO: 0,
        OffFormation5Name: '',
        OffForm5Weight: 0,
        OffForm5TraditionalRun: 0,
        OffForm5OptionRun: 0,
        OffForm5Pass: 0,
        OffForm5RPO: 0,
        RunnerDistributionQB: 1,
        RunnerDistributionRB1: 5,
        RunnerDistributionRB2: 1,
        RunnerDistributionRB3: 1,
        RunnerDistributionFB1: 1,
        RunnerDistributionFB2: 1,
        RunnerDistributionWR: 0,
        RunnerDistributionWRPosition: 'WR1',
        RunOutsideLeft: 13,
        RunOutsideRight: 12,
        RunInsideLeft: 25,
        RunInsideRight: 25,
        RunPowerLeft: 0,
        RunPowerRight: 0,
        RunDrawLeft: 12,
        RunDrawRight: 13,
        ReadOptionLeft: 18,
        ReadOptionRight: 17,
        SpeedOptionLeft: 15,
        SpeedOptionRight: 15,
        InvertedOptionLeft: 0,
        InvertedOptionRight: 0,
        TripleOptionLeft: 17,
        TripleOptionRight: 18,
        PassQuick: 15,
        PassShort: 25,
        PassLong: 20,
        PassScreen: 10,
        PassPAShort: 20,
        PassPALong: 10,
        LeftVsRight: 50,
        ChoiceOutside: 17,
        ChoiceInside: 17,
        ChoicePower: 17,
        PeekOutside: 17,
        PeekInside: 16,
        PeekPower: 16,
        TargetingWR1: 6,
        TargetDepthWR1: 'None',
        TargetingWR2: 5,
        TargetDepthWR2: 'None',
        TargetingWR3: 3,
        TargetDepthWR3: 'None',
        TargetingWR4: 2,
        TargetDepthWR4: 'None',
        TargetingWR5: 2,
        TargetDepthWR5: 'None',
        TargetingTE1: 3,
        TargetDepthTE1: 'None',
        TargetingTE2: 2,
        TargetDepthTE2: 'None',
        TargetingTE3: 1,
        TargetDepthTE3: 'None',
        TargetingRB1: 2,
        TargetDepthRB1: 'None',
        TargetingRB2: 1,
        TargetDepthRB2: 'None',
        TargetingFB1: 1,
        TargetDepthFB1: 'None'
    },
    'Spread Option': {
        OffFormation1Name: '',
        OffForm1Weight: 34,
        OffForm1TraditionalRun: 5,
        OffForm1OptionRun: 15,
        OffForm1Pass: 10,
        OffForm1RPO: 5,
        OffFormation2Name: '',
        OffForm2Weight: 33,
        OffForm2TraditionalRun: 7,
        OffForm2OptionRun: 10,
        OffForm2Pass: 10,
        OffForm2RPO: 5,
        OffFormation3Name: '',
        OffForm3Weight: 33,
        OffForm3TraditionalRun: 8,
        OffForm3OptionRun: 10,
        OffForm3Pass: 10,
        OffForm3RPO: 5,
        OffFormation4Name: '',
        OffForm4Weight: 0,
        OffForm4TraditionalRun: 0,
        OffForm4OptionRun: 0,
        OffForm4Pass: 0,
        OffForm4RPO: 0,
        OffFormation5Name: '',
        OffForm5Weight: 0,
        OffForm5TraditionalRun: 0,
        OffForm5OptionRun: 0,
        OffForm5Pass: 0,
        OffForm5RPO: 0,
        RunnerDistributionQB: 2,
        RunnerDistributionRB1: 5,
        RunnerDistributionRB2: 1,
        RunnerDistributionRB3: 1,
        RunnerDistributionFB1: 1,
        RunnerDistributionFB2: 1,
        RunnerDistributionWR: 0,
        RunnerDistributionWRPosition: 'WR1',
        RunOutsideLeft: 10,
        RunOutsideRight: 10,
        RunInsideLeft: 10,
        RunInsideRight: 10,
        RunPowerLeft: 28,
        RunPowerRight: 28,
        RunDrawLeft: 2,
        RunDrawRight: 2,
        ReadOptionLeft: 13,
        ReadOptionRight: 12,
        SpeedOptionLeft: 13,
        SpeedOptionRight: 12,
        InvertedOptionLeft: 12,
        InvertedOptionRight: 13,
        TripleOptionLeft: 12,
        TripleOptionRight: 13,
        PassQuick: 15,
        PassShort: 25,
        PassLong: 10,
        PassScreen: 10,
        PassPAShort: 20,
        PassPALong: 20,
        LeftVsRight: 50,
        ChoiceOutside: 15,
        ChoiceInside: 15,
        ChoicePower: 20,
        PeekOutside: 15,
        PeekInside: 15,
        PeekPower: 20,
        TargetingWR1: 6,
        TargetDepthWR1: 'None',
        TargetingWR2: 5,
        TargetDepthWR2: 'None',
        TargetingWR3: 3,
        TargetDepthWR3: 'None',
        TargetingWR4: 2,
        TargetDepthWR4: 'None',
        TargetingWR5: 2,
        TargetDepthWR5: 'None',
        TargetingTE1: 3,
        TargetDepthTE1: 'None',
        TargetingTE2: 2,
        TargetDepthTE2: 'None',
        TargetingTE3: 1,
        TargetDepthTE3: 'None',
        TargetingRB1: 2,
        TargetDepthRB1: 'None',
        TargetingRB2: 1,
        TargetDepthRB2: 'None',
        TargetingFB1: 1,
        TargetDepthFB1: 'None'
    },
    'Wing-T': {
        OffFormation1Name: '',
        OffForm1Weight: 34,
        OffForm1TraditionalRun: 20,
        OffForm1OptionRun: 0,
        OffForm1Pass: 20,
        OffForm1RPO: 0,
        OffFormation2Name: '',
        OffForm2Weight: 33,
        OffForm2TraditionalRun: 20,
        OffForm2OptionRun: 0,
        OffForm2Pass: 10,
        OffForm2RPO: 0,
        OffFormation3Name: '',
        OffForm3Weight: 33,
        OffForm3TraditionalRun: 20,
        OffForm3OptionRun: 0,
        OffForm3Pass: 10,
        OffForm3RPO: 0,
        OffFormation4Name: '',
        OffForm4Weight: 0,
        OffForm4TraditionalRun: 0,
        OffForm4OptionRun: 0,
        OffForm4Pass: 0,
        OffForm4RPO: 0,
        OffFormation5Name: '',
        OffForm5Weight: 0,
        OffForm5TraditionalRun: 0,
        OffForm5OptionRun: 0,
        OffForm5Pass: 0,
        OffForm5RPO: 0,
        RunnerDistributionQB: 2,
        RunnerDistributionRB1: 5,
        RunnerDistributionRB2: 5,
        RunnerDistributionRB3: 1,
        RunnerDistributionFB1: 5,
        RunnerDistributionFB2: 1,
        RunnerDistributionWR: 0,
        RunnerDistributionWRPosition: 'WR1',
        RunOutsideLeft: 16,
        RunOutsideRight: 16,
        RunInsideLeft: 16,
        RunInsideRight: 16,
        RunPowerLeft: 16,
        RunPowerRight: 16,
        RunDrawLeft: 2,
        RunDrawRight: 2,
        ReadOptionLeft: 13,
        ReadOptionRight: 12,
        SpeedOptionLeft: 13,
        SpeedOptionRight: 12,
        InvertedOptionLeft: 12,
        InvertedOptionRight: 13,
        TripleOptionLeft: 12,
        TripleOptionRight: 13,
        PassQuick: 15,
        PassShort: 25,
        PassLong: 20,
        PassScreen: 10,
        PassPAShort: 20,
        PassPALong: 10,
        LeftVsRight: 50,
        ChoiceOutside: 10,
        ChoiceInside: 10,
        ChoicePower: 20,
        PeekOutside: 35,
        PeekInside: 15,
        PeekPower: 10,
        TargetingWR1: 6,
        TargetDepthWR1: 'None',
        TargetingWR2: 5,
        TargetDepthWR2: 'None',
        TargetingWR3: 3,
        TargetDepthWR3: 'None',
        TargetingWR4: 2,
        TargetDepthWR4: 'None',
        TargetingWR5: 2,
        TargetDepthWR5: 'None',
        TargetingTE1: 3,
        TargetDepthTE1: 'None',
        TargetingTE2: 2,
        TargetDepthTE2: 'None',
        TargetingTE3: 1,
        TargetDepthTE3: 'None',
        TargetingRB1: 2,
        TargetDepthRB1: 'None',
        TargetingRB2: 1,
        TargetDepthRB2: 'None',
        TargetingFB1: 1,
        TargetDepthFB1: 'None'
    },
    'Double Wing': {
        OffFormation1Name: '',
        OffForm1Weight: 34,
        OffForm1TraditionalRun: 30,
        OffForm1OptionRun: 0,
        OffForm1Pass: 5,
        OffForm1RPO: 0,
        OffFormation2Name: '',
        OffForm2Weight: 33,
        OffForm2TraditionalRun: 25,
        OffForm2OptionRun: 5,
        OffForm2Pass: 2,
        OffForm2RPO: 0,
        OffFormation3Name: '',
        OffForm3Weight: 33,
        OffForm3TraditionalRun: 25,
        OffForm3OptionRun: 5,
        OffForm3Pass: 3,
        OffForm3RPO: 0,
        OffFormation4Name: '',
        OffForm4Weight: 0,
        OffForm4TraditionalRun: 0,
        OffForm4OptionRun: 0,
        OffForm4Pass: 0,
        OffForm4RPO: 0,
        OffFormation5Name: '',
        OffForm5Weight: 0,
        OffForm5TraditionalRun: 0,
        OffForm5OptionRun: 0,
        OffForm5Pass: 0,
        OffForm5RPO: 0,
        RunnerDistributionQB: 5,
        RunnerDistributionRB1: 5,
        RunnerDistributionRB2: 5,
        RunnerDistributionRB3: 1,
        RunnerDistributionFB1: 5,
        RunnerDistributionFB2: 1,
        RunnerDistributionWR: 0,
        RunnerDistributionWRPosition: 'WR1',
        RunOutsideLeft: 17,
        RunOutsideRight: 16,
        RunInsideLeft: 16,
        RunInsideRight: 17,
        RunPowerLeft: 16,
        RunPowerRight: 17,
        RunDrawLeft: 1,
        RunDrawRight: 0,
        ReadOptionLeft: 13,
        ReadOptionRight: 12,
        SpeedOptionLeft: 13,
        SpeedOptionRight: 12,
        InvertedOptionLeft: 12,
        InvertedOptionRight: 13,
        TripleOptionLeft: 12,
        TripleOptionRight: 13,
        PassQuick: 15,
        PassShort: 25,
        PassLong: 20,
        PassScreen: 10,
        PassPAShort: 20,
        PassPALong: 10,
        LeftVsRight: 50,
        ChoiceOutside: 10,
        ChoiceInside: 10,
        ChoicePower: 20,
        PeekOutside: 35,
        PeekInside: 15,
        PeekPower: 10,
        TargetingWR1: 6,
        TargetDepthWR1: 'None',
        TargetingWR2: 5,
        TargetDepthWR2: 'None',
        TargetingWR3: 3,
        TargetDepthWR3: 'None',
        TargetingWR4: 2,
        TargetDepthWR4: 'None',
        TargetingWR5: 2,
        TargetDepthWR5: 'None',
        TargetingTE1: 3,
        TargetDepthTE1: 'None',
        TargetingTE2: 2,
        TargetDepthTE2: 'None',
        TargetingTE3: 1,
        TargetDepthTE3: 'None',
        TargetingRB1: 2,
        TargetDepthRB1: 'None',
        TargetingRB2: 1,
        TargetDepthRB2: 'None',
        TargetingFB1: 1,
        TargetDepthFB1: 'None'
    },
    Flexbone: {
        OffFormation1Name: '',
        OffForm1Weight: 34,
        OffForm1TraditionalRun: 10,
        OffForm1OptionRun: 20,
        OffForm1Pass: 5,
        OffForm1RPO: 0,
        OffFormation2Name: '',
        OffForm2Weight: 33,
        OffForm2TraditionalRun: 10,
        OffForm2OptionRun: 20,
        OffForm2Pass: 5,
        OffForm2RPO: 0,
        OffFormation3Name: '',
        OffForm3Weight: 33,
        OffForm3TraditionalRun: 15,
        OffForm3OptionRun: 10,
        OffForm3Pass: 0,
        OffForm3RPO: 5,
        OffFormation4Name: '',
        OffForm4Weight: 0,
        OffForm4TraditionalRun: 0,
        OffForm4OptionRun: 0,
        OffForm4Pass: 0,
        OffForm4RPO: 0,
        OffFormation5Name: '',
        OffForm5Weight: 0,
        OffForm5TraditionalRun: 0,
        OffForm5OptionRun: 0,
        OffForm5Pass: 0,
        OffForm5RPO: 0,
        RunnerDistributionQB: 1,
        RunnerDistributionRB1: 2,
        RunnerDistributionRB2: 2,
        RunnerDistributionRB3: 1,
        RunnerDistributionFB1: 5,
        RunnerDistributionFB2: 1,
        RunnerDistributionWR: 0,
        RunnerDistributionWRPosition: 'WR1',
        RunOutsideLeft: 16,
        RunOutsideRight: 16,
        RunInsideLeft: 16,
        RunInsideRight: 16,
        RunPowerLeft: 16,
        RunPowerRight: 16,
        RunDrawLeft: 2,
        RunDrawRight: 2,
        ReadOptionLeft: 2,
        ReadOptionRight: 3,
        SpeedOptionLeft: 23,
        SpeedOptionRight: 22,
        InvertedOptionLeft: 3,
        InvertedOptionRight: 2,
        TripleOptionLeft: 22,
        TripleOptionRight: 23,
        PassQuick: 15,
        PassShort: 25,
        PassLong: 20,
        PassScreen: 10,
        PassPAShort: 20,
        PassPALong: 10,
        LeftVsRight: 50,
        ChoiceOutside: 17,
        ChoiceInside: 17,
        ChoicePower: 17,
        PeekOutside: 16,
        PeekInside: 16,
        PeekPower: 17,
        TargetingWR1: 6,
        TargetDepthWR1: 'None',
        TargetingWR2: 5,
        TargetDepthWR2: 'None',
        TargetingWR3: 3,
        TargetDepthWR3: 'None',
        TargetingWR4: 2,
        TargetDepthWR4: 'None',
        TargetingWR5: 2,
        TargetDepthWR5: 'None',
        TargetingTE1: 2,
        TargetDepthTE1: 'None',
        TargetingTE2: 2,
        TargetDepthTE2: 'None',
        TargetingTE3: 1,
        TargetDepthTE3: 'None',
        TargetingRB1: 4,
        TargetDepthRB1: 'None',
        TargetingRB2: 3,
        TargetDepthRB2: 'None',
        TargetingFB1: 1,
        TargetDepthFB1: 'None'
    },
    Wishbone: {
        OffFormation1Name: '',
        OffForm1Weight: 34,
        OffForm1TraditionalRun: 25,
        OffForm1OptionRun: 10,
        OffForm1Pass: 5,
        OffForm1RPO: 0,
        OffFormation2Name: '',
        OffForm2Weight: 33,
        OffForm2TraditionalRun: 15,
        OffForm2OptionRun: 10,
        OffForm2Pass: 7,
        OffForm2RPO: 0,
        OffFormation3Name: '',
        OffForm3Weight: 33,
        OffForm3TraditionalRun: 10,
        OffForm3OptionRun: 10,
        OffForm3Pass: 8,
        OffForm3RPO: 0,
        OffFormation4Name: '',
        OffForm4Weight: 0,
        OffForm4TraditionalRun: 0,
        OffForm4OptionRun: 0,
        OffForm4Pass: 0,
        OffForm4RPO: 0,
        OffFormation5Name: '',
        OffForm5Weight: 0,
        OffForm5TraditionalRun: 0,
        OffForm5OptionRun: 0,
        OffForm5Pass: 0,
        OffForm5RPO: 0,
        RunnerDistributionQB: 1,
        RunnerDistributionRB1: 5,
        RunnerDistributionRB2: 5,
        RunnerDistributionRB3: 1,
        RunnerDistributionFB1: 1,
        RunnerDistributionFB2: 1,
        RunnerDistributionWR: 0,
        RunnerDistributionWRPosition: 'WR1',
        RunOutsideLeft: 16,
        RunOutsideRight: 16,
        RunInsideLeft: 16,
        RunInsideRight: 16,
        RunPowerLeft: 16,
        RunPowerRight: 16,
        RunDrawLeft: 2,
        RunDrawRight: 2,
        ReadOptionLeft: 10,
        ReadOptionRight: 10,
        SpeedOptionLeft: 10,
        SpeedOptionRight: 10,
        InvertedOptionLeft: 10,
        InvertedOptionRight: 10,
        TripleOptionLeft: 20,
        TripleOptionRight: 20,
        PassQuick: 10,
        PassShort: 10,
        PassLong: 10,
        PassScreen: 10,
        PassPAShort: 30,
        PassPALong: 30,
        LeftVsRight: 50,
        ChoiceOutside: 10,
        ChoiceInside: 10,
        ChoicePower: 20,
        PeekOutside: 35,
        PeekInside: 15,
        PeekPower: 10,
        TargetingWR1: 6,
        TargetDepthWR1: 'None',
        TargetingWR2: 5,
        TargetDepthWR2: 'None',
        TargetingWR3: 3,
        TargetDepthWR3: 'None',
        TargetingWR4: 2,
        TargetDepthWR4: 'None',
        TargetingWR5: 2,
        TargetDepthWR5: 'None',
        TargetingTE1: 3,
        TargetDepthTE1: 'None',
        TargetingTE2: 2,
        TargetDepthTE2: 'None',
        TargetingTE3: 1,
        TargetDepthTE3: 'None',
        TargetingRB1: 2,
        TargetDepthRB1: 'None',
        TargetingRB2: 1,
        TargetDepthRB2: 'None',
        TargetingFB1: 1,
        TargetDepthFB1: 'None'
    }
};

export const DefenseDefaultSchemes = {
    'Old School': {
        'Power Run': {
            DefFormation1: '4-4 Base',
            DefFormation1RunToPass: 60,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '4-3 Light',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '4-4 Base',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '4-4 Over',
            DefFormation4RunToPass: 60,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '4-4 Under',
            DefFormation5RunToPass: 60,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        Vertical: {
            DefFormation1: '4-4 Base',
            DefFormation1RunToPass: 60,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '4-3 Light',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '4-4 Base',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '4-3 Light',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '4-4 Under',
            DefFormation5RunToPass: 40,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        'West Coast': {
            DefFormation1: '4-4 Base',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '4-3 Light',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '4-2-5 Nickel',
            DefFormation3RunToPass: 30,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '4-3 Light',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '4-4 Under',
            DefFormation5RunToPass: 50,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        'I Option': {
            DefFormation1: '4-4 Base',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '4-3 Light',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '4-4 Base',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '4-3 Light',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '4-4 Under',
            DefFormation5RunToPass: 50,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        'Run and Shoot': {
            DefFormation1: '4-4 Base',
            DefFormation1RunToPass: 30,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '4-3 Light',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '4-2-5 Nickel',
            DefFormation3RunToPass: 40,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '4-3 Light',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '4-2-5 Nickel',
            DefFormation5RunToPass: 20,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        'Air Raid': {
            DefFormation1: '4-2-5 Nickel',
            DefFormation1RunToPass: 40,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '4-3 Light',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '4-2-5 Nickel',
            DefFormation3RunToPass: 20,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '4-2-5 Nickel',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '4-2-5 Nickel',
            DefFormation5RunToPass: 20,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        Pistol: {
            DefFormation1: '4-3 Light',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '4-4 Base',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '4-4 Over',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '4-4 Under',
            DefFormation4RunToPass: 50,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '4-2-5 Nickel',
            DefFormation5RunToPass: 30,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        'Spread Option': {
            DefFormation1: '4-2-5 Nickel',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '4-3 Light',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '4-4 Under',
            DefFormation3RunToPass: 50,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '4-2-5 Nickel',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '4-2-5 Nickel',
            DefFormation5RunToPass: 30,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        'Wing-T': {
            DefFormation1: '4-4 Over',
            DefFormation1RunToPass: 70,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '4-4 Base',
            DefFormation2RunToPass: 70,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '4-4 Under',
            DefFormation3RunToPass: 70,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '4-4 Base',
            DefFormation4RunToPass: 70,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '4-4 Base',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        'Double Wing': {
            DefFormation1: '4-4 Over',
            DefFormation1RunToPass: 80,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '4-4 Over',
            DefFormation2RunToPass: 80,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '4-4 Base',
            DefFormation3RunToPass: 80,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '4-2-5 Nickel',
            DefFormation4RunToPass: 50,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '4-4 Base',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        Wishbone: {
            DefFormation1: '4-4 Over',
            DefFormation1RunToPass: 70,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '4-4 Under',
            DefFormation2RunToPass: 70,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '4-4 Base',
            DefFormation3RunToPass: 70,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '4-4 Over',
            DefFormation4RunToPass: 70,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '4-4 Base',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        Flexbone: {
            DefFormation1: '4-4 Over',
            DefFormation1RunToPass: 80,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '4-4 Under',
            DefFormation2RunToPass: 80,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '4-4 Base',
            DefFormation3RunToPass: 80,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '4-4 Over',
            DefFormation4RunToPass: 80,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '4-4 Base',
            DefFormation5RunToPass: 80,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        }
    },
    '2-Gap': {
        'Power Run': {
            DefFormation1: '3-4 Okie',
            DefFormation1RunToPass: 60,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '3-3-5 Nickel',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '3-4 Bronco',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '3-4 Eagle',
            DefFormation4RunToPass: 60,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '3-4 Bronco',
            DefFormation5RunToPass: 60,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        Vertical: {
            DefFormation1: '3-4 Okie',
            DefFormation1RunToPass: 60,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '3-3-5 Nickel',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '3-4 Bronco',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '3-3-5 Nickel',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '3-2-6 Dime',
            DefFormation5RunToPass: 40,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        'West Coast': {
            DefFormation1: '3-4 Okie',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '3-3-5 Nickel',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '3-2-6 Dime',
            DefFormation3RunToPass: 30,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '3-3-5 Nickel',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '3-4 Bronco',
            DefFormation5RunToPass: 50,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        'I Option': {
            DefFormation1: '3-4 Okie',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '3-3-5 Nickel',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '3-4 Bronco',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '3-3-5 Nickel',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '3-4 Bronco',
            DefFormation5RunToPass: 50,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        'Run and Shoot': {
            DefFormation1: '3-2-6 Dime',
            DefFormation1RunToPass: 30,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '3-3-5 Nickel',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '3-2-6 Dime',
            DefFormation3RunToPass: 40,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '3-3-5 Nickel',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '3-2-6 Dime',
            DefFormation5RunToPass: 20,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        'Air Raid': {
            DefFormation1: '3-2-6 Dime',
            DefFormation1RunToPass: 40,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '3-3-5 Nickel',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '3-2-6 Dime',
            DefFormation3RunToPass: 20,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '3-4 Bronco',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '3-3-5 Nickel',
            DefFormation5RunToPass: 20,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        Pistol: {
            DefFormation1: '3-3-5 Nickel',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '3-4 Okie',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '3-4 Eagle',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '3-4 Eagle',
            DefFormation4RunToPass: 50,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '3-2-6 Dime',
            DefFormation5RunToPass: 30,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        'Spread Option': {
            DefFormation1: '3-2-6 Dime',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '3-3-5 Nickel',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '3-4 Bronco',
            DefFormation3RunToPass: 50,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '3-4 Bronco',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '3-3-5 Nickel',
            DefFormation5RunToPass: 30,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        'Wing-T': {
            DefFormation1: '3-4 Eagle',
            DefFormation1RunToPass: 70,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '3-4 Eagle',
            DefFormation2RunToPass: 70,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '3-4 Eagle',
            DefFormation3RunToPass: 70,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '3-4 Eagle',
            DefFormation4RunToPass: 70,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '3-4 Eagle',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        'Double Wing': {
            DefFormation1: '3-4 Eagle',
            DefFormation1RunToPass: 80,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '3-4 Eagle',
            DefFormation2RunToPass: 80,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '3-4 Eagle',
            DefFormation3RunToPass: 80,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '3-3-5 Nickel',
            DefFormation4RunToPass: 50,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '3-4 Eagle',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        Wishbone: {
            DefFormation1: '3-4 Eagle',
            DefFormation1RunToPass: 70,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '3-4 Eagle',
            DefFormation2RunToPass: 70,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '3-4 Eagle',
            DefFormation3RunToPass: 70,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '3-4 Eagle',
            DefFormation4RunToPass: 70,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '3-4 Okie',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        },
        Flexbone: {
            DefFormation1: '3-4 Eagle',
            DefFormation1RunToPass: 80,
            DefFormation1BlitzWeight: 50,
            DefFormation1BlitzAggression: 'Aggressive',
            DefFormation2: '3-4 Eagle',
            DefFormation2RunToPass: 80,
            DefFormation2BlitzWeight: 50,
            DefFormation2BlitzAggression: 'Aggressive',
            DefFormation3: '3-4 Eagle',
            DefFormation3RunToPass: 80,
            DefFormation3BlitzWeight: 50,
            DefFormation3BlitzAggression: 'Aggressive',
            DefFormation4: '3-4 Eagle',
            DefFormation4RunToPass: 80,
            DefFormation4BlitzWeight: 50,
            DefFormation4BlitzAggression: 'Aggressive',
            DefFormation5: '3-4 Eagle',
            DefFormation5RunToPass: 80,
            DefFormation5BlitzWeight: 50,
            DefFormation5BlitzAggression: 'Aggressive'
        }
    },
    '4-Man Front Spread Stopper': {
        'Power Run': {
            DefFormation1: '4-2-5 Base',
            DefFormation1RunToPass: 60,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '4-2-5 Base',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '4-3 Heavy',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '4-4 Jumbo',
            DefFormation4RunToPass: 60,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '4-2-5 Base',
            DefFormation5RunToPass: 60,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        Vertical: {
            DefFormation1: '4-2-5 Base',
            DefFormation1RunToPass: 60,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '4-2-5 Base',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '4-3 Heavy',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '4-2-5 Base',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '4-1-6 Dime',
            DefFormation5RunToPass: 40,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        'West Coast': {
            DefFormation1: '4-2-5 Base',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '4-2-5 Base',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '4-1-6 Dime',
            DefFormation3RunToPass: 30,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '4-2-5 Base',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '4-2-5 Base',
            DefFormation5RunToPass: 50,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        'I Option': {
            DefFormation1: '4-2-5 Base',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '4-2-5 Base',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '4-3 Heavy',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '4-2-5 Base',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '4-2-5 Base',
            DefFormation5RunToPass: 50,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        'Run and Shoot': {
            DefFormation1: '4-1-6 Dime',
            DefFormation1RunToPass: 30,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '4-2-5 Base',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '4-1-6 Dime',
            DefFormation3RunToPass: 40,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '4-2-5 Base',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '4-1-6 Dime',
            DefFormation5RunToPass: 20,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        'Air Raid': {
            DefFormation1: '4-1-6 Dime',
            DefFormation1RunToPass: 40,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '4-2-5 Base',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '4-1-6 Dime',
            DefFormation3RunToPass: 20,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '4-1-6 Big Dime',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '4-1-6 Big Dime',
            DefFormation5RunToPass: 20,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        Pistol: {
            DefFormation1: '4-2-5 Base',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '4-2-5 Base',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '4-4 Jumbo',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '4-1-6 Big Dime',
            DefFormation4RunToPass: 50,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '4-1-6 Dime',
            DefFormation5RunToPass: 30,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        'Spread Option': {
            DefFormation1: '4-1-6 Dime',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '4-2-5 Base',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '4-2-5 Base',
            DefFormation3RunToPass: 50,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '4-1-6 Big Dime',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '4-1-6 Big Dime',
            DefFormation5RunToPass: 30,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        'Wing-T': {
            DefFormation1: '4-4 Jumbo',
            DefFormation1RunToPass: 70,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '4-4 Jumbo',
            DefFormation2RunToPass: 70,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '4-4 Jumbo',
            DefFormation3RunToPass: 70,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '4-4 Jumbo',
            DefFormation4RunToPass: 70,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '4-4 Jumbo',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        'Double Wing': {
            DefFormation1: '4-4 Jumbo',
            DefFormation1RunToPass: 80,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '4-4 Jumbo',
            DefFormation2RunToPass: 80,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '4-4 Jumbo',
            DefFormation3RunToPass: 80,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '4-1-6 Big Dime',
            DefFormation4RunToPass: 50,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '4-4 Jumbo',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        Wishbone: {
            DefFormation1: '4-4 Jumbo',
            DefFormation1RunToPass: 70,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '4-4 Jumbo',
            DefFormation2RunToPass: 70,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '4-4 Jumbo',
            DefFormation3RunToPass: 70,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '4-4 Jumbo',
            DefFormation4RunToPass: 70,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '4-2-5 Base',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        Flexbone: {
            DefFormation1: '4-4 Jumbo',
            DefFormation1RunToPass: 80,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '4-4 Jumbo',
            DefFormation2RunToPass: 80,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '4-4 Jumbo',
            DefFormation3RunToPass: 80,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '4-4 Jumbo',
            DefFormation4RunToPass: 80,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '4-4 Jumbo',
            DefFormation5RunToPass: 80,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        }
    },
    '3-Man Front Spread Stopper': {
        'Power Run': {
            DefFormation1: '3-3-5 Base',
            DefFormation1RunToPass: 60,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '3-3-5 Over',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '3-2-6 Big Penny',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '3-4-4 Heavy',
            DefFormation4RunToPass: 60,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '3-3-5 Base',
            DefFormation5RunToPass: 60,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        Vertical: {
            DefFormation1: '3-3-5 Base',
            DefFormation1RunToPass: 60,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '3-3-5 Over',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '3-2-6 Big Penny',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '3-3-5 Over',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '3-3-5 Base',
            DefFormation5RunToPass: 40,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        'West Coast': {
            DefFormation1: '3-3-5 Base',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '3-3-5 Over',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '3-2-6 Penny',
            DefFormation3RunToPass: 30,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '3-3-5 Over',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '3-3-5 Base',
            DefFormation5RunToPass: 50,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        'I Option': {
            DefFormation1: '3-3-5 Base',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '3-3-5 Over',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '3-2-6 Big Penny',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '3-3-5 Over',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '3-3-5 Base',
            DefFormation5RunToPass: 50,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        'Run and Shoot': {
            DefFormation1: '3-2-6 Penny',
            DefFormation1RunToPass: 30,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '3-3-5 Over',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '3-2-6 Penny',
            DefFormation3RunToPass: 40,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '3-3-5 Over',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '3-2-6 Penny',
            DefFormation5RunToPass: 20,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        'Air Raid': {
            DefFormation1: '3-2-6 Penny',
            DefFormation1RunToPass: 40,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '3-3-5 Over',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '3-2-6 Penny',
            DefFormation3RunToPass: 20,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '3-2-6 Big Penny',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '3-2-6 Big Penny',
            DefFormation5RunToPass: 20,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        Pistol: {
            DefFormation1: '3-3-5 Base',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '3-3-5 Base',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '3-4-4 Heavy',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '3-2-6 Big Penny',
            DefFormation4RunToPass: 50,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '3-2-6 Penny',
            DefFormation5RunToPass: 30,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        'Spread Option': {
            DefFormation1: '4-2-5 Nickel',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '3-3-5 Over',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '3-3-5 Base',
            DefFormation3RunToPass: 50,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '4-2-5 Nickel',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '4-2-5 Nickel',
            DefFormation5RunToPass: 30,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        'Wing-T': {
            DefFormation1: '3-4-4 Heavy',
            DefFormation1RunToPass: 70,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '3-4-4 Heavy',
            DefFormation2RunToPass: 70,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '3-4-4 Heavy',
            DefFormation3RunToPass: 70,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '3-4-4 Heavy',
            DefFormation4RunToPass: 70,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '3-4-4 Heavy',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        'Double Wing': {
            DefFormation1: '3-4-4 Heavy',
            DefFormation1RunToPass: 80,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '3-4-4 Heavy',
            DefFormation2RunToPass: 80,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '3-4-4 Heavy',
            DefFormation3RunToPass: 80,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '3-3-5 Over',
            DefFormation4RunToPass: 50,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '3-4-4 Heavy',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        Wishbone: {
            DefFormation1: '3-4-4 Heavy',
            DefFormation1RunToPass: 70,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '3-4-4 Heavy',
            DefFormation2RunToPass: 70,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '3-4-4 Heavy',
            DefFormation3RunToPass: 70,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '3-4-4 Heavy',
            DefFormation4RunToPass: 70,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '3-3-5 Base',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        },
        Flexbone: {
            DefFormation1: '3-4-4 Heavy',
            DefFormation1RunToPass: 80,
            DefFormation1BlitzWeight: 20,
            DefFormation1BlitzAggression: 'Cautious',
            DefFormation2: '3-4-4 Heavy',
            DefFormation2RunToPass: 80,
            DefFormation2BlitzWeight: 20,
            DefFormation2BlitzAggression: 'Cautious',
            DefFormation3: '3-4-4 Heavy',
            DefFormation3RunToPass: 80,
            DefFormation3BlitzWeight: 20,
            DefFormation3BlitzAggression: 'Cautious',
            DefFormation4: '3-4-4 Heavy',
            DefFormation4RunToPass: 80,
            DefFormation4BlitzWeight: 20,
            DefFormation4BlitzAggression: 'Cautious',
            DefFormation5: '3-4-4 Heavy',
            DefFormation5RunToPass: 80,
            DefFormation5BlitzWeight: 20,
            DefFormation5BlitzAggression: 'Cautious'
        }
    },
    Speed: {
        'Power Run': {
            DefFormation1: '4-3 Base',
            DefFormation1RunToPass: 60,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-2-5 Nickel',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-3 Over',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-4 Heavy',
            DefFormation4RunToPass: 60,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-3 Base',
            DefFormation5RunToPass: 60,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        Vertical: {
            DefFormation1: '4-3 Base',
            DefFormation1RunToPass: 60,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-2-5 Nickel',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-3 Over',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-2-5 Nickel',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-1-6 Dime',
            DefFormation5RunToPass: 40,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        'West Coast': {
            DefFormation1: '4-3 Base',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-2-5 Nickel',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-1-6 Dime',
            DefFormation3RunToPass: 30,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-2-5 Nickel',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-3 Base',
            DefFormation5RunToPass: 50,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        'I Option': {
            DefFormation1: '4-3 Base',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-2-5 Nickel',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-3 Over',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-2-5 Nickel',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-3 Base',
            DefFormation5RunToPass: 50,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        'Run and Shoot': {
            DefFormation1: '4-1-6 Dime',
            DefFormation1RunToPass: 30,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-2-5 Nickel',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-1-6 Dime',
            DefFormation3RunToPass: 40,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-2-5 Nickel',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-1-6 Dime',
            DefFormation5RunToPass: 20,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        'Air Raid': {
            DefFormation1: '4-1-6 Dime',
            DefFormation1RunToPass: 40,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-2-5 Nickel',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-1-6 Dime',
            DefFormation3RunToPass: 20,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-2-5 Nickel',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-2-5 Nickel',
            DefFormation5RunToPass: 20,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        Pistol: {
            DefFormation1: '4-2-5 Nickel',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-3 Base',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-4 Heavy',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-3 Base',
            DefFormation4RunToPass: 50,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-1-6 Dime',
            DefFormation5RunToPass: 30,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        'Spread Option': {
            DefFormation1: '4-1-6 Dime',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-2-5 Nickel',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-3 Base',
            DefFormation3RunToPass: 50,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-2-5 Nickel',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-2-5 Nickel',
            DefFormation5RunToPass: 30,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        'Wing-T': {
            DefFormation1: '4-4 Heavy',
            DefFormation1RunToPass: 70,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-4 Heavy',
            DefFormation2RunToPass: 70,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-4 Heavy',
            DefFormation3RunToPass: 70,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-4 Heavy',
            DefFormation4RunToPass: 70,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-4 Heavy',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        'Double Wing': {
            DefFormation1: '4-4 Heavy',
            DefFormation1RunToPass: 80,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-4 Heavy',
            DefFormation2RunToPass: 80,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-4 Heavy',
            DefFormation3RunToPass: 80,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-2-5 Nickel',
            DefFormation4RunToPass: 50,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-4 Heavy',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        Wishbone: {
            DefFormation1: '4-4 Heavy',
            DefFormation1RunToPass: 70,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-4 Heavy',
            DefFormation2RunToPass: 70,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-4 Heavy',
            DefFormation3RunToPass: 70,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-4 Heavy',
            DefFormation4RunToPass: 70,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-3 Base',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        Flexbone: {
            DefFormation1: '4-4 Heavy',
            DefFormation1RunToPass: 80,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-4 Heavy',
            DefFormation2RunToPass: 80,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-4 Heavy',
            DefFormation3RunToPass: 80,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-4 Heavy',
            DefFormation4RunToPass: 80,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-4 Heavy',
            DefFormation5RunToPass: 80,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        }
    },
    Multiple: {
        'Power Run': {
            DefFormation1: '4-3 Base',
            DefFormation1RunToPass: 60,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-2-5 Over',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-3 Over',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-3 Over',
            DefFormation4RunToPass: 60,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '3-4 Bronco',
            DefFormation5RunToPass: 60,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        Vertical: {
            DefFormation1: '4-3 Base',
            DefFormation1RunToPass: 60,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-2-5 Over',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-3 Base',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-2-5 Over',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-2-5 Nickel',
            DefFormation5RunToPass: 40,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        'West Coast': {
            DefFormation1: '3-4 Bronco',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-2-5 Over',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-2-5 Nickel',
            DefFormation3RunToPass: 30,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-2-5 Over',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '3-4 Bronco',
            DefFormation5RunToPass: 50,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        'I Option': {
            DefFormation1: '4-3 Base',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-2-5 Over',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-3 Over',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-2-5 Over',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '3-4 Bronco',
            DefFormation5RunToPass: 50,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        'Run and Shoot': {
            DefFormation1: '4-2-5 Nickel',
            DefFormation1RunToPass: 30,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-2-5 Nickel',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-2-5 Nickel',
            DefFormation3RunToPass: 40,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-2-5 Nickel',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-2-5 Nickel',
            DefFormation5RunToPass: 20,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        'Air Raid': {
            DefFormation1: '4-2-5 Nickel',
            DefFormation1RunToPass: 40,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-2-5 Nickel',
            DefFormation2RunToPass: 40,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-2-5 Nickel',
            DefFormation3RunToPass: 20,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '3-4 Bronco',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-2-5 Nickel',
            DefFormation5RunToPass: 20,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        Pistol: {
            DefFormation1: '4-2-5 Nickel',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '3-4 Bronco',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-3 Over',
            DefFormation3RunToPass: 60,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '3-4 Bronco',
            DefFormation4RunToPass: 50,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-2-5 Nickel',
            DefFormation5RunToPass: 30,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        'Spread Option': {
            DefFormation1: '4-2-5 Nickel',
            DefFormation1RunToPass: 50,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-2-5 Nickel',
            DefFormation2RunToPass: 50,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-3 Base',
            DefFormation3RunToPass: 50,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '3-4 Bronco',
            DefFormation4RunToPass: 40,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-2-5 Nickel',
            DefFormation5RunToPass: 30,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        'Wing-T': {
            DefFormation1: '4-3 Over',
            DefFormation1RunToPass: 70,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-3 Over',
            DefFormation2RunToPass: 70,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-3 Over',
            DefFormation3RunToPass: 70,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-3 Over',
            DefFormation4RunToPass: 70,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-3 Over',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        'Double Wing': {
            DefFormation1: '4-3 Over',
            DefFormation1RunToPass: 80,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-3 Over',
            DefFormation2RunToPass: 80,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-3 Over',
            DefFormation3RunToPass: 80,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-2-5 Nickel',
            DefFormation4RunToPass: 50,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-3 Over',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        Wishbone: {
            DefFormation1: '4-3 Over',
            DefFormation1RunToPass: 70,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-3 Over',
            DefFormation2RunToPass: 70,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-3 Over',
            DefFormation3RunToPass: 70,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-3 Over',
            DefFormation4RunToPass: 70,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-3 Base',
            DefFormation5RunToPass: 70,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        },
        Flexbone: {
            DefFormation1: '4-3 Over',
            DefFormation1RunToPass: 80,
            DefFormation1BlitzWeight: 35,
            DefFormation1BlitzAggression: 'Moderate',
            DefFormation2: '4-3 Over',
            DefFormation2RunToPass: 80,
            DefFormation2BlitzWeight: 35,
            DefFormation2BlitzAggression: 'Moderate',
            DefFormation3: '4-3 Over',
            DefFormation3RunToPass: 80,
            DefFormation3BlitzWeight: 35,
            DefFormation3BlitzAggression: 'Moderate',
            DefFormation4: '4-3 Over',
            DefFormation4RunToPass: 80,
            DefFormation4BlitzWeight: 35,
            DefFormation4BlitzAggression: 'Moderate',
            DefFormation5: '4-3 Over',
            DefFormation5RunToPass: 80,
            DefFormation5BlitzWeight: 35,
            DefFormation5BlitzAggression: 'Moderate'
        }
    }
};
