import logos from './logos';

export const getLogo = (team) => {
    switch (team) {
        case 'USAF':
            return logos.Air_Force;
        case 'AAMU':
            return logos.Alabama_AM;
        case 'ACU':
            return logos.Abilene_Christian;
        case 'AKRN':
            return logos.Akron_Zips;
        case 'ALB':
            return logos.Albany;
        case 'ALCN':
            return logos.Alcorn_State;
        case 'ALST':
            return logos.Alabama_State;
        case 'AMCC':
            return logos.Texas_AM_Corpus;
        case 'AMER':
            return logos.American;
        case 'APSU':
            return logos.Austin_Peay;
        case 'BAMA':
            return logos.Alabama;
        case 'APST':
            return logos.App_State;
        case 'ZONA':
            return logos.Arizona;
        case 'AZST':
            return logos.Arizona_State;
        case 'ARK':
            return logos.Arkansas;
        case 'ARST':
            return logos.Arkansas_State;
        case 'ARMY':
            return logos.Army;
        case 'AUB':
            return logos.Auburn;
        case 'BALL':
            return logos.Ball_State;
        case 'BAYL':
            return logos.Baylor;
        case 'BOIS':
            return logos.Boise_State;
        case 'BC':
            return logos.Boston_College;
        case 'BCU':
            return logos.Bethune_Cookman;
        case 'BEL':
            return logos.Belmont;
        case 'BELL':
            return logos.Bellarmine;
        case 'BGSU':
            return logos.Bowling_Green;
        case 'BING':
            return logos.Binghamton;
        case 'BRAD':
            return logos.Bradley;
        case 'BRWN':
            return logos.Brown;
        case 'BRY':
            return logos.Bryant;
        case 'BU':
            return logos.Boston;
        case 'BUFF':
            return logos.Buffalo;
        case 'BUCK':
            return logos.Bucknell;
        case 'BUT':
            return logos.Butler;
        case 'BYU':
            return logos.BYU;
        case 'CAL':
            return logos.California;
        case 'CAMP':
            return logos.Campbell;
        case 'CAN':
            return logos.Canisius;
        case 'CARK':
            return logos.Central_Arkansas;
        case 'CBU':
            return logos.California_Baptist;
        case 'CCSU':
            return logos.Central_Connecticut;
        case 'CMU':
            return logos.Central_Michigan;
        case 'CHAM':
            return logos.Chaminade;
        case 'CHSO':
            return logos.Charleston_Southern;
        case 'CHST':
            return logos.Chicago_State;
        case 'CHAR':
            return logos.Charlotte;
        case 'CINC':
            return logos.Cincinnati;
        case 'CIT':
            return logos.Citadel;
        case 'CLEM':
            return logos.Clemson;
        case 'CLEV':
            return logos.Cleveland_State;
        case 'CCU':
            return logos.Coastal_Carolina;
        case 'COFC':
            return logos.Charleston;
        case 'COLG':
            return logos.Colgate;
        case 'COLO':
            return logos.Colorado;
        case 'COLU':
            return logos.Columbia;
        case 'COPP':
            return logos.Coppin_State;
        case 'COR':
            return logos.Cornell;
        case 'CP':
            return logos.Cal_Poly;
        case 'CSUB':
            return logos.Cal_State_Bakersfield;
        case 'CSUF':
            return logos.Cal_State_Fullerton;
        case 'CSUN':
            return logos.Cal_State_Northridge;
        case 'CSU':
            return logos.Colorado_State;
        case 'CREI':
            return logos.Creighton;
        case 'DART':
            return logos.Dartmouth;
        case 'DAV':
            return logos.Davidson;
        case 'DAY':
            return logos.Dayton;
        case 'DEL':
            return logos.Delaware;
        case 'DETM':
            return logos.Detroit_Mercy;
        case 'DREX':
            return logos.Drexel;
        case 'DRKE':
            return logos.Drake;
        case 'DSU':
            return logos.Delaware_State;
        case 'DU':
            return logos.Denver;
        case 'DUKE':
            return logos.Duke;
        case 'DUQ':
            return logos.Duquesne;
        case 'ECU':
            return logos.East_Carolina;
        case 'EIU':
            return logos.Eastern_Illinois;
        case 'EKU':
            return logos.Eastern_Kentucky;
        case 'ELON':
            return logos.Elon;
        case 'EMU':
            return logos.Eastern_Michigan;
        case 'ETSU':
            return logos.ETSU;
        case 'EWU':
            return logos.Eastern_Washington;
        case 'FAIR':
            return logos.Fairfield;
        case 'FAMU':
            return logos.FAMU;
        case 'FDU':
            return logos.Fairleigh_Dickinson;
        case 'FIU':
            return logos.FIU;
        case 'FLA':
            return logos.Florida;
        case 'FAU':
            return logos.Florida_Atlantic;
        case 'FSU':
            return logos.Florida_State;
        case 'FOR':
            return logos.Fordham;
        case 'FRES':
            return logos.Fresno_State;
        case 'FUR':
            return logos.Furman;
        case 'GCU':
            return logos.Grand_Canyon;
        case 'GMU':
            return logos.GeorgeMason;
        case 'GRAM':
            return logos.Grambling_State;
        case 'GW':
            return logos.GeorgeWashington;
        case 'UGA':
            return logos.Georgia;
        case 'GASO':
            return logos.Georgia_Southern;
        case 'GAST':
            return logos.Georgia_State;
        case 'GT':
            return logos.Georgia_Tech;
        case 'GONZ':
            return logos.Gonzaga;
        case 'HAMP':
            return logos.Hampton;
        case 'HART':
            return logos.Hartford;
        case 'HARV':
            return logos.Harvard;
        case 'HAWI':
            return logos.Hawaii;
        case 'HC':
            return logos.Holy_Cross;
        case 'UHOU':
            return logos.Houston;
        case 'HCU':
            return logos.Houston_Baptist;
        case 'HOF':
            return logos.Hofstra;
        case 'HOW':
            return logos.Howard;
        case 'HP':
            return logos.High_Point;
        case 'IDHO':
            return logos.Idaho;
        case 'IDST':
            return logos.Idaho_State;
        case 'ILLI':
            return logos.Illinois;
        case 'ILST':
            return logos.Illinois_State;
        case 'IND':
            return logos.Indiana;
        case 'INST':
            return logos.Indiana_State;
        case 'IONA':
            return logos.Iona;
        case 'IOWA':
            return logos.Iowa;
        case 'IAST':
            return logos.Iowa_State;
        case 'IUPU':
            return logos.IUPUI;
        case 'JMU':
            return logos.JMU;
        case 'JXST':
            return logos.Jackson_State;
        case 'JST':
            return logos.JacksonvilleState;
        case 'KANS':
            return logos.Kansas;
        case 'KCU':
            return logos.Kansas_City_U;
        case 'KSST':
            return logos.Kansas_State;
        case 'KENT':
            return logos.Kent_State;
        case 'KNSW':
            return logos.KennesawState;
        case 'UKEN':
            return logos.Kentucky;
        case 'LAS':
            return logos.LaSalle;
        case 'LAF':
            return logos.Lafayette;
        case 'LAM':
            return logos.Lamar;
        case 'LBSU':
            return logos.Long_Beach;
        case 'LEH':
            return logos.LeHigh;
        case 'LEM':
            return logos.Lemoyne;
        case 'LIN':
            return logos.Lindenwood;
        case 'LIP':
            return logos.Lipscomb;
        case 'LIU':
            return logos.Long_Island;
        case 'L-MD':
            return logos.Loyola_Maryland;
        case 'LONG':
            return logos.Longwood;
        case 'LR':
            return logos.Little_Rock;
        case 'LU':
            return logos.Liberty;
        case 'ULL':
            return logos.Louisiana;
        case 'ULM':
            return logos.Louisiana_Monroe;
        case 'LT':
            return logos.Louisiana_Tech;
        case 'LOU':
            return logos.Louisville;
        case 'LUC':
            return logos.LoyolaC;
        case 'LMU':
            return logos.LoyolaM;
        case 'LSU':
            return logos.LSU;
        case 'MAN':
            return logos.Manhattan;
        case 'MCN':
            return logos.McNeese_State;
        case 'MARQ':
            return logos.Marquette;
        case 'ME':
            return logos.Maine;
        case 'MRSH':
            return logos.Marshall;
        case 'UMD':
            return logos.Maryland;
        case 'MEMP':
            return logos.Memphis;
        case 'MER':
            return logos.Mercer;
        case 'MIAF':
            return logos.Miami;
        case 'MIAO':
            return logos.Miami_OH;
        case 'MICH':
            return logos.Michigan;
        case 'MIST':
            return logos.Michigan_State;
        case 'MILW':
            return logos.Milwaukee;
        case 'MTSU':
            return logos.Middle_Tennessee;
        case 'MINN':
            return logos.Minnesota;
        case 'MSST':
            return logos.Mississippi_State;
        case 'MIZZ':
            return logos.Missouri;
        case 'MONM':
            return logos.Monmouth;
        case 'MONT':
            return logos.Montana;
        case 'MORE':
            return logos.Morehead;
        case 'MORG':
            return logos.Morgan_State;
        case 'MOST':
            return logos.Missouri_State;
        case 'MRMK':
            return logos.Merrimack;
        case 'MRST':
            return logos.Marist;
        case 'MSM':
            return logos.Mount_St_Marys;
        case 'MSVU':
            return logos.Mississippi_Valley;
        case 'MTST':
            return logos.Montana_State;
        case 'MUR':
            return logos.Murray_State;
        case 'NAU':
            return logos.Northern_Arizona;
        case 'NAVY':
            return logos.Navy;
        case 'NCAT':
            return logos.North_Carolina_AT;
        case 'NCCU':
            return logos.North_Carolina_Central;
        case 'NCST':
            return logos.NC_State;
        case 'NDSU':
            return logos.North_Dakota_State;
        case 'NE':
            return logos.Northeastern;
        case 'NEB':
            return logos.Nebraska;
        case 'NEV':
            return logos.Nevada;
        case 'NIA':
            return logos.Niagara;
        case 'NICH':
            return logos.Nicholls_State;
        case 'NJIT':
            return logos.NJIT;
        case 'NKU':
            return logos.Northern_Kentucky;
        case 'UNM':
            return logos.New_Mexico;
        case 'NMSU':
            return logos.New_Mexico_State;
        case 'UNC':
            return logos.North_Carolina;
        case 'UNT':
            return logos.North_Texas;
        case 'NIU':
            return logos.NIU;
        case 'NORF':
            return logos.Norfolk_State;
        case 'NW':
            return logos.Northwestern;
        case 'NWST':
            return logos.Northwestern_State;
        case 'ND':
            return logos.Notre_Dame;
        case 'OAK':
            return logos.Oakland;
        case 'OHIO':
            return logos.Ohio;
        case 'OHST':
            return logos.Ohio_State;
        case 'OKLA':
            return logos.Oklahoma;
        case 'OKST':
            return logos.Oklahoma_State;
        case 'ODU':
            return logos.Old_Dominion;
        case 'MISS':
            return logos.Ole_Miss;
        case 'OREG':
            return logos.Oregon;
        case 'ORST':
            return logos.Oregon_State;
        case 'ORU':
            return logos.Oral_Roberts;
        case 'PAC':
            return logos.Pacific;
        case 'PENN':
            return logos.Pennsylvania;
        case 'PFW':
            return logos.Purdue_Fort_Wayne;
        case 'PRE':
            return logos.Presbyterian_College;
        case 'PNST':
            return logos.Penn_State;
        case 'PEPP':
            return logos.Pepperdine;
        case 'PITT':
            return logos.Pitt;
        case 'PRIN':
            return logos.Princeton;
        case 'PROV':
            return logos.Providence;
        case 'PRST':
            return logos.Portland_State;
        case 'PURD':
            return logos.Purdue;
        case 'PV':
            return logos.Prairie_View;
        case 'QUIN':
            return logos.Quinnipiac;
        case 'QUOC':
            return logos.Queens;
        case 'RAD':
            return logos.Radford;
        case 'RGV':
            return logos.Rio_Grande_Valley;
        case 'RID':
            return logos.Rider;
        case 'RMU':
            return logos.Robert_Morris;
        case 'URI':
            return logos.RhodeIsland;
        case 'RICE':
            return logos.Rice;
        case 'RICH':
            return logos.Richmond;
        case 'RUTG':
            return logos.Rutgers;
        case 'JOES':
            return logos.SaintJosephs;
        case 'SLU':
            return logos.SaintLouis;
        case 'SAM':
            return logos.Samford;
        case 'SCST':
            return logos.South_Carolina_State;
        case 'SDAK':
            return logos.South_Dakota;
        case 'SDSU':
            return logos.San_Diego_State;
        case 'SELA':
            return logos.Southeastern_Louisiana;
        case 'SEMO':
            return logos.Southeast_Missouri;
        case 'SF':
            return logos.SFDons;
        case 'SFA':
            return logos.SFA;
        case 'SFNY':
            return logos.St_Francis;
        case 'SFPA':
            return logos.Saint_Francis;
        case 'SHSU':
            return logos.SamHoustonState;
        case 'SHU':
            return logos.Sacred_Heart;
        case 'SIE':
            return logos.Siena;
        case 'SIU':
            return logos.Southern_Illinois;
        case 'SIUE':
            return logos.SIU_E;
        case 'SJSU':
            return logos.San_Jose;
        case 'SCU':
            return logos.SantaClara;
        case 'HALL':
            return logos.SetonHall;
        case 'SMU':
            return logos.SMU;
        case 'SOU':
            return logos.Southern;
        case 'SPU':
            return logos.Saint_Peters;
        case 'USA':
            return logos.South_Alabama;
        case 'SOCA':
            return logos.South_Carolina;
        case 'SSU':
            return logos.Sacramento_State;
        case 'USF':
            return logos.South_Florida;
        case 'USM':
            return logos.Southern_Miss;
        case 'SJU':
            return logos.StJohns;
        case 'STAN':
            return logos.Stanford;
        case 'STBK':
            return logos.Stony_Brook;
        case 'STET':
            return logos.Stetson;
        case 'STMN':
            return logos.St_Thomas;
        case 'STO':
            return logos.Stonehill;
        case 'SUU':
            return logos.Southern_Utah;
        case 'CUSE':
            return logos.Syracuse;
        case 'TAMC':
            return logos.Texas_AM_Commerce;
        case 'TAR':
            return logos.Tarleton;
        case 'TCU':
            return logos.TCU;
        case 'TEMP':
            return logos.Temple;
        case 'TENN':
            return logos.Tennessee;
        case 'TNST':
            return logos.Tennessee_State;
        case 'TNTC':
            return logos.Tennessee_Tech;
        case 'TEX':
            return logos.Texas;
        case 'TAMU':
            return logos.TAMU;
        case 'TXST':
            return logos.Texas_State;
        case 'TTU':
            return logos.Texas_Tech;
        case 'TXSO':
            return logos.Texas_Southern;
        case 'TLDO':
            return logos.Toledo;
        case 'TOW':
            return logos.Towson;
        case 'TROY':
            return logos.Troy;
        case 'TLNE':
            return logos.Tulane;
        case 'TULS':
            return logos.Tulsa;
        case 'UAB':
            return logos.UAB;
        case 'UAPB':
            return logos.Arkansas_Pine_Bluff;
        case 'UCD':
            return logos.UC_Davis;
        case 'UCR':
            return logos.UC_Riverside;
        case 'UCSB':
            return logos.UC_Santa_Barbara;
        case 'UIC':
            return logos.UIC;
        case 'UIW':
            return logos.Incarnate_Word;
        case 'UCF':
            return logos.UCF;
        case 'UCLA':
            return logos.UCLA;
        case 'CONN':
            return logos.Connecticut;
        case 'MASS':
            return logos.UMASS;
        case 'UMES':
            return logos.Maryland_East;
        case 'UML':
            return logos.UMASS_Lowell;
        case 'UNA':
            return logos.North_Alabama;
        case 'UNCA':
            return logos.UNC_Asheville;
        case 'UNCO':
            return logos.Northern_Colorado;
        case 'UNCG':
            return logos.UNCG;
        case 'UNCW':
            return logos.UNC_Wilmington;
        case 'UND':
            return logos.North_Dakota;
        case 'UNF':
            return logos.North_Florida;
        case 'UNH':
            return logos.New_Hampshire;
        case 'UNI':
            return logos.Northern_Iowa;
        case 'UNO':
            return logos.New_Orleans;
        case 'UOG':
            return logos.Guam;
        case 'UNLV':
            return logos.UNLV;
        case 'UPST':
            return logos.USC_Upstate;
        case 'USC':
            return logos.USC;
        case 'USI':
            return logos.Southern_Indiana;
        case 'UTA':
            return logos.UT_Arlington;
        case 'UTC':
            return logos.Chattanooga;
        case 'UTM':
            return logos.UT_Martin;
        case 'UTU':
            return logos.Utah_Tech;
        case 'UTEP':
            return logos.UTEP;
        case 'UTSA':
            return logos.UTSA;
        case 'UTAH':
            return logos.Utah;
        case 'UTST':
            return logos.Utah_State;
        case 'UV':
            return logos.Vermont;
        case 'UVU':
            return logos.Utah_Valley;
        case 'UWGB':
            return logos.Green_Bay;
        case 'VAL':
            return logos.Valparaiso;
        case 'VAND':
            return logos.Vanderbilt;
        case 'VILL':
            return logos.Villanova;
        case 'UVA':
            return logos.Virginia;
        case 'VMI':
            return logos.VMI;
        case 'VT':
            return logos.Virginia_Tech;
        case 'WAG':
            return logos.Wagner;
        case 'WAKE':
            return logos.Wake_Forest;
        case 'WASH':
            return logos.Washington;
        case 'WAST':
            return logos.Washington_State;
        case 'WCU':
            return logos.Western_Carolina;
        case 'WEB':
            return logos.Weber_State;
        case 'WEBB':
            return logos.Gardner_Webb;
        case 'WIN':
            return logos.Winthrop;
        case 'WIU':
            return logos.Western_Illinois;
        case 'W&M':
            return logos.William_and_Mary;
        case 'WOF':
            return logos.Wofford;
        case 'WRST':
            return logos.Wright_State;
        case 'WVU':
            return logos.West_Virginia;
        case 'WKU':
            return logos.Western_Kentucky;
        case 'WMU':
            return logos.Western_Michigan;
        case 'WISC':
            return logos.Wisconsin;
        case 'WYOM':
            return logos.Wyoming;
        case 'XAV':
            return logos.Xavier;
        case 'YALE':
            return logos.Yale;
        case 'YSU':
            return logos.Youngstown_State;
        case 'UMBC':
            return logos.UMBC;
        case 'WICH':
            return logos.Wichita_State;
        case 'USD':
            return logos.U_San_Diego;
        case 'UCSD':
            return logos.UC_San_Diego;
        case 'SMC':
            return logos.St_Marys;
        case 'VCU':
            return logos.VCU;
        case 'GEOT':
            return logos.Georgetown;
        case 'SBON':
            return logos.St_Bonaventure;
        case 'UCI':
            return logos.UC_Irvine;
        case 'SDST':
            return logos.South_Dakota_State;
        case 'DPU':
            return logos.DePaul;
        case 'FGCU':
            return logos.FGCU;
        case 'JU':
            return logos.Jacksonville;
        case 'UNOM':
            return logos.Nebraska_Omaha;
        case 'PORT':
            return logos.Portland;
        case 'SEAU':
            return logos.Seattle;
        case 'EVAN':
            return logos.Evansville;
        case 'Arizona Cardinals':
            return logos.ARI_Cardinals;
        case 'Atlanta Hawks':
            return logos.ATL_Hawks;
        case 'Atlanta Falcons':
            return logos.ATL_Falcons;
        case 'Baltimore Ravens':
            return logos.BAL_Ravens;
        case 'Boston Celtics':
            return logos.BOS_Celtics;
        case 'Brooklyn Nets':
            return logos.BRK_Nets;
        case 'Buffalo Bills':
            return logos.BUF_Bills;
        case 'Carolina Panthers':
            return logos.CAR_Panthers;
        case 'Cincinnati Bengals':
            return logos.CIN_Bengals;
        case 'Cleveland Browns':
            return logos.CLE_Browns;
        case 'Cleveland Cavaliers':
            return logos.CLE_Cavaliers;
        case 'Charlotte Hornets':
            return logos.CHA_Hornets;
        case 'Chicago Bulls':
            return logos.CHI_Bulls;
        case 'Chicago Bears':
            return logos.CHI_Bears;
        case 'Dallas Mavericks':
            return logos.DAL_Mavericks;
        case 'Dallas Cowboys':
            return logos.DAL_Cowboys;
        case 'Denver Nuggets':
            return logos.DEN_Nuggets;
        case 'Denver Broncos':
            return logos.DEN_Broncos;
        case 'Detroit Pistons':
            return logos.DET_Pistons;
        case 'Detroit Lions':
            return logos.DET_Lions;
        case 'Green Bay Packers':
            return logos.GB_Packers;
        case 'Golden State Warriors':
            return logos.GS_Warriors;
        case 'Houston Rockets':
            return logos.HOU_Rockets;
        case 'Houston Texans':
            return logos.HOU_Texans;
        case 'Indiana Pacers':
            return logos.IND_Pacers;
        case 'Indianapolis Colts':
            return logos.IND_Colts;
        case 'Jacksonville Jaguars':
            return logos.JAX_Jaguars;
        case 'Kansas City Chiefs':
            return logos.KC_Chiefs;
        case 'Las Vegas Raiders':
            return logos.LV_Raiders;
        case 'Los Angeles Lakers':
            return logos.LA_Lakers;
        case 'Los Angeles Clippers':
            return logos.LA_Clippers;
        case 'Los Angeles Rams':
            return logos.LA_Rams;
        case 'Los Angeles Chargers':
            return logos.LA_Chargers;
        case 'Memphis Grizzlies':
            return logos.MEM_Grizzlies;
        case 'Miami Heat':
            return logos.MIA_Heat;
        case 'Miami Dolphins':
            return logos.MIA_Dolphins;
        case 'Milwaukee Bucks':
            return logos.MIL_Bucks;
        case 'Minnesota Timberwolves':
            return logos.MIN_Timberwolves;
        case 'Minnesota Vikings':
            return logos.MN_Vikings;
        case 'New England Patriots':
            return logos.NE_Patriots;
        case 'New Orleans Pelicans':
            return logos.NO_Pelicans;
        case 'New Orleans Saints':
            return logos.NO_Saints;
        case 'New York Knicks':
            return logos.NY_Knicks;
        case 'New York Giants':
            return logos.NY_Giants;
        case 'New York Jets':
            return logos.NY_Jets;
        case 'Orlando Magic':
            return logos.ORL_Magic;
        case 'Oklahoma City Thunder':
            return logos.OKC_Thunder;
        case 'Philadelphia 76ers':
            return logos.PHI_76ers;
        case 'Philadelphia Eagles':
            return logos.PHI_Eagles;
        case 'Phoenix Suns':
            return logos.PHO_Suns;
        case 'Pittsburgh Steelers':
            return logos.PIT_Steelers;
        case 'Portland Trailblazers':
            return logos.POR_Trailblazers;
        case 'Sacramento Kings':
            return logos.SAC_Kings;
        case 'San Antonio Spurs':
            return logos.SA_Spurs;
        case 'San Diego Clippers':
            return logos.SD_Clippers;
        case 'San Francisco 49ers':
            return logos.SF_49ers;
        case 'Seattle Supersonics':
            return logos.SEA_Supersonics;
        case 'Seattle Seahawks':
            return logos.SEA_Seahawks;
        case 'Tampa Bay Buccaneers':
            return logos.TB_Buccaneers;
        case 'Tennessee Titans':
            return logos.TEN_Titans;
        case 'Toronto Raptors':
            return logos.TOR_Raptors;
        case 'Utah Jazz':
            return logos.UTA_Jazz;
        case 'Vancouver Sea Lions':
            return logos.VAN_Sealions;
        case 'Washington Wizards':
            return logos.WAS_Wizards;
        case 'Washington Commanders':
            return logos.WAS_Commies;

        default:
            return logos.Unknown;
    }
};
