export const baseUrl = 'https://calebrose.io/simfba-logo-cdn';

const logos = {
    Abilene_Christian: `${baseUrl}/logos/Abiene_Christian_Wildcats_logo.png`,
    Air_Force: baseUrl + '/logos/Air_Force_Falcons_logo.png',
    Akron_Zips: baseUrl + '/logos/Akron_Zips_logo.png',
    Alabama: baseUrl + '/logos/Alabama_Crimson_Tide_logo.png',
    Alabama_AM: baseUrl + '/logos/Alabama_A&M_Bulldogs_logo.png',
    Alabama_State: baseUrl + '/logos/Alabama_State_logo.png',
    Albany: `${baseUrl}/logos/Albany_Great_Danes_logo.png`,
    Alcorn_State: baseUrl + '/logos/Alcorn_State_athletics_logo.png',
    American: `${baseUrl}/logos/American_Eagles_logo.png`,
    App_State: baseUrl + '/logos/appstate_logo.png',
    Arizona_State: baseUrl + '/logos/Arizona_State_Sun_Devils_2.png',
    Arizona: baseUrl + '/logos/Arizona_Wildcats_logo.png',
    Arkansas: baseUrl + '/logos/arkansas_logo.png',
    Arkansas_State: baseUrl + '/logos/Arkansas_State_Red_Wolves_logo.png',
    Arkansas_Pine_Bluff:
        baseUrl + '/logos/Arkansas_Pine_Bluff_Golden_Lions_logo.png',
    Army: baseUrl + '/logos/Army_West_Point_logo.png',
    Auburn: baseUrl + '/logos/Auburn_Tigers_logo.png',
    Austin_Peay: `${baseUrl}/logos/Austin_Peay_Governors_logo.png`,
    Ball_State: baseUrl + '/logos/Ball_State_Cardinals_logo.png',
    Baylor: baseUrl + '/logos/Baylor_Green.png',
    Bellarmine: `${baseUrl}/logos/Bellarmine_Knights_logo.png`,
    Belmont: `${baseUrl}/logos/Belmont_Bruins_logo.png`,
    Bethune_Cookman: baseUrl + '/logos/Bethune_Cookman_Wildcats_logo.png',
    Binghamton: `${baseUrl}/logos/Binghamton_Bearcats_logo.png`,
    Boise_State: baseUrl + '/logos/Boise_State_Broncos_logo.png',
    Boston_College: baseUrl + '/logos/Boston_College_Eagles_logo.png',
    Boston: `${baseUrl}/logos/Boston_University_Terriers_logo.png`,
    Bowling_Green: baseUrl + '/logos/Bowling_Green_Falcons_logo.png',
    Bradley: `${baseUrl}/logos/Bradley_Braves_logo.png`,
    Brown: baseUrl + '/logos/Brown_Bears_Athletics_logo.png',
    Bryant: `${baseUrl}/logos/Bryant_Bulldogs_logo.png`,
    Bucknell: baseUrl + '/logos/Bucknell_Bison_logo.png',
    Buffalo: baseUrl + '/logos/Buffalo_Bulls_logo.png',
    Butler: baseUrl + '/logos/Butler_Bulldogs_logo.png',
    BYU: baseUrl + '/logos/BYU_Cougars_logo.png',
    California: baseUrl + '/logos/California_Golden_Bears_logo_2.png',
    Cal_Poly: baseUrl + '/logos/Cal_Poly_Mustangs_logo.png',
    Cal_State_Bakersfield: `${baseUrl}/logos/Cal_State_Bakersfield_Roadrunners_logo.png`,
    Cal_State_Fullerton: `${baseUrl}/logos/Cal_State_Fullerton_Titans_logo.png`,
    Cal_State_Northridge: `${baseUrl}/logos/CSUN_Matadors_logo.png`,
    California_Baptist: `${baseUrl}/logos/Californi_Baptist_logo.png`,
    Campbell: `${baseUrl}/logos/Campbell_Fighting_Camels_logo.png`,
    Canisius: `${baseUrl}/logos/Canisius_Golden_Griffins.png`,
    Central_Arkansas: `${baseUrl}/logos/Central_Arkansas_Athletics_logo.png`,
    Central_Connecticut: `${baseUrl}/logos/Central_Connecticut_Blue_Devils_logo.png`,
    Central_Michigan: baseUrl + '/logos/Central_Michigan_Chippewas_logo.png',
    Charleston: `${baseUrl}/logos/Charleston_Cougars_logo.png`,
    Charleston_Southern: `${baseUrl}/logos/Charleston_Southern_Buccaneers_logo.png`,
    Charlotte: baseUrl + '/logos/Charlotte_49ers_logo.png',
    Chattanooga: baseUrl + '/logos/Chattanooga_Mocs_logo.png',
    Chicago_State: `${baseUrl}/logos/Chicago_State_Cougars_logo.png`,
    Cincinnati: baseUrl + '/logos/Cincinnati_Bearcats_logo.png',
    Citadel: baseUrl + '/logos/Citadel_Bulldogs_logo.png',
    Clemson: baseUrl + '/logos/Clemson_Tigers_logo.png',
    Cleveland_State: `${baseUrl}/logos/Cleveland_State_Vikings_logo.png`,
    Coastal_Carolina: baseUrl + '/logos/Coastal_Carolina_Chanticleers_logo.png',
    Colgate: baseUrl + '/logos/Colgate_Raiders_logo.png',
    Colorado: baseUrl + '/logos/Colorado_Buffaloes_logo.png',
    Colorado_State: baseUrl + '/logos/Colorado_State_Rams_logo.png',
    Columbia: baseUrl + '/logos/Columbia_Lions_logo.png',
    Connecticut: baseUrl + '/logos/Connecticut_Huskies_logo.png',
    Coppin_State: `${baseUrl}/logos/Coppin_State_Eagles_logo.png`,
    Cornell: baseUrl + '/logos/Cornell_Big_Red_logo.png',
    Creighton: baseUrl + '/logos/Creighton_Bluejays_logo.png',
    Dartmouth: baseUrl + '/logos/Dartmouth_College_Big_Green_logo.png',
    Davidson: baseUrl + '/logos/Davidson_Wildcats_logo.png',
    Dayton: baseUrl + '/logos/dayton_flyers_logo.png',
    Delaware: `${baseUrl}/logos/Delaware_Blue_Hens_logo.png`,
    Delaware_State: `${baseUrl}/logos/Delaware_State_Hornets_logo.png`,
    Denver: `${baseUrl}/logos/Denver_Pioneers_Athletics_logo.png`,
    DePaul: baseUrl + '/logos/DePaul_Blue_Demons_logo.png',
    Detroit_Mercy: `${baseUrl}/logos/Detroit_Titans_logo.png`,
    Drake: `${baseUrl}/logos/Drake_Bulldogs_logo.png`,
    Drexel: `${baseUrl}/logos/Drexel_Dragons_logo.png`,
    Duke: baseUrl + '/logos/Duke_Athletics_logo.png',
    Duquesne: baseUrl + '/logos/Duquesne_Dukes_logo.png',
    East_Carolina: baseUrl + '/logos/East_Carolina_Pirates_logo.png',
    ETSU: baseUrl + '/logos/East_Tennessee_State_Buccaneers_logo.png',
    Eastern_Illinois: `${baseUrl}/logos/Eastern_Illinois_Panthers_logo.png`,
    Eastern_Kentucky: `${baseUrl}/logos/Eastern_Kentucky_Colonels_logo.png`,
    Eastern_Michigan: baseUrl + '/logos/Eastern_Michigan_Eagles_logo.png',
    Eastern_Washington: baseUrl + '/logos/Eastern_Washington_Eagles_logo.png',
    Elon: `${baseUrl}/logos/Elon_Phoenix_logo.png`,
    Evansville: baseUrl + '/logos/Evansville_Purple_Aces_logo.png',
    Fairfield: `${baseUrl}/logos/Fairfield_Stags_logo.png`,
    Fairleigh_Dickinson: `${baseUrl}/FDU_Knights_Logo.png`,
    FAMU: baseUrl + '/logos/FAMU_Rattler.png',
    FGCU: baseUrl + '/logos/Florida_Gulf_Coast_Eagles_logo.png',
    FIU: baseUrl + '/logos/FIU_Panthers_logo.png',
    Florida_Atlantic: baseUrl + '/logos/Florida_Atlantic_Owls_logo.png',
    Florida: baseUrl + '/logos/Florida_Gators_logo.png',
    Florida_State: baseUrl + '/logos/Florida_State_Seminoles_logo.png',
    Fordham: baseUrl + '/logos/Fordham_Rams_logo.png',
    Fresno_State: baseUrl + '/logos/Fresno_State_Bulldogs_logo.png',
    Furman: baseUrl + '/logos/Furman_Paladins_logo.png',
    Gardner_Webb: `${baseUrl}/logos/Gardner_Webb_Bulldogs_Logo.png`,
    GeorgeMason: baseUrl + '/logos/George_Mason_Patriots_logo.png',
    Georgetown: baseUrl + '/logos/Georgetown_Hoyas_logo.png',
    GeorgeWashington: baseUrl + '/logos/George_Washington_Colonials_logo.png',
    Georgia: baseUrl + '/logos/Georgia_Athletics_logo.png',
    Georgia_Southern: baseUrl + '/logos/Georgia_Southern_Eagles_logo.png',
    Georgia_State: baseUrl + '/logos/Georgia_State_Athletics_logo.png',
    Georgia_Tech: baseUrl + '/logos/Georgia_Tech_Yellow_Jackets_logo.png',
    Gonzaga: baseUrl + '/logos/Gonzaga_Bulldogs_logo.png',
    Grambling_State: baseUrl + '/logos/Grambling_State_Tigers_logo.png',
    Grand_Canyon: `${baseUrl}/logos/Grand_Canyon_Antelopes_logo.png`,
    Green_Bay: `${baseUrl}/logos/Green_Bay_Phoenix_logo.png`,
    Guam: `${baseUrl}/logos/Guam_Tritons_logo.png`,
    Hampton: `${baseUrl}/logos/Hampton_Pirates_logo.png`,
    Hartford: `${baseUrl}/logos/Hartford_Hawks_logo.png`,
    Harvard: baseUrl + '/logos/Harvard_Crimson_logo.png',
    Hawaii: baseUrl + '/logos/Hawaii_Warriors_logo.png',
    High_Point: `${baseUrl}/logos/High_Point_Panthers_logo.png`,
    Hofstra: `${baseUrl}/logos/Hofstra_Pridge_logo.png`,
    Holy_Cross: baseUrl + '/logos/Holy_Cross_Crusaders_logo.png',
    Houston: baseUrl + '/logos/Houston_Cougars_primary_logo.png',
    Houston_Baptist: `${baseUrl}/logos/Houston_Baptist_Huskies_logo.png`,
    Howard: `${baseUrl}/logos/Howard_Bison_logo.png`,
    Idaho: baseUrl + '/logos/Idaho_Vandals_logo.png',
    Idaho_State: baseUrl + '/logos/Idaho_State_Bengals_logo.png',
    Illinois: baseUrl + '/logos/Illinois_Fighting_Illini_logo.png',
    Illinois_State: baseUrl + '/logos/Illinois_State_Athletics_logo.png',
    Incarnate_Word: `${baseUrl}/logos/Incarnate_Word_Cardinals_logo.png`,
    Indiana: baseUrl + '/logos/Indiana_Hoosiers_logo.png',
    Indiana_State: baseUrl + '/logos/Indiana_State_Sycamores_logo.png',
    Iona: `${baseUrl}/logos/Iona_Gaels_logo.png`,
    Iowa: baseUrl + '/logos/Iowa_Hawkeyes_logo.png',
    Iowa_State: baseUrl + '/logos/Iowa_State_Cyclones_logo.png',
    IUPUI: `${baseUrl}/logos/IUPUI_Jaguars_logo.png`,
    JMU: baseUrl + '/logos/James_Madison_University_Athletics_logo.png',
    Jacksonville: baseUrl + '/logos/Jacksonville_Dolphins_logo.png',
    JacksonvilleState: baseUrl + '/logos/Jacksonville_State_Gamecocks_logo.png',
    Jackson_State: baseUrl + '/logos/Jackson_State_athletics_logo.png',
    Kansas: baseUrl + '/logos/Kansas_Jayhawks_logo.png',
    Kansas_State: baseUrl + '/logos/Kansas_State_Wildcats_logo.png',
    Kansas_City_U: `${baseUrl}/logos/kansas_city_roos_logo.png`,
    KennesawState: baseUrl + '/logos/Kennesaw_State_Owls_logo.png',
    Kent_State: baseUrl + '/logos/Kent_State_athletic_logo.png',
    Kentucky: baseUrl + '/logos/Kentucky_Wildcats_logo.png',
    Lafayette: baseUrl + '/logos/Lafayette_Leopards_logo.png',
    Lamar: `${baseUrl}/logos/Lamar_Cardinals_logo.png`,
    LaSalle: baseUrl + '/logos/La_Salle_Explorers_logo.png',
    LeHigh: baseUrl + '/logos/LehighMountainHawks.png',
    Liberty: baseUrl + '/logos/Liberty_Flames_logo.png',
    Lindenwood: `${baseUrl}/logos/Lindenwood_Lions_logo.png`,
    Lipscomb: `${baseUrl}/logos/lipscomb_bisons.png`,
    Little_Rock: `${baseUrl}/logos/Little_Rock_Trojans_logo.png`,
    Long_Beach: `${baseUrl}/logos/Long_Beach_State_Athletics_logo.png`,
    Long_Island: `${baseUrl}/logos/LIU_Sharks_logo.png`,
    Longwood: `${baseUrl}/logos/Longwood_Lancers_logo.png`,
    Louisiana_Tech: baseUrl + '/logos/Louisiana_Tech_Athletics_logo.png',
    Louisiana: baseUrl + '/logos/louisiana-lafayette-ragin-cajuns-logo.png',
    Louisiana_Monroe: baseUrl + '/logos/Louisiana_Monroe_Warhawks.png',
    Louisville: baseUrl + '/logos/Louisville_Cardinals_logo.png',
    LoyolaC: baseUrl + '/logos/Loyola_Ramblers_logo.png',
    LoyolaM: baseUrl + '/logos/LMU_Lions_logo.png',
    Loyola_Maryland: `${baseUrl}/logos/Loyola_Greyhounds_logo.png`,
    LSU: baseUrl + '/logos/LSU_Athletics_logo.png',
    Maine: `${baseUrl}/logos/Maine_Black_Bears_logo.png`,
    Manhattan: `${baseUrl}/logos/Manhattan_Jaspers_logo.png`,
    Marist: `${baseUrl}/logos/Marist_Red_Foxes_logo.png`,
    Marquette: baseUrl + '/logos/Marquette_Golden_Eagles_logo.png',
    Marshall: baseUrl + '/logos/Marshall_Thundering_Herd_logo.png',
    Maryland_East: `${baseUrl}/logos/Maryland_Eastern_Shore_Hawks_logo.png`,
    Maryland: baseUrl + '/logos/Maryland_Terrapins_logo.png',
    McNeese_State: `${baseUrl}/logos/McNeese_State_Athletics_logo.png`,
    Memphis: baseUrl + '/logos/Memphis_Tigers_logo.png',
    Mercer: baseUrl + '/logos/Mercer_Bears_logo.png',
    Merrimack: `${baseUrl}/logos/Merrimack_Warriors.png`,
    Miami: baseUrl + '/logos/Miami_Hurricanes_logo.png',
    Miami_OH: baseUrl + '/logos/Miami_Redhawks_logo.png',
    Michigan_State: baseUrl + '/logos/Michigan_State_Athletics_logo.png',
    Michigan: baseUrl + '/logos/Michigan_Wolverines_logo.png',
    Middle_Tennessee: baseUrl + '/logos/Middle_Tennessee_Athletics_logo.png',
    Milwaukee: `${baseUrl}/logos/Milwaukee_Panthers_logo.png`,
    Minnesota: baseUrl + '/logos/Minnesota_Golden_Gophers_logo.png',
    Mississippi_State: baseUrl + '/logos/Mississippi_State_Bulldogs_logo.png',
    Missouri: baseUrl + '/logos/Missouri_Tigers_logo.png',
    Missouri_State: baseUrl + '/logos/Missouri_State_Athletics_logo.png',
    Monmouth: `${baseUrl}/logos/Monmouth_Hawks_logo.png`,
    Montana: baseUrl + '/logos/Montana_Griz_logo.png',
    Montana_State: baseUrl + '/logos/Montana_State_Bobcats_logo.png',
    Morehead: `${baseUrl}/logos/Morehead_State_Eagles_logo.png`,
    Morgan_State: `${baseUrl}/logos/Morgan_State_Bears_logo.png`,
    Mount_St_Marys: `${baseUrl}/logos/Mount_St_Marys_Mountaineers_logo.png`,
    Murray_State: baseUrl + '/logos/Murray_State_Racers_logo.png',
    Mississippi_Valley: baseUrl + '/logos/MVSU_logo.png',
    Northern_Arizona: baseUrl + '/logos/NAU_logo.png',
    Navy: baseUrl + '/logos/Navy_Athletics_logo.png',
    NC_State:
        baseUrl + '/logos/North_Carolina_State_University_Athletic_logo.png',
    Nebraska: baseUrl + '/logos/Nebraska_Cornhuskers_logo.png',
    Nebraska_Omaha: baseUrl + '/logos/Omaha_Mavericks_logo.png',
    Nevada: baseUrl + '/logos/Nevada_Wolf_Pack_logo.png',
    New_Hampshire: `${baseUrl}/logos/New_Hampshire_Wildcats_logo.png`,
    New_Mexico: baseUrl + '/logos/New_Mexico_Lobos_logo.png',
    New_Mexico_State: baseUrl + '/logos/New_Mexico_State_Aggies_logo.png',
    New_Orleans: `${baseUrl}/logos/New_Orleans_Privateers_logo.png`,
    Niagara: `${baseUrl}/logos/Niagara_Purple_Eagles.png`,
    Nicholls_State: `${baseUrl}/logos/Nicholls_State_Colonels_logo.png`,
    NJIT: `${baseUrl}/logos/NJIT_Highlanders_logo.png`,
    Norfolk_State: `${baseUrl}/logos/Norfork_State_Spartans_logo.png`,
    North_Alabama: `${baseUrl}/logos/North_Alabama_Lions_logo.png`,
    North_Carolina: baseUrl + '/logos/North_Carolina_Tar_Heels_logo.png',
    North_Carolina_AT: `${baseUrl}/logos/North_Carolina_A&T_Aggies_logo.png`,
    North_Carolina_Central: `${baseUrl}/logos/NCCU_Eagles_logo.png`,
    North_Dakota: baseUrl + '/logos/North_Dakota_Fighting_Hawks_logo.png',
    North_Dakota_State: baseUrl + '/logos/North_Dakota_State_Bison_logo.png',
    North_Florida: `${baseUrl}/logos/UNF_Ospreys_logo.png`,
    North_Texas: baseUrl + '/logos/North_Texas_Mean_Green_logo.png',
    Northeastern: `${baseUrl}/logos/Northeastern_Huskies_logo.png`,
    Northern_Colorado: baseUrl + '/logos/Northern_Colorado_Bears_logo.png',
    Northern_Iowa: baseUrl + '/logos/Northern_iowa_Panthers_logo.png',
    Northern_Kentucky: `${baseUrl}/logos/Northern_Kentucky_Norse_logo.png`,
    NIU: baseUrl + '/logos/Northern_Illinois_Huskies_logo.png',
    Northwestern: baseUrl + '/logos/Northwestern_Wildcats_logo.png',
    Northwestern_State: `${baseUrl}/logos/Northwestern_State_Demons_logo.png`,
    Notre_Dame: baseUrl + '/logos/Notre_Dame_Fighting_Irish_logo.png',
    Oakland: `${baseUrl}/logos/Oakland_Golden_Grizzlies_logo.png`,
    Ohio: baseUrl + '/logos/Ohio_Bobcats_logo.png',
    Ohio_State: baseUrl + '/logos/Ohio_State_Buckeyes_logo.png',
    Oklahoma: baseUrl + '/logos/Oklahoma_Sooners_logo.png',
    Oklahoma_State: baseUrl + '/logos/Oklahoma_State_logo.png',
    Old_Dominion: baseUrl + '/logos/Old_Dominion_Athletics_logo.png',
    Ole_Miss: baseUrl + '/logos/Ole_Miss_Rebels_logo.png',
    Oral_Roberts: `${baseUrl}/logos/Oral_Roberts_Golden_Eagles_logo.png`,
    Oregon: baseUrl + '/logos/Oregon_Ducks_logo.png',
    Oregon_State: baseUrl + '/logos/Oregon_State_Beavers_logo.png',
    Pacific: baseUrl + '/logos/Pacific_Tigers_logo.png',
    Pennsylvania: baseUrl + '/logos/Penn_Quakers_logo.png',
    Penn_State: baseUrl + '/logos/Penn_State_Nittany_Lions_logo.png',
    Pepperdine: baseUrl + '/logos/Pepperdine_Waves_logo.png',
    Pitt: baseUrl + '/logos/Pitt_Panthers_logo.png',
    Portland: baseUrl + '/logos/Portland_Pilots_logo.png',
    Portland_State: baseUrl + '/logos/Portland_State_Vikings_logo.png',
    Prairie_View: baseUrl + '/logos/Prairie_View_A&M_Panthers_logo.png',
    Presbyterian_College: `${baseUrl}/logos/Presbyterian_College_logo.png`,
    Princeton: baseUrl + '/logos/Princeton_Tigers_logo.png',
    Providence: baseUrl + '/logos/Providence_Friars_logo.png',
    Purdue: baseUrl + '/logos/Purdue_Boilermakers_logo.png',
    Purdue_Fort_Wayne: `${baseUrl}/logos/Purdue_Fort_Wayne_Mastodons_logo.png`,
    Queens: `${baseUrl}/logos/Queens_Royals_primary_logo.png`,
    Quinnipiac: `${baseUrl}/logos/Quinnipiac_Bobcats_logo.png`,
    Radford: `${baseUrl}/logos/Radford_Highlanders_logo.png`,
    RhodeIsland: baseUrl + '/logos/Rhode_Island_Rams_logo.png',
    Rice: baseUrl + '/logos/Rice_Owls_logo.png',
    Richmond: baseUrl + '/logos/Richmond_Spiders_logo.png',
    Rider: `${baseUrl}/logos/Rider_Broncs.png`,
    Rio_Grande_Valley: `${baseUrl}/logos/Rio_Grande_Valley_Vaqueros_logo.png`,
    Robert_Morris: `${baseUrl}/logos/Robert_Morris_Colonials_logo.png`,
    Rutgers: baseUrl + '/logos/Rutgers_Scarlet_Knights_logo.png',
    Sacramento_State: baseUrl + '/logos/Sacramento_State_Hornets_logo.png',
    Sacred_Heart: `${baseUrl}/logos/Sacred_Heart_Pioneers_logo.png`,
    Saint_Francis: `${baseUrl}/logos/Saint_Francis_Red_Flash_logo.png`,
    SaintJosephs: baseUrl + '/logos/Saint_Josephs_Hawks_logo.png',
    SaintLouis: baseUrl + '/logos/Saint_Louis_Billikens_logo.png',
    Saint_Peters: `${baseUrl}/logos/Saint_Peters_Peacocks_logo.png`,
    Samford: baseUrl + '/logos/Samford_Bulldogs_logo.png',
    SamHoustonState: baseUrl + '/logos/SHSU_athletics_logo.png',
    San_Diego_State: baseUrl + '/logos/San_Diego_State_Aztecs_logo.png',
    SantaClara: baseUrl + '/logos/Santa_Clara_Broncos_logo.png',
    SFDons: baseUrl + '/logos/San_Francisco_Dons_logo.png',
    SFA: `${baseUrl}/logos/sfa_logo.png`,
    San_Jose: baseUrl + '/logos/San_Jose_State_Spartans_logo.png',
    Seattle: baseUrl + '/logos/Seattle_Redhawks_logo.png',
    SetonHall: baseUrl + '/logos/Seton_Hall_Pirates_logo.png',
    Siena: `${baseUrl}/logos/Siena_Saints_logo.png`,
    SIU_E: `${baseUrl}/logos/siue_cougars_logo.png`,
    SMU: baseUrl + '/logos/SMU_Mustang_logo.png',
    South_Alabama: baseUrl + '/logos/South_Alabama_Jaguars_logo.png',
    South_Carolina: baseUrl + '/logos/South_Carolina_Gamecocks_logo.png',
    South_Carolina_State: `${baseUrl}/logos/South_Carolina_State_Bulldogs_logo.png`,
    South_Dakota: baseUrl + '/logos/South_Dakota_Coyotes_logo.png',
    South_Dakota_State:
        baseUrl + '/logos/South_Dakota_State_Jackrabbits_logo.png',
    South_Florida: baseUrl + '/logos/South_Florida_Bulls_logo.png',
    Southeast_Missouri: `${baseUrl}/logos/semo_logo.png`,
    Southeastern_Louisiana: `${baseUrl}/logos/Southeastern_Louisiana_Lions_logo.png`,
    Southern: baseUrl + '/logos/Southern_Jaguars_logo.png',
    Southern_Illinois: baseUrl + '/logos/southern_illinois_salukis_logo.png',
    Southern_Indiana: `${baseUrl}/logos/Southern_Indiana_Screaming_Eagles_logo.png`,
    Southern_Miss: baseUrl + '/logos/Southern_Miss_Athletics_logo.png',
    Southern_Utah: `${baseUrl}/logos/Southern_Utah_Thunderbirds_logo.png`,
    Stanford: baseUrl + '/logos/Stanford_Cardinal_logo.png',
    St_Bonaventure: baseUrl + '/logos/St._Bonaventure_Bonnies_logo.png',
    St_Francis: `${baseUrl}/logos/st_Francis_Brooklyn_Terriers_logo.png`,
    St_Marys: baseUrl + "/logos/Saint_Mary's_College_Gaels_logo.png",
    St_Thomas: `${baseUrl}/logos/st_thomas_tommies_logo.png`,
    StJohns: baseUrl + '/logos/St_Johns_Red_Storm_logo.png',
    Stetson: `${baseUrl}/logos/Stetson_Hatters_logo.png`,
    Stonehill: `${baseUrl}/logos/Stonehill_Skyhawks_logo.png`,
    Stony_Brook: `${baseUrl}/logos/Stony_Brook_Seawolves_logo.png`,
    Syracuse: baseUrl + '/logos/Syracuse_Orange_logo.png',
    Tarleton: `${baseUrl}/logos/Tarleton_Ton_logo.png`,
    TCU: baseUrl + '/logos/TCU_Horned_Frogs_logo.png',
    Temple: baseUrl + '/logos/Temple_Owls_logo.png',
    Tennessee: baseUrl + '/logos/Tennessee_Volunteers_logo.png',
    Tennessee_State: `${baseUrl}/logos/Tennessee_State_logo.png`,
    Tennessee_Tech: `${baseUrl}/logos/Tennessee_Tech_Golden_Eagles_logo.png`,
    TAMU: baseUrl + '/logos/Texas_A&M_University_logo.png',
    Texas_AM_Corpus: `${baseUrl}/logos/tamu_Corpus_Christi_Islanders_logo.png`,
    Texas_AM_Commerce: `${baseUrl}/logos/Texas_A&M_Commerce_Lions_logo.png`,
    Texas: baseUrl + '/logos/Texas_Longhorns_logo.png',
    Texas_Tech: baseUrl + '/logos/Texas_Tech_Athletics_logo.png',
    Texas_State: baseUrl + '/logos/Texas_State_Bobcats_logo.png',
    Texas_Southern: baseUrl + '/logos/Texas_Southern_Tigers_logo.png',
    Toledo: baseUrl + '/logos/Toledo_Rockets_logo.png',
    Towson: `${baseUrl}/logos/Towson_Tigers_logo.png`,
    Troy: baseUrl + '/logos/Troy_Trojans_logo.png',
    Tulane: baseUrl + '/logos/Tulane_Green_Wave_logo.png',
    Tulsa: baseUrl + '/logos/Tulsa_Golden_Hurricane_logo.png',
    UAB: baseUrl + '/logos/UAB_Blazers_logo.png',
    UCF: baseUrl + '/logos/UCF_Knights_logo.png',
    UC_Davis: baseUrl + '/logos/UC_Davis_Aggies_logo.png',
    UC_Irvine: baseUrl + '/logos/UC_Irvine_Anteaters_logo.png',
    UC_Riverside: `${baseUrl}/logos/UC_Riverside_Highlanders_logo.png`,
    UC_San_Diego: baseUrl + '/logos/UC_San_Diego.png',
    UC_Santa_Barbara: `${baseUrl}/logos/UC_Santa_Barbara_Gauchos_logo.png`,
    U_San_Diego: baseUrl + '/logos/San_Diego_Toreros_logo.png',
    UCLA: baseUrl + '/logos/UCLA_Bruins_logo.png',
    UIC: `${baseUrl}/logos/UIC_Flames_logo.png`,
    UMASS: baseUrl + '/logos/UMass_Amherst_Athletics_logo.png',
    UMASS_Amherst: `${baseUrl}/logos/UMass_Amherst_Athletics_logo.png`,
    UMASS_Lowell: `${baseUrl}/logos/UMass_Lowell_River_Hawks_logo.png`,
    UMBC: baseUrl + '/logos/UMBC_Retrievers_logo.png',
    UNC_Asheville: `${baseUrl}/logos/UNC_Asheville_Bulldogs_logo.png`,
    UNC_Wilmington: `${baseUrl}/logos/UNC_Wilmington_Seahawks_logo.png`,
    UNCG: `${baseUrl}/logos/UNCG_Spartans_logo.png`,
    UNLV: baseUrl + '/logos/UNLV_Rebels_wordmark.png',
    USC: baseUrl + '/logos/USC_Trojans_logo.png',
    USC_Upstate: `${baseUrl}/logos/USC_Upstate_Spartans_logo.png`,
    UT_Arlington: `${baseUrl}/logos/UT_Arlington_Mavericks_logo.png`,
    UT_Martin: `${baseUrl}/logos/UT_Martin_Skyhawks_logo.png`,
    Utah_State: baseUrl + '/logos/Utah_State_Aggies_logo.png',
    Utah: baseUrl + '/logos/Utah_Utes_logo.png',
    Utah_Tech: `${baseUrl}/logos/Utah_Tech_Trailblazers_logo.png`,
    Utah_Valley: `${baseUrl}/logos/Utah_Valey_Wolverines_logo.png`,
    UTEP: baseUrl + '/logos/UTEP_Miners_logo.png',
    UTSA: baseUrl + '/logos/UTSA_Roadrunners_logo.png',
    Valparaiso: `${baseUrl}/logos/Valparaiso_Crusaders_logo.png`,
    Vanderbilt: baseUrl + '/logos/Vanderbilt.png',
    VCU: baseUrl + '/logos/VCU_Rams_logo.png',
    Vermont: `${baseUrl}/logos/Vermont_Catamounts_logo.png`,
    Villanova: baseUrl + '/logos/Villanova_Wildcats_logo.png',
    Virginia: baseUrl + '/logos/Virginia_Cavaliers_logo.png',
    Virginia_Tech: baseUrl + '/logos/Virginia_Tech_Hokies_logo.png',
    VMI: baseUrl + '/logos/VMI_Keydets_logo.png',
    Wagner: `${baseUrl}/logos/Wagner_Seahawks_logo.png`,
    Wake_Forest: baseUrl + '/logos/Wake_Forest_University_Athletic_logo.png',
    Washington: baseUrl + '/logos/Washington_Huskies_logo.png',
    Washington_State: baseUrl + '/logos/Washington_State_Cougars_logo.png',
    Weber_State: baseUrl + '/logos/Weber_State_Wildcats_logo.png',
    West_Virginia: baseUrl + '/logos/West_Virginia_Mountaineers_logo.png',
    Western_Carolina: baseUrl + '/logos/Western_Carolina_Catamounts_logo.png',
    Western_Illinois: baseUrl + '/logos/Western_Illinois_Leathernecks_logo.png',
    Western_Kentucky: baseUrl + '/logos/WKU_Athletics_logo.png',
    Western_Michigan: baseUrl + '/logos/Western_Michigan.png',
    Wichita_State: baseUrl + '/logos/Wichita_State_Shockers_logo.png',
    William_and_Mary: `${baseUrl}/logos/William_and_Mary_Tribe_logo.png`,
    Winthrop: `${baseUrl}/logos/Winthrop_Eagles_logo.png`,
    Wisconsin: baseUrl + '/logos/Wisconsin_Badgers_logo.png',
    Wofford: baseUrl + '/logos/Wofford_Terriers_logo.png',
    Wright_State: `${baseUrl}/logos/Wright_State_Raiders_logo.png`,
    Wyoming: baseUrl + '/logos/Wyoming_Athletics_logo.png',
    Xavier: baseUrl + '/logos/xavier_logo.png',
    Yale: baseUrl + '/logos/Yale_Bulldogs.png',
    Youngstown_State: baseUrl + '/logos/Youngstown_State.png',

    Unknown: baseUrl + '/logos/unknown1.png',
    SEA_Supersonics: baseUrl + '/logos/supersonics.png',
    SEA_Seahawks: baseUrl + '/logos/SEA_Seahawks.png',
    BUF_Bills: baseUrl + '/logos/BUF_Bills.png',
    MIA_Dolphins: baseUrl + '/logos/MIA_Dolphins.png',
    NE_Patriots: baseUrl + '/logos/NE_Patriots.png',
    NY_Jets: baseUrl + '/logos/NY_Jets.png',
    BAL_Ravens: baseUrl + '/logos/BAL_Ravens.png',
    CIN_Bengals: baseUrl + '/logos/CIN_Bengals.png',
    CLE_Browns: baseUrl + '/logos/CLE_Browns.png',
    PIT_Steelers: baseUrl + '/logos/PIT_Steelers.png',
    HOU_Texans: baseUrl + '/logos/HOU_Texans.png',
    IND_Colts: baseUrl + '/logos/IND_Colts.png',
    JAX_Jaguars: baseUrl + '/logos/JAX_Jaguars.png',
    TEN_Titans: baseUrl + '/logos/TEN_Titans.png',
    DEN_Broncos: baseUrl + '/logos/DEN_Broncos.png',
    KC_Chiefs: baseUrl + '/logos/KC_Chiefs.png',
    LV_Raiders: baseUrl + '/logos/LV_Raiders.png',
    LA_Chargers: baseUrl + '/logos/LA_Chargers.png',
    DAL_Cowboys: baseUrl + '/logos/DAL_Cowboys.png',
    NY_Giants: baseUrl + '/logos/NY_Giants.png',
    PHI_Eagles: baseUrl + '/logos/PHI_Eagles.png',
    WFT: baseUrl + '/logos/WFT.png',
    WAS_Commies: baseUrl + '/logos/Washington_Commanders_logo.png',
    CHI_Bears: baseUrl + '/logos/CHI_Bears.png',
    DET_Lions: baseUrl + '/logos/DET_Lions.png',
    GB_Packers: baseUrl + '/logos/GB_Packers.png',
    MN_Vikings: baseUrl + '/logos/MN_Vikings.png',
    ATL_Falcons: baseUrl + '/logos/ATL_Falcons.png',
    CAR_Panthers: baseUrl + '/logos/CAR_Panthers.png',
    NO_Saints: baseUrl + '/logos/NO_Saints.png',
    TB_Buccaneers: baseUrl + '/logos/TB_Buccaneers.png',
    ARI_Cardinals: baseUrl + '/logos/ARI_Cardinals.png',
    LA_Rams: baseUrl + '/logos/LA_Rams.png',
    SF_49ers: baseUrl + '/logos/SF_49ers.png',
    VAN_Sealions: baseUrl + '/logos/VAN_Sealions_2.png',
    VGK: baseUrl + '/logos/',
    BOS_Celtics: baseUrl + '/logos/BOS_Celtics.png',
    BRK_Nets: baseUrl + '/logos/BRK_Nets.png',
    NY_Knicks: baseUrl + '/logos/NY_Knicks.png',
    PHI_76ers: baseUrl + '/logos/PHI_76ers.png',
    TOR_Raptors: baseUrl + '/logos/TOR_Raptors.png',
    CHI_Bulls: baseUrl + '/logos/CHI_Bulls.png',
    CLE_Cavaliers: baseUrl + '/logos/CLE_Cavaliers.png',
    DET_Pistons: baseUrl + '/logos/DET_Pistons.png',
    IND_Pacers: baseUrl + '/logos/IND_Pacers.png',
    MIL_Bucks: baseUrl + '/logos/MIL_Bucks.png',
    ATL_Hawks: baseUrl + '/logos/ATL_Hawks.png',
    CHA_Hornets: baseUrl + '/logos/CHA_Hornets.png',
    MIA_Heat: baseUrl + '/logos/MIA_Heat.png',
    ORL_Magic: baseUrl + '/logos/ORL_Magic.png',
    WAS_Wizards: baseUrl + '/logos/WAS_Wizards.png',
    DEN_Nuggets: baseUrl + '/logos/DEN_Nuggets.png',
    MIN_Timberwolves: baseUrl + '/logos/MIN_Timberwolves.png',
    OKC_Thunder: baseUrl + '/logos/OKC_Thunder.png',
    POR_Trailblazers: baseUrl + '/logos/POR_Trailblazers.png',
    UTA_Jazz: baseUrl + '/logos/UTA_Jazz.png',
    GS_Warriors: baseUrl + '/logos/GS_Warriors.png',
    LA_Clippers: baseUrl + '/logos/LA_Clippers.png',
    LA_Lakers: baseUrl + '/logos/LA_Lakers.png',
    PHO_Suns: baseUrl + '/logos/PHO_Suns.png',
    SAC_Kings: baseUrl + '/logos/SAC_Kings.png',
    DAL_Mavericks: baseUrl + '/logos/DAL_Mavericks.png',
    HOU_Rockets: baseUrl + '/logos/HOU_Rockets.png',
    MEM_Grizzlies: baseUrl + '/logos/MEM_Grizzlies.png',
    NO_Pelicans: baseUrl + '/logos/NO_Pelicans.png',
    SA_Spurs: baseUrl + '/logos/SA_Spurs.png'
};

export default logos;
