export const baseUrl = 'https://calebrose.io/simfba-logo-cdn';

export const logos = {
    Abilene_Christian: `${baseUrl}/logos/Abilene_Christian_Wildcats_logo.png`,
    Air_Force: baseUrl + '/logos/Air_Force_Falcons_logo.png',
    Akron_Zips: baseUrl + '/logos/Akron_Zips_logo.png',
    Alabama: baseUrl + '/logos/Alabama_Crimson_Tide_logo.png',
    Alabama_AM: baseUrl + '/logos/Alabama_A&M_Bulldogs_logo.png',
    Alabama_State: baseUrl + '/logos/Alabama_State_logo.png',
    Albany: `${baseUrl}/logos/Albany_Great_Danes_logo.png`,
    Alcorn_State: baseUrl + '/logos/Alcorn_State_athletics_logo.png',
    American: `${baseUrl}/logos/American_Eagles_logo.png`,
    AmericanSamoa: `${baseUrl}/logos/american_samoa_athletics_logo.png`,
    App_State: baseUrl + '/logos/App_state_2.png',
    Arizona_State: baseUrl + '/logos/Arizona_State_Sun_Devils_2.png',
    Arizona: baseUrl + '/logos/Arizona_Wildcats_logo.png',
    Arkansas: baseUrl + '/logos/Arkansas_Logo_2.png',
    Arkansas_State: baseUrl + '/logos/Arkansas_State_Red_Wolves_logo.png',
    Arkansas_Pine_Bluff:
        baseUrl + '/logos/Arkansas_Pine_Bluff_Golden_Lions_logo.png',
    Army: baseUrl + '/logos/Army_West_Point_logo.png',
    Auburn: baseUrl + '/logos/Auburn_Tigers_logo.png',
    Austin_Peay: `${baseUrl}/logos/Austin_Peay_Governors_logo.png`,
    Ball_State: baseUrl + '/logos/Ball_State_Cardinals_logo.png',
    Baylor: baseUrl + '/logos/Baylor_Green.png',
    Bellarmine: `${baseUrl}/logos/Bellarmine_Knights_logo.png`,
    Belmont: `${baseUrl}/logos/Belmont_Bruins_logo.png`,
    Bethune_Cookman: baseUrl + '/logos/Bethune_Cookman_Wildcats_logo.png',
    Binghamton: `${baseUrl}/logos/Binghamton_Bearcats_logo.png`,
    Boise_State: baseUrl + '/logos/Boise_State_Broncos_logo.png',
    Boston_College: baseUrl + '/logos/Boston_College_Eagles_logo.png',
    Boston: `${baseUrl}/logos/Boston_University_Terriers_logo.png`,
    Bowling_Green: baseUrl + '/logos/Bowling_Green_Falcons_logo.png',
    Bradley: `${baseUrl}/logos/Bradley_Braves_logo.png`,
    Brown: baseUrl + '/logos/Brown_Bears_Athletics_logo.png',
    Bryant: `${baseUrl}/logos/Bryant_Bulldogs_logo.png`,
    Bucknell: baseUrl + '/logos/Bucknell_Bison_logo.png',
    Buffalo: baseUrl + '/logos/Buffalo_Bulls_logo.png',
    Butler: baseUrl + '/logos/Butler_Bulldogs_logo.png',
    BYU: baseUrl + '/logos/BYU_Cougars_logo.png',
    California: baseUrl + '/logos/California_Golden_Bears_logo_2.png',
    Cal_Poly: baseUrl + '/logos/Cal_Poly_Mustangs_logo.png',
    Cal_State_Bakersfield: `${baseUrl}/logos/Cal_State_Bakersfield_Roadrunners_logo.png`,
    Cal_State_Fullerton: `${baseUrl}/logos/Cal_State_Fullerton_Titans_logo.png`,
    Cal_State_Northridge: `${baseUrl}/logos/CSUN_Matadors_logo.png`,
    California_Baptist: `${baseUrl}/logos/California_Baptist_logo.png`,
    Campbell: `${baseUrl}/logos/Campbell_Fighting_Camels_logo.png`,
    Canisius: `${baseUrl}/logos/Canisius_Golden_Griffins.png`,
    Central_Arkansas: `${baseUrl}/logos/Central_Arkansas_Athletics_logo.png`,
    Central_Connecticut: `${baseUrl}/logos/Central_Connecticut_Blue_Devils_logo.png`,
    Central_Michigan: baseUrl + '/logos/Central_Michigan_Chippewas_logo.png',
    Chaminade: `${baseUrl}/logos/Chaminade_logo.png`,
    Charleston: `${baseUrl}/logos/Charleston_Cougars_logo.png`,
    Charleston_Southern: `${baseUrl}/logos/Charleston_Southern_Buccaneers_logo.png`,
    Charlotte: baseUrl + '/logos/Charlotte_49ers_logo.png',
    Chattanooga: baseUrl + '/logos/Chattanooga_Mocs_logo.png',
    Chicago_State: `${baseUrl}/logos/Chicago_State_Cougars_logo.png`,
    Cincinnati: baseUrl + '/logos/Cincinnati_Bearcats_logo.png',
    Citadel: baseUrl + '/logos/Citadel_Bulldogs_logo.png',
    Clemson: baseUrl + '/logos/Clemson_Tigers_logo.png',
    Cleveland_State: `${baseUrl}/logos/Cleveland_State_Vikings_logo.png`,
    Coastal_Carolina: baseUrl + '/logos/Coastal_Carolina_Chanticleers_logo.png',
    Colgate: baseUrl + '/logos/Colgate_Raiders_logo.png',
    Colorado: baseUrl + '/logos/Colorado_Buffaloes_logo.png',
    Colorado_State: baseUrl + '/logos/Colorado_State_Rams_logo.png',
    Columbia: baseUrl + '/logos/Columbia_Lions_logo.png',
    Connecticut: baseUrl + '/logos/Connecticut_Huskies_logo.png',
    Coppin_State: `${baseUrl}/logos/Coppin_State_Eagles_logo.png`,
    Cornell: baseUrl + '/logos/Cornell_Big_Red_logo.png',
    Creighton: baseUrl + '/logos/Creighton_Bluejays_logo.png',
    Dartmouth: baseUrl + '/logos/Dartmouth_College_Big_Green_logo.png',
    Davidson: baseUrl + '/logos/Davidson_Wildcats_logo.png',
    Dayton: baseUrl + '/logos/dayton_flyers_logo.png',
    Delaware: `${baseUrl}/logos/Delaware_Blue_Hens_Logo.png`,
    Delaware_State: `${baseUrl}/logos/Delaware_State_Hornets_logo.png`,
    Denver: `${baseUrl}/logos/Denver_Pioneers_Athletics_logo.png`,
    DePaul: baseUrl + '/logos/DePaul_Blue_Demons_logo.png',
    Detroit_Mercy: `${baseUrl}/logos/Detroit_Titans_logo.png`,
    Drake: `${baseUrl}/logos/Drake_Bulldogs_logo.png`,
    Drexel: `${baseUrl}/logos/Drexel_Dragons_logo.png`,
    Duke: baseUrl + '/logos/Duke_Athletics_logo.png',
    Duquesne: baseUrl + '/logos/Duquesne_Dukes_logo.png',
    East_Carolina: baseUrl + '/logos/East_Carolina_Pirates_logo.png',
    ETSU: baseUrl + '/logos/East_Tennessee_State_Buccaneers_logo.png',
    Eastern_Illinois: `${baseUrl}/logos/Eastern_Illinois_Panthers_logo.png`,
    Eastern_Kentucky: `${baseUrl}/logos/Eastern_Kentucky_Colonels_logo.png`,
    Eastern_Michigan: baseUrl + '/logos/Eastern_Michigan_Eagles_logo.png',
    Eastern_Washington: baseUrl + '/logos/Eastern_Washington_Eagles_logo.png',
    Elon: `${baseUrl}/logos/Elon_Phoenix_logo.png`,
    Evansville: baseUrl + '/logos/Evansville_Purple_Aces_logo.png',
    Fairfield: `${baseUrl}/logos/Fairfield_Stags_logo.png`,
    Fairleigh_Dickinson: `${baseUrl}/logos/FDU_Knights_Logo.png`,
    FAMU: baseUrl + '/logos/FAMU_Rattler.png',
    FGCU: baseUrl + '/logos/Florida_Gulf_Coast_Eagles_logo.png',
    FIU: baseUrl + '/logos/FIU_Panthers_logo.png',
    Florida_Atlantic: baseUrl + '/logos/Florida_Atlantic_Owls_logo.png',
    Florida: baseUrl + '/logos/Florida_Gators_logo.png',
    Florida_State: baseUrl + '/logos/Florida_State_Seminoles_logo.png',
    Fordham: baseUrl + '/logos/Fordham_Rams_logo.png',
    Fresno_State: baseUrl + '/logos/Fresno_State_Bulldogs_logo.png',
    Furman: baseUrl + '/logos/Furman_Paladins_logo.png',
    Gardner_Webb: `${baseUrl}/logos/Gardner_Webb_Bulldogs_Logo.png`,
    GeorgeMason: baseUrl + '/logos/George_Mason_Patriots_logo.png',
    Georgetown: baseUrl + '/logos/Georgetown_Hoyas_logo.png',
    GeorgeWashington: baseUrl + '/logos/George_Washington_Colonials_logo.png',
    Georgia: baseUrl + '/logos/Georgia_Athletics_logo.png',
    Georgia_Southern: baseUrl + '/logos/Georgia_Southern_Eagles_logo.png',
    Georgia_State: baseUrl + '/logos/Georgia_State_Athletics_logo.png',
    Georgia_Tech: baseUrl + '/logos/Georgia_Tech_Yellow_Jackets_logo.png',
    Gonzaga: baseUrl + '/logos/Gonzaga_Bulldogs_logo.png',
    Grambling_State: baseUrl + '/logos/Grambling_State_Tigers_logo.png',
    Grand_Canyon: `${baseUrl}/logos/Grand_Canyon_Antelopes_logo.png`,
    Green_Bay: `${baseUrl}/logos/Green_Bay_Phoenix_logo.png`,
    Guam: `${baseUrl}/logos/Guam_logo.png`,
    Hampton: `${baseUrl}/logos/Hampton_Pirates_logo.png`,
    Hartford: `${baseUrl}/logos/Hartford_Hawks_logo.png`,
    Harvard: baseUrl + '/logos/Harvard_Crimson_logo.png',
    Hawaii: baseUrl + '/logos/Hawaii_Warriors_logo.png',
    High_Point: `${baseUrl}/logos/High_Point_Panthers_logo.png`,
    Hofstra: `${baseUrl}/logos/Hofstra_Pride_logo.png`,
    Holy_Cross: baseUrl + '/logos/Holy_Cross_Crusaders_logo.png',
    Houston: baseUrl + '/logos/Houston_Cougars_primary_logo.png',
    Houston_Baptist: `${baseUrl}/logos/Houston_Baptist_Huskies_logo.png`,
    Howard: `${baseUrl}/logos/Howard_Bison_logo.png`,
    Idaho: baseUrl + '/logos/Idaho_Vandals_logo.png',
    Idaho_State: baseUrl + '/logos/Idaho_State_Bengals_logo.png',
    Illinois: baseUrl + '/logos/Illinois_Fighting_Illini_logo.png',
    Illinois_State: baseUrl + '/logos/Illinois_State_Athletics_logo.png',
    Incarnate_Word: `${baseUrl}/logos/Incarnate_Word_Cardinals_logo.png`,
    Indiana: baseUrl + '/logos/Indiana_Hoosiers_logo.png',
    Indiana_State: baseUrl + '/logos/Indiana_State_Sycamores_logo.png',
    Iona: `${baseUrl}/logos/Iona_Gaels_logo.png`,
    Iowa: baseUrl + '/logos/Iowa_Hawkeyes_logo.png',
    Iowa_State: baseUrl + '/logos/Iowa_State_Cyclones_logo.png',
    IUPUI: `${baseUrl}/logos/IUPUI_Jaguars_logo.png`,
    JMU: baseUrl + '/logos/James_Madison_University_Athletics_logo.png',
    Jacksonville: baseUrl + '/logos/Jacksonville_Dolphins_logo.png',
    JacksonvilleState: baseUrl + '/logos/Jacksonville_State_Gamecocks_logo.png',
    Jackson_State: baseUrl + '/logos/Jackson_State_athletics_logo.png',
    Kansas: baseUrl + '/logos/Kansas_Jayhawks_logo.png',
    Kansas_State: baseUrl + '/logos/Kansas_State_Wildcats_logo.png',
    Kansas_City_U: `${baseUrl}/logos/kansas_city_roos_logo.png`,
    KennesawState: baseUrl + '/logos/Kennesaw_State_Owls_logo.png',
    Kent_State: baseUrl + '/logos/Kent_State_athletic_logo.png',
    Kentucky: baseUrl + '/logos/Kentucky_Wildcats_logo.png',
    Lafayette: baseUrl + '/logos/Lafayette_Leopards_logo.png',
    Lamar: `${baseUrl}/logos/Lamar_Cardinals_logo.png`,
    LaSalle: baseUrl + '/logos/La_Salle_Explorers_logo.png',
    LeHigh: baseUrl + '/logos/LehighMountainHawks.png',
    Lemoyne: `${baseUrl}/logos/Le_Moyne_Dolphins_logo.png`,
    Liberty: baseUrl + '/logos/Liberty_Flames_logo.png',
    Lindenwood: `${baseUrl}/logos/Lindenwood_Lions_logo.png`,
    Lipscomb: `${baseUrl}/logos/lipscomb_bisons.png`,
    Little_Rock: `${baseUrl}/logos/Little_Rock_Trojans_logo.png`,
    Long_Beach: `${baseUrl}/logos/Long_Beach_State_Athletics_logo.png`,
    Long_Island: `${baseUrl}/logos/LIU_Sharks_logo.png`,
    Longwood: `${baseUrl}/logos/Longwood_Lancers_logo.png`,
    Louisiana_Tech: baseUrl + '/logos/Louisiana_Tech_Athletics_logo.png',
    Louisiana: baseUrl + '/logos/louisiana-lafayette-ragin-cajuns-logo.png',
    Louisiana_Monroe: baseUrl + '/logos/Louisiana_Monroe_Warhawks.png',
    Louisville: baseUrl + '/logos/Louisville_Cardinals_logo.png',
    LoyolaC: baseUrl + '/logos/Loyola_Ramblers_logo.png',
    LoyolaM: baseUrl + '/logos/LMU_Lions_logo.png',
    Loyola_Maryland: `${baseUrl}/logos/Loyola_Greyhounds_logo.png`,
    LSU: baseUrl + '/logos/LSU_Athletics_logo.png',
    Maine: `${baseUrl}/logos/Maine_Black_Bears_logo.png`,
    Manhattan: `${baseUrl}/logos/Manhattan_Jaspers_logo.png`,
    Marist: `${baseUrl}/logos/Marist_Red_Foxes_logo.png`,
    Marquette: baseUrl + '/logos/Marquette_Golden_Eagles_logo.png',
    Marshall: baseUrl + '/logos/Marshall_Thundering_Herd_logo.png',
    Maryland_East: `${baseUrl}/logos/Maryland_Eastern_Shore_Hawks_logo.png`,
    Maryland: baseUrl + '/logos/Maryland_Terrapins_logo.png',
    McNeese_State: `${baseUrl}/logos/McNeese_State_Athletics_logo.png`,
    Memphis: baseUrl + '/logos/Memphis_Tigers_logo.png',
    Mercer: baseUrl + '/logos/Mercer_Bears_logo.png',
    Mercyhurst: `${baseUrl}/logos/Mercyhurst_logo.png`,
    Merrimack: `${baseUrl}/logos/Merrimack_Warriors.png`,
    Miami: baseUrl + '/logos/Miami_Hurricanes_logo.png',
    Miami_OH: baseUrl + '/logos/Miami_Redhawks_logo.png',
    Michigan_State: baseUrl + '/logos/Michigan_State_Athletics_logo.png',
    Michigan: baseUrl + '/logos/Michigan_Wolverines_logo.png',
    Middle_Tennessee: baseUrl + '/logos/Middle_Tennessee_Athletics_logo.png',
    Milwaukee: `${baseUrl}/logos/Milwaukee_Panthers_logo.png`,
    Minnesota: baseUrl + '/logos/Minnesota_Golden_Gophers_logo.png',
    Mississippi_State: baseUrl + '/logos/Mississippi_State_Bulldogs_logo.png',
    Missouri: baseUrl + '/logos/Missouri_Tigers_logo.png',
    Missouri_State: baseUrl + '/logos/Missouri_State_Athletics_logo.png',
    Monmouth: `${baseUrl}/logos/Monmouth_Hawks_logo.png`,
    Montana: baseUrl + '/logos/Montana_Griz_logo.png',
    Montana_State: baseUrl + '/logos/Montana_State_Bobcats_logo.png',
    Morehead: `${baseUrl}/logos/Morehead_State_Eagles_logo.png`,
    Morgan_State: `${baseUrl}/logos/Morgan_State_Bears_logo.png`,
    Mount_St_Marys: `${baseUrl}/logos/Mount_St_Marys_Mountaineers_logo.png`,
    Murray_State: baseUrl + '/logos/Murray_State_Racers_logo.png',
    Mississippi_Valley: baseUrl + '/logos/MVSU_logo.png',
    Northern_Arizona: baseUrl + '/logos/NAU_logo.png',
    Navy: baseUrl + '/logos/Navy_Athletics_logo.png',
    NC_State:
        baseUrl + '/logos/North_Carolina_State_University_Athletic_logo.png',
    Nebraska: baseUrl + '/logos/Nebraska_Cornhuskers_logo.png',
    Nebraska_Omaha: baseUrl + '/logos/Omaha_Mavericks_logo.png',
    Nevada: baseUrl + '/logos/Nevada_Wolf_Pack_logo.png',
    New_Hampshire: `${baseUrl}/logos/New_Hampshire_Wildcats_logo.png`,
    New_Mexico: baseUrl + '/logos/New_Mexico_Lobos_logo.png',
    New_Mexico_State: baseUrl + '/logos/New_Mexico_State_Aggies_logo.png',
    New_Orleans: `${baseUrl}/logos/New_Orleans_Privateers_logo.png`,
    Niagara: `${baseUrl}/logos/Niagara_Purple_Eagles.png`,
    Nicholls_State: `${baseUrl}/logos/Nicholls_State_Colonels_logo.png`,
    NJIT: `${baseUrl}/logos/NJIT_Highlanders_logo.png`,
    Norfolk_State: `${baseUrl}/logos/Norfork_State_Spartans_logo.png`,
    North_Alabama: `${baseUrl}/logos/North_Alabama_Lions_logo.png`,
    North_Carolina: baseUrl + '/logos/North_Carolina_Tar_Heels_logo.png',
    North_Carolina_AT: `${baseUrl}/logos/North_Carolina_A&T_Aggies_logo.png`,
    North_Carolina_Central: `${baseUrl}/logos/NCCU_Eagles_logo.png`,
    North_Dakota: baseUrl + '/logos/North_Dakota_Fighting_Hawks_logo.png',
    North_Dakota_State: baseUrl + '/logos/North_Dakota_State_Bison_logo.png',
    North_Florida: `${baseUrl}/logos/UNF_Ospreys_logo.png`,
    North_Texas: baseUrl + '/logos/North_Texas_Mean_Green_logo.png',
    Northeastern: `${baseUrl}/logos/Northeastern_Huskies_logo.png`,
    Northern_Colorado: baseUrl + '/logos/Northern_Colorado_Bears_logo.png',
    Northern_Iowa: baseUrl + '/logos/Northern_Iowa_Panthers_logo.png',
    Northern_Kentucky: `${baseUrl}/logos/Northern_Kentucky_Norse_logo.png`,
    NIU: baseUrl + '/logos/Northern_Illinois_Huskies_logo.png',
    Northwestern: baseUrl + '/logos/Northwestern_Wildcats_logo.png',
    Northwestern_State: `${baseUrl}/logos/Northwestern_State_Demons_logo.png`,
    Notre_Dame: baseUrl + '/logos/Notre_Dame_Fighting_Irish_logo.png',
    Oakland: `${baseUrl}/logos/Oakland_Golden_Grizzlies_logo.png`,
    Ohio: baseUrl + '/logos/Ohio_Bobcats_logo.png',
    Ohio_State: baseUrl + '/logos/Ohio_State_Buckeyes_logo.png',
    Oklahoma: baseUrl + '/logos/Oklahoma_Sooners_logo.png',
    Oklahoma_State: baseUrl + '/logos/Oklahoma_State_logo.png',
    Old_Dominion: baseUrl + '/logos/Old_Dominion_Athletics_logo.png',
    Ole_Miss: baseUrl + '/logos/Ole_Miss_Rebels_logo.png',
    Oral_Roberts: `${baseUrl}/logos/Oral_Roberts_Golden_Eagles_logo.png`,
    Oregon: baseUrl + '/logos/Oregon_Ducks_logo.png',
    Oregon_State: baseUrl + '/logos/Oregon_State_Beavers_logo.png',
    Pacific: baseUrl + '/logos/Pacific_Tigers_logo.png',
    Pennsylvania: baseUrl + '/logos/Penn_Quakers_logo.png',
    Penn_State: baseUrl + '/logos/Penn_State_Nittany_Lions_logo.png',
    Pepperdine: baseUrl + '/logos/Pepperdine_Waves_logo.png',
    Pitt: baseUrl + '/logos/Pitt_Panthers_logo.png',
    Portland: baseUrl + '/logos/Portland_Pilots_logo.png',
    Portland_State: baseUrl + '/logos/Portland_State_Vikings_logo.png',
    Prairie_View: baseUrl + '/logos/Prairie_View_A&M_Panthers_logo.png',
    Presbyterian_College: `${baseUrl}/logos/Presbyterian_College_logo.png`,
    Princeton: baseUrl + '/logos/Princeton_Tigers_logo.png',
    Providence: baseUrl + '/logos/Providence_Friars_logo.png',
    Purdue: baseUrl + '/logos/Purdue_Boilermakers_logo.png',
    Purdue_Fort_Wayne: `${baseUrl}/logos/Purdue_Fort_Wayne_Mastodons_logo.png`,
    Queens: `${baseUrl}/logos/Queens_Royals_primary_logo.png`,
    Quinnipiac: `${baseUrl}/logos/Quinnipiac_Bobcats_logo.png`,
    Radford: `${baseUrl}/logos/Radford_Highlanders_logo.png`,
    RhodeIsland: baseUrl + '/logos/Rhode_Island_Rams_logo.png',
    Rice: baseUrl + '/logos/Rice_Owls_logo.png',
    Richmond: baseUrl + '/logos/Richmond_Spiders_logo.png',
    Rider: `${baseUrl}/logos/Rider_Broncs.png`,
    Rio_Grande_Valley: `${baseUrl}/logos/Rio_Grande_Valley_Vaqueros_logo.png`,
    Robert_Morris: `${baseUrl}/logos/Robert_Morris_Colonials_logo.png`,
    Rutgers: baseUrl + '/logos/Rutgers_Scarlet_Knights_logo.png',
    Sacramento_State: baseUrl + '/logos/Sacramento_State_Hornets_logo.png',
    Sacred_Heart: `${baseUrl}/logos/Sacred_Heart_Pioneers_logo.png`,
    Saint_Francis: `${baseUrl}/logos/Saint_Francis_Red_Flash_logo.png`,
    SaintJosephs: baseUrl + '/logos/Saint_Josephs_Hawks_logo.png',
    SaintLouis: baseUrl + '/logos/Saint_Louis_Billikens_logo.png',
    Saint_Peters: `${baseUrl}/logos/Saint_Peters_Peacocks_logo.png`,
    Samford: baseUrl + '/logos/Samford_Bulldogs_logo.png',
    SamHoustonState: baseUrl + '/logos/SHSU_athletics_logo.png',
    San_Diego_State: baseUrl + '/logos/San_Diego_State_Aztecs_logo.png',
    SantaClara: baseUrl + '/logos/Santa_Clara_Broncos_logo.png',
    SFDons: baseUrl + '/logos/San_Francisco_Dons_logo.png',
    SFA: `${baseUrl}/logos/sfa_logo.png`,
    San_Jose: baseUrl + '/logos/San_Jose_State_Spartans_logo.png',
    Seattle: baseUrl + '/logos/Seattle_Redhawks_logo.png',
    SetonHall: baseUrl + '/logos/Seton_Hall_Pirates_logo.png',
    Siena: `${baseUrl}/logos/Siena_Saints_logo.png`,
    SIU_E: `${baseUrl}/logos/siue_cougars_logo.png`,
    SMU: baseUrl + '/logos/SMU_Mustang_logo.png',
    South_Alabama: baseUrl + '/logos/South_Alabama_Jaguars_logo.png',
    South_Carolina: baseUrl + '/logos/South_Carolina_Gamecocks_logo.png',
    South_Carolina_State: `${baseUrl}/logos/South_Carolina_State_Bulldogs_logo.png`,
    South_Dakota: baseUrl + '/logos/South_Dakota_Coyotes_logo.png',
    South_Dakota_State:
        baseUrl + '/logos/South_Dakota_State_Jackrabbits_logo.png',
    South_Florida: baseUrl + '/logos/South_Florida_Bulls_logo.png',
    Southeast_Missouri: `${baseUrl}/logos/semo_logo.png`,
    Southeastern_Louisiana: `${baseUrl}/logos/Southeastern_Louisiana_Lions_logo.png`,
    Southern: baseUrl + '/logos/Southern_Jaguars_logo.png',
    Southern_Illinois: baseUrl + '/logos/southern_illinois_salukis_logo.png',
    Southern_Indiana: `${baseUrl}/logos/Southern_Indiana_Screaming_Eagles_logo.png`,
    Southern_Miss: baseUrl + '/logos/Southern_Miss_Athletics_logo.png',
    Southern_Utah: `${baseUrl}/logos/Southern_Utah_Thunderbirds_logo.png`,
    Stanford: baseUrl + '/logos/Stanford_Cardinal_logo.png',
    St_Bonaventure: baseUrl + '/logos/St._Bonaventure_Bonnies_logo.png',
    St_Francis: `${baseUrl}/logos/st_Francis_Brooklyn_Terriers_logo.png`,
    St_Marys: baseUrl + "/logos/Saint_Mary's_College_Gaels_logo.png",
    St_Thomas: `${baseUrl}/logos/st_thomas_tommies_logo.png`,
    StJohns: baseUrl + '/logos/St_Johns_Red_Storm_logo.png',
    Stetson: `${baseUrl}/logos/Stetson_Hatters_logo.png`,
    Stonehill: `${baseUrl}/logos/Stonehill_Skyhawks_logo.png`,
    Stony_Brook: `${baseUrl}/logos/Stony_Brook_Seawolves_logo.png`,
    Syracuse: baseUrl + '/logos/Syracuse_Orange_logo.png',
    Tarleton: `${baseUrl}/logos/Tarleton_Ton_logo.png`,
    TCU: baseUrl + '/logos/TCU_Horned_Frogs_logo.png',
    Temple: baseUrl + '/logos/Temple_Owls_logo.png',
    Tennessee: baseUrl + '/logos/Tennessee_Volunteers_logo.png',
    Tennessee_State: `${baseUrl}/logos/Tennessee_State_logo.png`,
    Tennessee_Tech: `${baseUrl}/logos/Tennessee_Tech_Golden_Eagles_logo.png`,
    TAMU: baseUrl + '/logos/Texas_A&M_University_logo.png',
    Texas_AM_Corpus: `${baseUrl}/logos/tamu_Corpus_Christi_Islanders_logo.png`,
    Texas_AM_Commerce: `${baseUrl}/logos/Texas_A&M_Commerce_Lions_logo.png`,
    Texas: baseUrl + '/logos/Texas_Longhorns_logo.png',
    Texas_Tech: baseUrl + '/logos/Texas_Tech_Athletics_logo.png',
    Texas_State: baseUrl + '/logos/Texas_State_Bobcats_logo.png',
    Texas_Southern: baseUrl + '/logos/Texas_Southern_Tigers_logo.png',
    Toledo: baseUrl + '/logos/Toledo_Rockets_logo.png',
    Towson: `${baseUrl}/logos/Towson_Tigers_logo.png`,
    Troy: baseUrl + '/logos/Troy_Trojans_logo.png',
    Tulane: baseUrl + '/logos/Tulane_Green_Wave_logo.png',
    Tulsa: baseUrl + '/logos/Tulsa_alternate_logo.webp',
    UAB: baseUrl + '/logos/UAB_Blazers_logo.png',
    UCF: baseUrl + '/logos/UCF_Knights_logo.png',
    UC_Davis: baseUrl + '/logos/UC_Davis_Aggies_logo.png',
    UC_Irvine: baseUrl + '/logos/UC_Irvine_Anteaters_logo.png',
    UC_Riverside: `${baseUrl}/logos/UC_Riverside_Highlanders_logo.png`,
    UC_San_Diego: baseUrl + '/logos/UC_San_Diego.png',
    UC_Santa_Barbara: `${baseUrl}/logos/UC_Santa_Barbara_Gauchos_logo.png`,
    U_San_Diego: baseUrl + '/logos/San_Diego_Toreros_logo.png',
    UCLA: baseUrl + '/logos/UCLA_Bruins_logo.png',
    UIC: `${baseUrl}/logos/UIC_Flames_logo.png`,
    UMASS: baseUrl + '/logos/UMass_Amherst_Athletics_logo.png',
    UMASS_Amherst: `${baseUrl}/logos/UMass_Amherst_Athletics_logo.png`,
    UMASS_Lowell: `${baseUrl}/logos/UMass_Lowell_River_Hawks_logo.png`,
    UMBC: baseUrl + '/logos/UMBC_Retrievers_logo.png',
    UNC_Asheville: `${baseUrl}/logos/UNC_Asheville_Bulldogs_logo.png`,
    UNC_Wilmington: `${baseUrl}/logos/UNC_Wilmington_Seahawks_logo.png`,
    UNCG: `${baseUrl}/logos/UNCG_Spartans_logo.png`,
    UNLV: baseUrl + '/logos/UNLV_Rebels_wordmark.png',
    USC: baseUrl + '/logos/USC_Trojans_logo.png',
    USC_Upstate: `${baseUrl}/logos/USC_Upstate_Spartans_logo.png`,
    UT_Arlington: `${baseUrl}/logos/UT_Arlington_Mavericks_logo.png`,
    UT_Martin: `${baseUrl}/logos/UT_Martin_Skyhawks_logo.png`,
    Utah_State: baseUrl + '/logos/Utah_State_Aggies_logo.png',
    Utah: baseUrl + '/logos/Utah_Utes_logo.png',
    Utah_Tech: `${baseUrl}/logos/Utah_Tech_Trailblazers_logo.png`,
    Utah_Valley: `${baseUrl}/logos/Utah_Valley_Wolverines_logo.png`,
    UTEP: baseUrl + '/logos/UTEP_Miners_logo.png',
    UTSA: baseUrl + '/logos/UTSA_Roadrunners_logo.png',
    Valparaiso: `${baseUrl}/logos/Valparaiso_Crusaders_logo.png`,
    Vanderbilt: baseUrl + '/logos/Vanderbilt.png',
    VCU: baseUrl + '/logos/VCU_Rams_logo.png',
    Vermont: `${baseUrl}/logos/Vermont_Catamounts_logo.png`,
    Villanova: baseUrl + '/logos/Villanova_Wildcats_logo.png',
    Virginia: baseUrl + '/logos/Virginia_Cavaliers_logo.png',
    Virginia_Tech: baseUrl + '/logos/Virginia_Tech_Hokies_logo.png',
    VMI: baseUrl + '/logos/VMI_Keydets_logo.png',
    Wagner: `${baseUrl}/logos/Wagner_Seahawks_logo.png`,
    Wake_Forest: baseUrl + '/logos/Wake_Forest_University_Athletic_logo.png',
    Washington: baseUrl + '/logos/Washington_Huskies_logo.png',
    Washington_State: baseUrl + '/logos/Washington_State_Cougars_logo.png',
    Weber_State: baseUrl + '/logos/Weber_State_Wildcats_logo.png',
    West_Georgia: `${baseUrl}/logos/West_Georgia_Wolves_logo.png`,
    West_Virginia: baseUrl + '/logos/West_Virginia_Mountaineers_logo.png',
    Western_Carolina: baseUrl + '/logos/Western_Carolina_Catamounts_logo.png',
    Western_Illinois: baseUrl + '/logos/Western_Illinois_Leathernecks_logo.png',
    Western_Kentucky: baseUrl + '/logos/WKU_Athletics_logo.png',
    Western_Michigan: baseUrl + '/logos/Western_Michigan.png',
    Wichita_State: baseUrl + '/logos/Wichita_State_Shockers_logo.png',
    William_and_Mary: `${baseUrl}/logos/William_and_Mary_Tribe_logo.png`,
    Winthrop: `${baseUrl}/logos/Winthrop_Eagles_logo.png`,
    Wisconsin: baseUrl + '/logos/Wisconsin_Badgers_logo.png',
    Wofford: baseUrl + '/logos/Wofford_Terriers_logo.png',
    Wright_State: `${baseUrl}/logos/Wright_State_Raiders_logo.png`,
    Wyoming: baseUrl + '/logos/Wyoming_Athletics_logo.png',
    Xavier: baseUrl + '/logos/xavier_logo.png',
    Yale: baseUrl + '/logos/Yale_Bulldogs.png',
    Youngstown_State: baseUrl + '/logos/Youngstown_State.png',

    Unknown: baseUrl + '/logos/unknown1.png',
    SEA_Supersonics: baseUrl + '/logos/supersonics.png',
    SEA_Seahawks: baseUrl + '/logos/SEA_Seahawks.png',
    BUF_Bills: baseUrl + '/logos/BUF_Bills.png',
    MIA_Dolphins: baseUrl + '/logos/MIA_Dolphins.png',
    NE_Patriots: baseUrl + '/logos/NE_Patriots.png',
    NY_Jets: baseUrl + '/logos/NY_Jets.png',
    BAL_Ravens: baseUrl + '/logos/BAL_Ravens.png',
    CIN_Bengals: baseUrl + '/logos/CIN_Bengals.png',
    CLE_Browns: baseUrl + '/logos/CLE_Browns.png',
    PIT_Steelers: baseUrl + '/logos/PIT_Steelers.png',
    HOU_Texans: baseUrl + '/logos/HOU_Texans.png',
    IND_Colts: baseUrl + '/logos/IND_Colts.png',
    JAX_Jaguars: baseUrl + '/logos/JAX_Jaguars.png',
    TEN_Titans: baseUrl + '/logos/Tennessee_Titans_logo.png',
    DEN_Broncos: baseUrl + '/logos/DEN_Broncos.png',
    KC_Chiefs: baseUrl + '/logos/KC_Chiefs.png',
    LV_Raiders: baseUrl + '/logos/LV_Raiders.png',
    LA_Chargers: baseUrl + '/logos/LA_Chargers.png',
    DAL_Cowboys: baseUrl + '/logos/DAL_Cowboys.png',
    NY_Giants: baseUrl + '/logos/NY_Giants.png',
    PHI_Eagles: baseUrl + '/logos/PHI_Eagles.png',
    WFT: baseUrl + '/logos/WFT.png',
    WAS_Commies: baseUrl + '/logos/Washington_Commanders_logo.png',
    CHI_Bears: baseUrl + '/logos/CHI_Bears.png',
    DET_Lions: baseUrl + '/logos/DET_Lions.png',
    GB_Packers: baseUrl + '/logos/GB_Packers.png',
    MN_Vikings: baseUrl + '/logos/MN_Vikings.png',
    ATL_Falcons: baseUrl + '/logos/ATL_Falcons.png',
    CAR_Panthers: baseUrl + '/logos/CAR_Panthers.png',
    NO_Saints: baseUrl + '/logos/NO_Saints.png',
    TB_Buccaneers: baseUrl + '/logos/TB_Buccaneers.png',
    ARI_Cardinals: baseUrl + '/logos/ARI_Cardinals.png',
    LA_Rams: baseUrl + '/logos/LA_Rams.png',
    SF_49ers: baseUrl + '/logos/SF_49ers.png',
    VAN_Sealions: baseUrl + '/logos/VAN_Sealions_2.png',
    VGK: baseUrl + '/logos/',
    BOS_Celtics: baseUrl + '/logos/BOS_Celtics.png',
    BRK_Nets: baseUrl + '/logos/BRK_Nets.png',
    NY_Knicks: baseUrl + '/logos/NY_Knicks.png',
    PHI_76ers: baseUrl + '/logos/PHI_76ers.png',
    TOR_Raptors: baseUrl + '/logos/TOR_Raptors.png',
    CHI_Bulls: baseUrl + '/logos/CHI_Bulls.png',
    CLE_Cavaliers: baseUrl + '/logos/CLE_Cavaliers.png',
    DET_Pistons: baseUrl + '/logos/DET_Pistons.png',
    IND_Pacers: baseUrl + '/logos/IND_Pacers.png',
    MIL_Bucks: baseUrl + '/logos/MIL_Bucks.png',
    ATL_Hawks: baseUrl + '/logos/ATL_Hawks.png',
    CHA_Hornets: baseUrl + '/logos/Charlotte_Hornets_Logo_1989.png',
    MIA_Heat: baseUrl + '/logos/MIA_Heat.png',
    ORL_Magic: baseUrl + '/logos/ORL_Magic.png',
    WAS_Wizards: baseUrl + '/logos/WAS_Wizards.png',
    DEN_Nuggets: baseUrl + '/logos/DEN_Nuggets.png',
    MIN_Timberwolves: baseUrl + '/logos/MIN_Timberwolves.png',
    OKC_Thunder: baseUrl + '/logos/OKC_Thunder.png',
    POR_Trailblazers: baseUrl + '/logos/POR_Trailblazers.png',
    UTA_Jazz: baseUrl + '/logos/UTA_Jazz.png',
    GS_Warriors: baseUrl + '/logos/GS_Warriors.png',
    LA_Clippers: baseUrl + '/logos/LA_Clippers.png',
    LA_Lakers: baseUrl + '/logos/LA_Lakers.png',
    PHO_Suns: baseUrl + '/logos/PHO_Suns.png',
    SAC_Kings: baseUrl + '/logos/SAC_Kings.png',
    DAL_Mavericks: baseUrl + '/logos/DAL_Mavericks.png',
    HOU_Rockets: baseUrl + '/logos/HOU_Rockets.png',
    MEM_Grizzlies: baseUrl + '/logos/MEM_Grizzlies.png',
    NO_Pelicans: baseUrl + '/logos/NO_Pelicans.png',
    SA_Spurs: baseUrl + '/logos/SA_Spurs.png',
    SD_Clippers: `${baseUrl}/logos/SDClippers2.png`
};

export const retro_logos = {
    Abilene_Christian: `${baseUrl}/logos/Abilene_Christian_Wildcats_logo.png`,
    Air_Force: baseUrl + '/logos/usaf_retro_logo.png',
    Akron_Zips: baseUrl + '/logos/akron_retro_logo.png',
    Alabama: baseUrl + '/logos/alabama_retro_logo.png',
    Alabama_AM: baseUrl + '/logos/Alabama_A&M_Bulldogs_logo.png',
    Alabama_State: baseUrl + '/logos/Alabama_State_logo.png',
    Albany: `${baseUrl}/logos/Albany_Great_Danes_logo.png`,
    Alcorn_State: baseUrl + '/logos/Alcorn_State_athletics_logo.png',
    American: `${baseUrl}/logos/American_Eagles_logo.png`,
    AmericanSamoa: `${baseUrl}/logos/american_samoa_athletics_logo.png`,
    App_State: baseUrl + '/logos/app_state_retro_logo.png',
    Arizona_State: baseUrl + '/logos/asu_retro_logo.webp',
    Arizona: baseUrl + '/logos/arizona_retro_logo.png',
    Arkansas: baseUrl + '/logos/arkansas_retro_logo.webp',
    Arkansas_State: baseUrl + '/logos/arkansas_state_retro_logo.png',
    Arkansas_Pine_Bluff:
        baseUrl + '/logos/Arkansas_Pine_Bluff_Golden_Lions_logo.png',
    Army: baseUrl + '/logos/army_retro_logo.png',
    Auburn: baseUrl + '/logos/auburn_retro_logo.png',
    Austin_Peay: `${baseUrl}/logos/Austin_Peay_Governors_logo.png`,
    Ball_State: baseUrl + '/logos/ball_state_retro_logo.png',
    Baylor: baseUrl + '/logos/baylor_bears_retro.png',
    Bellarmine: `${baseUrl}/logos/Bellarmine_Knights_logo.png`,
    Belmont: `${baseUrl}/logos/Belmont_Bruins_logo.png`,
    Bethune_Cookman: baseUrl + '/logos/Bethune_Cookman_Wildcats_logo.png',
    Binghamton: `${baseUrl}/logos/Binghamton_Bearcats_logo.png`,
    Boise_State: baseUrl + '/logos/boise_state_retro_logo.png',
    Boston_College: baseUrl + '/logos/boston_college_retro_logo.png',
    Boston: `${baseUrl}/logos/Boston_University_Terriers_logo.png`,
    Bowling_Green: baseUrl + '/logos/bowling_green_retro_logo.png',
    Bradley: `${baseUrl}/logos/Bradley_Braves_logo.png`,
    Brown: baseUrl + '/logos/Brown_Bears_Athletics_logo.png',
    Bryant: `${baseUrl}/logos/Bryant_Bulldogs_logo.png`,
    Bucknell: baseUrl + '/logos/Bucknell_Bison_logo.png',
    Buffalo: baseUrl + '/logos/buffalo_bulls_retro_logo.png',
    Butler: baseUrl + '/logos/Butler_Bulldogs_logo.png',
    BYU: baseUrl + '/logos/byu_retro_logo.png',
    California: baseUrl + '/logos/cal_retro_logo_2.png',
    Cal_Poly: baseUrl + '/logos/Cal_Poly_Mustangs_logo.png',
    Cal_State_Bakersfield: `${baseUrl}/logos/Cal_State_Bakersfield_Roadrunners_logo.png`,
    Cal_State_Fullerton: `${baseUrl}/logos/Cal_State_Fullerton_Titans_logo.png`,
    Cal_State_Northridge: `${baseUrl}/logos/CSUN_Matadors_logo.png`,
    California_Baptist: `${baseUrl}/logos/California_Baptist_logo.png`,
    Campbell: `${baseUrl}/logos/Campbell_Fighting_Camels_logo.png`,
    Canisius: `${baseUrl}/logos/Canisius_Golden_Griffins.png`,
    Central_Arkansas: `${baseUrl}/logos/Central_Arkansas_Athletics_logo.png`,
    Central_Connecticut: `${baseUrl}/logos/Central_Connecticut_Blue_Devils_logo.png`,
    Central_Michigan: baseUrl + '/logos/Central_Michigan_Chippewas_logo.png',
    Chaminade: `${baseUrl}/logos/Chaminade_logo.png`,
    Charleston: `${baseUrl}/logos/Charleston_Cougars_logo.png`,
    Charleston_Southern: `${baseUrl}/logos/Charleston_Southern_Buccaneers_logo.png`,
    Charlotte: baseUrl + '/logos/uncc_retro_logo.png',
    Chattanooga: baseUrl + '/logos/Chattanooga_Mocs_logo.png',
    Chicago_State: `${baseUrl}/logos/Chicago_State_Cougars_logo.png`,
    Cincinnati: baseUrl + '/logos/cincinnati_bearcats_retro_logo.webp',
    Citadel: baseUrl + '/logos/Citadel_Bulldogs_logo.png',
    Clemson: baseUrl + '/logos/clemson_retro_logo.png',
    Cleveland_State: `${baseUrl}/logos/Cleveland_State_Vikings_logo.png`,
    Coastal_Carolina: baseUrl + '/logos/coastal_carolina_retro_logo.png',
    Colgate: baseUrl + '/logos/Colgate_Raiders_logo.png',
    Colorado: baseUrl + '/logos/colorado_retro_3.png',
    Colorado_State: baseUrl + '/logos/colorado_state_retro_logo.png',
    Columbia: baseUrl + '/logos/Columbia_Lions_logo.png',
    Connecticut: baseUrl + '/logos/uconn_retro_logo.png',
    Coppin_State: `${baseUrl}/logos/Coppin_State_Eagles_logo.png`,
    Cornell: baseUrl + '/logos/Cornell_Big_Red_logo.png',
    Creighton: baseUrl + '/logos/Creighton_Bluejays_logo.png',
    Dartmouth: baseUrl + '/logos/Dartmouth_College_Big_Green_logo.png',
    Davidson: baseUrl + '/logos/Davidson_Wildcats_logo.png',
    Dayton: baseUrl + '/logos/dayton_flyers_logo.png',
    Delaware: `${baseUrl}/logos/Delaware_Blue_Hens_Logo.png`,
    Delaware_State: `${baseUrl}/logos/Delaware_State_Hornets_logo.png`,
    Denver: `${baseUrl}/logos/Denver_Pioneers_Athletics_logo.png`,
    DePaul: baseUrl + '/logos/DePaul_Blue_Demons_logo.png',
    Detroit_Mercy: `${baseUrl}/logos/Detroit_Titans_logo.png`,
    Drake: `${baseUrl}/logos/Drake_Bulldogs_logo.png`,
    Drexel: `${baseUrl}/logos/Drexel_Dragons_logo.png`,
    Duke: baseUrl + '/logos/duke_retro_logo.png',
    Duquesne: baseUrl + '/logos/Duquesne_Dukes_logo.png',
    East_Carolina: baseUrl + '/logos/ecu_retro_logo.png',
    ETSU: baseUrl + '/logos/East_Tennessee_State_Buccaneers_logo.png',
    Eastern_Illinois: `${baseUrl}/logos/Eastern_Illinois_Panthers_logo.png`,
    Eastern_Kentucky: `${baseUrl}/logos/Eastern_Kentucky_Colonels_logo.png`,
    Eastern_Michigan: baseUrl + '/logos/Eastern_Michigan_Eagles_logo.png',
    Eastern_Washington: baseUrl + '/logos/Eastern_Washington_Eagles_logo.png',
    Elon: `${baseUrl}/logos/Elon_Phoenix_logo.png`,
    Evansville: baseUrl + '/logos/Evansville_Purple_Aces_logo.png',
    Fairfield: `${baseUrl}/logos/Fairfield_Stags_logo.png`,
    Fairleigh_Dickinson: `${baseUrl}/logos/FDU_Knights_Logo.png`,
    FAMU: baseUrl + '/logos/FAMU_Rattler.png',
    FGCU: baseUrl + '/logos/Florida_Gulf_Coast_Eagles_logo.png',
    FIU: baseUrl + '/logos/fiu_retro_logo.png',
    Florida_Atlantic: baseUrl + '/logos/fau_retro_logo.png',
    Florida: baseUrl + '/logos/florida_gators_retro_logo.png',
    Florida_State: baseUrl + '/logos/florida_state_retro_logo.png',
    Fordham: baseUrl + '/logos/Fordham_Rams_logo.png',
    Fresno_State: baseUrl + '/logos/fresno_state_retro_logo.png',
    Furman: baseUrl + '/logos/Furman_Paladins_logo.png',
    Gardner_Webb: `${baseUrl}/logos/Gardner_Webb_Bulldogs_Logo.png`,
    GeorgeMason: baseUrl + '/logos/George_Mason_Patriots_logo.png',
    Georgetown: baseUrl + '/logos/Georgetown_Hoyas_logo.png',
    GeorgeWashington: baseUrl + '/logos/George_Washington_Colonials_logo.png',
    Georgia: baseUrl + '/logos/georgia_retro_logo.png',
    Georgia_Southern: baseUrl + '/logos/georgia_southern_retro_logo.png',
    Georgia_State: baseUrl + '/logos/georgia_state_retro_logo.png',
    Georgia_Tech: baseUrl + '/logos/georgia_tech_retro_logo.png',
    Gonzaga: baseUrl + '/logos/Gonzaga_Bulldogs_logo.png',
    Grambling_State: baseUrl + '/logos/Grambling_State_Tigers_logo.png',
    Grand_Canyon: `${baseUrl}/logos/Grand_Canyon_Antelopes_logo.png`,
    Green_Bay: `${baseUrl}/logos/Green_Bay_Phoenix_logo.png`,
    Guam: `${baseUrl}/logos/Guam_logo.png`,
    Hampton: `${baseUrl}/logos/Hampton_Pirates_logo.png`,
    Hartford: `${baseUrl}/logos/Hartford_Hawks_logo.png`,
    Harvard: baseUrl + '/logos/Harvard_Crimson_logo.png',
    Hawaii: baseUrl + '/logos/hawaii_retro_logo.png',
    High_Point: `${baseUrl}/logos/High_Point_Panthers_logo.png`,
    Hofstra: `${baseUrl}/logos/Hofstra_Pride_logo.png`,
    Holy_Cross: baseUrl + '/logos/Holy_Cross_Crusaders_logo.png',
    Houston: baseUrl + '/logos/Houston_Cougars_primary_logo.png',
    Houston_Baptist: `${baseUrl}/logos/Houston_Baptist_Huskies_logo.png`,
    Howard: `${baseUrl}/logos/Howard_Bison_logo.png`,
    Idaho: baseUrl + '/logos/idaho_retro_logo.png',
    Idaho_State: baseUrl + '/logos/Idaho_State_Bengals_logo.png',
    Illinois: baseUrl + '/logos/illinois_retro_logo.png',
    Illinois_State: baseUrl + '/logos/Illinois_State_Athletics_logo.png',
    Incarnate_Word: `${baseUrl}/logos/Incarnate_Word_Cardinals_logo.png`,
    Indiana: baseUrl + '/logos/indiana_retro_logo.png',
    Indiana_State: baseUrl + '/logos/Indiana_State_Sycamores_logo.png',
    Iona: `${baseUrl}/logos/Iona_Gaels_logo.png`,
    Iowa: baseUrl + '/logos/iowa_retro_logo.png',
    Iowa_State: baseUrl + '/logos/iowa_state_retro_logo.png',
    IUPUI: `${baseUrl}/logos/IUPUI_Jaguars_logo.png`,
    JMU: baseUrl + '/logos/james_madison_retro_logo.png',
    Jacksonville: baseUrl + '/logos/Jacksonville_Dolphins_logo.png',
    JacksonvilleState: baseUrl + '/logos/jacksonville_state_retro_logo.png',
    Jackson_State: baseUrl + '/logos/Jackson_State_athletics_logo.png',
    Kansas: baseUrl + '/logos/kansas_retro_logo.png',
    Kansas_State: baseUrl + '/logos/kansas_state_retro_logo.png',
    Kansas_City_U: `${baseUrl}/logos/kansas_city_roos_logo.png`,
    KennesawState: baseUrl + '/logos/kennesaw_state_retro_logo.png',
    Kent_State: baseUrl + '/logos/Kent_State_athletic_logo.png',
    Kentucky: baseUrl + '/logos/kentucky_retro_logo.png',
    Lafayette: baseUrl + '/logos/Lafayette_Leopards_logo.png',
    Lamar: `${baseUrl}/logos/Lamar_Cardinals_logo.png`,
    LaSalle: baseUrl + '/logos/La_Salle_Explorers_logo.png',
    LeHigh: baseUrl + '/logos/LehighMountainHawks.png',
    Lemoyne: `${baseUrl}/logos/Le_Moyne_Dolphins_logo.png`,
    Liberty: baseUrl + '/logos/liberty_retro_logo.png',
    Lindenwood: `${baseUrl}/logos/Lindenwood_Lions_logo.png`,
    Lipscomb: `${baseUrl}/logos/lipscomb_bisons.png`,
    Little_Rock: `${baseUrl}/logos/Little_Rock_Trojans_logo.png`,
    Long_Beach: `${baseUrl}/logos/Long_Beach_State_Athletics_logo.png`,
    Long_Island: `${baseUrl}/logos/LIU_Sharks_logo.png`,
    Longwood: `${baseUrl}/logos/Longwood_Lancers_logo.png`,
    Louisiana_Tech: baseUrl + '/logos/louisiana_tech_retro_logo.png',
    Louisiana: baseUrl + '/logos/louisiana_retro_logo.png',
    Louisiana_Monroe: baseUrl + '/logos/louisiana_monroe_retro_logo.png',
    Louisville: baseUrl + '/logos/louisville_retro_logo.png',
    LoyolaC: baseUrl + '/logos/Loyola_Ramblers_logo.png',
    LoyolaM: baseUrl + '/logos/LMU_Lions_logo.png',
    Loyola_Maryland: `${baseUrl}/logos/Loyola_Greyhounds_logo.png`,
    LSU: baseUrl + '/logos/lsu_tigers_retro.png',
    Maine: `${baseUrl}/logos/Maine_Black_Bears_logo.png`,
    Manhattan: `${baseUrl}/logos/Manhattan_Jaspers_logo.png`,
    Marist: `${baseUrl}/logos/Marist_Red_Foxes_logo.png`,
    Marquette: baseUrl + '/logos/Marquette_Golden_Eagles_logo.png',
    Marshall: baseUrl + '/logos/marshall_retro_logo.png',
    Maryland_East: `${baseUrl}/logos/Maryland_Eastern_Shore_Hawks_logo.png`,
    Maryland: baseUrl + '/logos/maryland_retro_logo.png',
    McNeese_State: `${baseUrl}/logos/McNeese_State_Athletics_logo.png`,
    Memphis: baseUrl + '/logos/memphis_retro_logo.png',
    Mercer: baseUrl + '/logos/Mercer_Bears_logo.png',
    Mercyhurst: `${baseUrl}/logos/Mercyhurst_logo.png`,
    Merrimack: `${baseUrl}/logos/Merrimack_Warriors.png`,
    Miami: baseUrl + '/logos/miami_hurricanes_retro_logo.png',
    Miami_OH: baseUrl + '/logos/miami_redhawks_retro_logo.png',
    Michigan_State: baseUrl + '/logos/michigan_state_retro_logo.png',
    Michigan: baseUrl + '/logos/michigan_retro_logo.png',
    Middle_Tennessee: baseUrl + '/logos/mtsu_retro_logo.png',
    Milwaukee: `${baseUrl}/logos/Milwaukee_Panthers_logo.png`,
    Minnesota: baseUrl + '/logos/minnesota_retro_logo.png',
    Mississippi_State: baseUrl + '/logos/mississippi_state_retro_logo.png',
    Missouri: baseUrl + '/logos/missouri_retro_logo.png',
    Missouri_State: baseUrl + '/logos/Missouri_State_Athletics_logo.png',
    Monmouth: `${baseUrl}/logos/Monmouth_Hawks_logo.png`,
    Montana: baseUrl + '/logos/Montana_Griz_logo.png',
    Montana_State: baseUrl + '/logos/Montana_State_Bobcats_logo.png',
    Morehead: `${baseUrl}/logos/Morehead_State_Eagles_logo.png`,
    Morgan_State: `${baseUrl}/logos/Morgan_State_Bears_logo.png`,
    Mount_St_Marys: `${baseUrl}/logos/Mount_St_Marys_Mountaineers_logo.png`,
    Murray_State: baseUrl + '/logos/Murray_State_Racers_logo.png',
    Mississippi_Valley: baseUrl + '/logos/MVSU_logo.png',
    Northern_Arizona: baseUrl + '/logos/NAU_logo.png',
    Navy: baseUrl + '/logos/navy_retro_logo.png',
    NC_State: baseUrl + '/logos/nc_state_retro_2.png',
    Nebraska: baseUrl + '/logos/nebraska_retro_logo.png',
    Nebraska_Omaha: baseUrl + '/logos/Omaha_Mavericks_logo.png',
    Nevada: baseUrl + '/logos/nevada_retro_logo.png',
    New_Hampshire: `${baseUrl}/logos/New_Hampshire_Wildcats_logo.png`,
    New_Mexico: baseUrl + '/logos/new_mexico_retro_logo.png',
    New_Mexico_State: baseUrl + '/logos/new_mexico_state_retro_logo.png',
    New_Orleans: `${baseUrl}/logos/New_Orleans_Privateers_logo.png`,
    Niagara: `${baseUrl}/logos/Niagara_Purple_Eagles.png`,
    Nicholls_State: `${baseUrl}/logos/Nicholls_State_Colonels_logo.png`,
    NJIT: `${baseUrl}/logos/NJIT_Highlanders_logo.png`,
    Norfolk_State: `${baseUrl}/logos/Norfork_State_Spartans_logo.png`,
    North_Alabama: `${baseUrl}/logos/North_Alabama_Lions_logo.png`,
    North_Carolina: baseUrl + '/logos/unc_retro_logo.png',
    North_Carolina_AT: `${baseUrl}/logos/North_Carolina_A&T_Aggies_logo.png`,
    North_Carolina_Central: `${baseUrl}/logos/NCCU_Eagles_logo.png`,
    North_Dakota: baseUrl + '/logos/North_Dakota_Fighting_Hawks_logo.png',
    North_Dakota_State: baseUrl + '/logos/North_Dakota_State_Bison_logo.png',
    North_Florida: `${baseUrl}/logos/UNF_Ospreys_logo.png`,
    North_Texas: baseUrl + '/logos/north_texas_retro_logo.png',
    Northeastern: `${baseUrl}/logos/Northeastern_Huskies_logo.png`,
    Northern_Colorado: baseUrl + '/logos/Northern_Colorado_Bears_logo.png',
    Northern_Iowa: baseUrl + '/logos/Northern_Iowa_Panthers_logo.png',
    Northern_Kentucky: `${baseUrl}/logos/nku_retro_logo.png`,
    NIU: baseUrl + '/logos/niu_retro_logo.png',
    Northwestern: baseUrl + '/logos/northwestern_retro_logo.gif',
    Northwestern_State: `${baseUrl}/logos/Northwestern_State_Demons_logo.png`,
    Notre_Dame: baseUrl + '/logos/notre_dame_retro_logo.png',
    Oakland: `${baseUrl}/logos/Oakland_Golden_Grizzlies_logo.png`,
    Ohio: baseUrl + '/logos/ohio_bobcats_retro_logo.png',
    Ohio_State: baseUrl + '/logos/ohio_state_retro_logo.png',
    Oklahoma: baseUrl + '/logos/Oklahoma_retro_logo.png',
    Oklahoma_State: baseUrl + '/logos/Oklahoma_state_retro_logo.png',
    Old_Dominion: baseUrl + '/logos/old_dominion_retro_logo.png',
    Ole_Miss: baseUrl + '/logos/ole_miss_retro_logo.png',
    Oral_Roberts: `${baseUrl}/logos/Oral_Roberts_Golden_Eagles_logo.png`,
    Oregon: baseUrl + '/logos/orego_retro_logo.png',
    Oregon_State: baseUrl + '/logos/oregon_state_retro_2.png',
    Pacific: baseUrl + '/logos/Pacific_Tigers_logo.png',
    Pennsylvania: baseUrl + '/logos/Penn_Quakers_logo.png',
    Penn_State: baseUrl + '/logos/penn_state_retro_logo.png',
    Pepperdine: baseUrl + '/logos/Pepperdine_Waves_logo.png',
    Pitt: baseUrl + '/logos/pittsburgh_retro_logo.png',
    Portland: baseUrl + '/logos/Portland_Pilots_logo.png',
    Portland_State: baseUrl + '/logos/Portland_State_Vikings_logo.png',
    Prairie_View: baseUrl + '/logos/Prairie_View_A&M_Panthers_logo.png',
    Presbyterian_College: `${baseUrl}/logos/Presbyterian_College_logo.png`,
    Princeton: baseUrl + '/logos/Princeton_Tigers_logo.png',
    Providence: baseUrl + '/logos/Providence_Friars_logo.png',
    Purdue: baseUrl + '/logos/purdue_retro_logo.png',
    Purdue_Fort_Wayne: `${baseUrl}/logos/Purdue_Fort_Wayne_Mastodons_logo.png`,
    Queens: `${baseUrl}/logos/Queens_Royals_primary_logo.png`,
    Quinnipiac: `${baseUrl}/logos/Quinnipiac_Bobcats_logo.png`,
    Radford: `${baseUrl}/logos/Radford_Highlanders_logo.png`,
    RhodeIsland: baseUrl + '/logos/Rhode_Island_Rams_logo.png',
    Rice: baseUrl + '/logos/rice_retro_2.png',
    Richmond: baseUrl + '/logos/Richmond_Spiders_logo.png',
    Rider: `${baseUrl}/logos/Rider_Broncs.png`,
    Rio_Grande_Valley: `${baseUrl}/logos/Rio_Grande_Valley_Vaqueros_logo.png`,
    Robert_Morris: `${baseUrl}/logos/Robert_Morris_Colonials_logo.png`,
    Rutgers: baseUrl + '/logos/rutgers_retro_logo.png',
    Sacramento_State: baseUrl + '/logos/Sacramento_State_Hornets_logo.png',
    Sacred_Heart: `${baseUrl}/logos/Sacred_Heart_Pioneers_logo.png`,
    Saint_Francis: `${baseUrl}/logos/Saint_Francis_Red_Flash_logo.png`,
    SaintJosephs: baseUrl + '/logos/Saint_Josephs_Hawks_logo.png',
    SaintLouis: baseUrl + '/logos/Saint_Louis_Billikens_logo.png',
    Saint_Peters: `${baseUrl}/logos/Saint_Peters_Peacocks_logo.png`,
    Samford: baseUrl + '/logos/Samford_Bulldogs_logo.png',
    SamHoustonState: baseUrl + '/logos/sam_houston_state_logo.png',
    San_Diego_State: baseUrl + '/logos/sdsu_retro_2.png',
    SantaClara: baseUrl + '/logos/Santa_Clara_Broncos_logo.png',
    SFDons: baseUrl + '/logos/San_Francisco_Dons_logo.png',
    SFA: `${baseUrl}/logos/sfa_logo.png`,
    San_Jose: baseUrl + '/logos/sjsu_retro_2.png',
    Seattle: baseUrl + '/logos/Seattle_Redhawks_logo.png',
    SetonHall: baseUrl + '/logos/Seton_Hall_Pirates_logo.png',
    Siena: `${baseUrl}/logos/Siena_Saints_logo.png`,
    SIU_E: `${baseUrl}/logos/siue_cougars_logo.png`,
    SMU: baseUrl + '/logos/smu_retro_logo.png',
    South_Alabama: baseUrl + '/logos/south_alabama_retro_logo.png',
    South_Carolina: baseUrl + '/logos/south_carolina_retro_logo.png',
    South_Carolina_State: `${baseUrl}/logos/South_Carolina_State_Bulldogs_logo.png`,
    South_Dakota: baseUrl + '/logos/South_Dakota_Coyotes_logo.png',
    South_Dakota_State: baseUrl + '/logos/south_dakota_state_retro_logo.png',
    South_Florida: baseUrl + '/logos/usf_retro_logo.png',
    Southeast_Missouri: `${baseUrl}/logos/semo_logo.png`,
    Southeastern_Louisiana: `${baseUrl}/logos/Southeastern_Louisiana_Lions_logo.png`,
    Southern: baseUrl + '/logos/Southern_Jaguars_logo.png',
    Southern_Illinois: baseUrl + '/logos/southern_illinois_salukis_logo.png',
    Southern_Indiana: `${baseUrl}/logos/Southern_Indiana_Screaming_Eagles_logo.png`,
    Southern_Miss: baseUrl + '/logos/southern_miss_retro_logo.png',
    Southern_Utah: `${baseUrl}/logos/Southern_Utah_Thunderbirds_logo.png`,
    Stanford: baseUrl + '/logos/stanford_retro_logo.png',
    St_Bonaventure: baseUrl + '/logos/St._Bonaventure_Bonnies_logo.png',
    St_Francis: `${baseUrl}/logos/st_Francis_Brooklyn_Terriers_logo.png`,
    St_Marys: baseUrl + "/logos/Saint_Mary's_College_Gaels_logo.png",
    St_Thomas: `${baseUrl}/logos/st_thomas_tommies_logo.png`,
    StJohns: baseUrl + '/logos/St_Johns_Red_Storm_logo.png',
    Stetson: `${baseUrl}/logos/Stetson_Hatters_logo.png`,
    Stonehill: `${baseUrl}/logos/Stonehill_Skyhawks_logo.png`,
    Stony_Brook: `${baseUrl}/logos/Stony_Brook_Seawolves_logo.png`,
    Syracuse: baseUrl + '/logos/syracuse_retro_logo.gif',
    Tarleton: `${baseUrl}/logos/Tarleton_Ton_logo.png`,
    TCU: baseUrl + '/logos/tcu_retro_logo.png',
    Temple: baseUrl + '/logos/temple_retro_logo.png',
    Tennessee: baseUrl + '/logos/tennessee_vols_retro_logo.png',
    Tennessee_State: `${baseUrl}/logos/Tennessee_State_logo.png`,
    Tennessee_Tech: `${baseUrl}/logos/Tennessee_Tech_Golden_Eagles_logo.png`,
    TAMU: baseUrl + '/logos/texas_a&m_retro_logo.png',
    Texas_AM_Corpus: `${baseUrl}/logos/tamu_Corpus_Christi_Islanders_logo.png`,
    Texas_AM_Commerce: `${baseUrl}/logos/Texas_A&M_Commerce_Lions_logo.png`,
    Texas: baseUrl + '/logos/Texas_retro_logo.png',
    Texas_Tech: baseUrl + '/logos/Texas_Tech_retro_logo.png',
    Texas_State: baseUrl + '/logos/texas_state_retro_logo.png',
    Texas_Southern: baseUrl + '/logos/Texas_Southern_Tigers_logo.png',
    Toledo: baseUrl + '/logos/toledo_retro_logo.png',
    Towson: `${baseUrl}/logos/Towson_Tigers_logo.png`,
    Troy: baseUrl + '/logos/troy_retro_logo.png',
    Tulane: baseUrl + '/logos/tulane_retro_logo.png',
    Tulsa: baseUrl + '/logos/tulsa_retro_logo_2.png',
    UAB: baseUrl + '/logos/uab_retro_logo.png',
    UCF: baseUrl + '/logos/ucf_retro_logo.png',
    UC_Davis: baseUrl + '/logos/UC_Davis_Aggies_logo.png',
    UC_Irvine: baseUrl + '/logos/UC_Irvine_Anteaters_logo.png',
    UC_Riverside: `${baseUrl}/logos/UC_Riverside_Highlanders_logo.png`,
    UC_San_Diego: baseUrl + '/logos/UC_San_Diego.png',
    UC_Santa_Barbara: `${baseUrl}/logos/UC_Santa_Barbara_Gauchos_logo.png`,
    U_San_Diego: baseUrl + '/logos/San_Diego_Toreros_logo.png',
    UCLA: baseUrl + '/logos/ucla_retro_logo.png',
    UIC: `${baseUrl}/logos/UIC_Flames_logo.png`,
    UMASS: baseUrl + '/logos/umass_retro_logo.gif',
    UMASS_Amherst: `${baseUrl}/logos/UMass_Amherst_Athletics_logo.png`,
    UMASS_Lowell: `${baseUrl}/logos/UMass_Lowell_River_Hawks_logo.png`,
    UMBC: baseUrl + '/logos/UMBC_Retrievers_logo.png',
    UNC_Asheville: `${baseUrl}/logos/UNC_Asheville_Bulldogs_logo.png`,
    UNC_Wilmington: `${baseUrl}/logos/UNC_Wilmington_Seahawks_logo.png`,
    UNCG: `${baseUrl}/logos/UNCG_Spartans_logo.png`,
    UNLV: baseUrl + '/logos/unlv_retro_logo.png',
    USC: baseUrl + '/logos/usc_retro_2.png',
    USC_Upstate: `${baseUrl}/logos/USC_Upstate_Spartans_logo.png`,
    UT_Arlington: `${baseUrl}/logos/UT_Arlington_Mavericks_logo.png`,
    UT_Martin: `${baseUrl}/logos/UT_Martin_Skyhawks_logo.png`,
    Utah_State: baseUrl + '/logos/utah_state_retro_logo.png',
    Utah: baseUrl + '/logos/utah_retro_logo.webp',
    Utah_Tech: `${baseUrl}/logos/Utah_Tech_Trailblazers_logo.png`,
    Utah_Valley: `${baseUrl}/logos/Utah_Valley_Wolverines_logo.png`,
    UTEP: baseUrl + '/logos/utep_retro_logo.png',
    UTSA: baseUrl + '/logos/utsa_retro_logo.png',
    Valparaiso: `${baseUrl}/logos/Valparaiso_Crusaders_logo.png`,
    Vanderbilt: baseUrl + '/logos/vanderbilt_retro_2.png',
    VCU: baseUrl + '/logos/VCU_Rams_logo.png',
    Vermont: `${baseUrl}/logos/Vermont_Catamounts_logo.png`,
    Villanova: baseUrl + '/logos/Villanova_Wildcats_logo.png',
    Virginia: baseUrl + '/logos/virginia_retro_logo.png',
    Virginia_Tech: baseUrl + '/logos/virginia_tech_retro_logo.png',
    VMI: baseUrl + '/logos/VMI_Keydets_logo.png',
    Wagner: `${baseUrl}/logos/Wagner_Seahawks_logo.png`,
    Wake_Forest: baseUrl + '/logos/wake_forest_retro_logo.png',
    Washington: baseUrl + '/logos/washington_retro_logo.png',
    Washington_State: baseUrl + '/logos/washington_state_retro_logo.png',
    Weber_State: baseUrl + '/logos/Weber_State_Wildcats_logo.png',
    West_Georgia: `${baseUrl}/logos/West_Georgia_Wolves_logo.png`,
    West_Virginia: baseUrl + '/logos/wvu_retro_logo.png',
    Western_Carolina: baseUrl + '/logos/Western_Carolina_Catamounts_logo.png',
    Western_Illinois: baseUrl + '/logos/Western_Illinois_Leathernecks_logo.png',
    Western_Kentucky: baseUrl + '/logos/wku_retro_logo.png',
    Western_Michigan: baseUrl + '/logos/wmu_retro_logo.png',
    Wichita_State: baseUrl + '/logos/Wichita_State_Shockers_logo.png',
    William_and_Mary: `${baseUrl}/logos/William_and_Mary_Tribe_logo.png`,
    Winthrop: `${baseUrl}/logos/Winthrop_Eagles_logo.png`,
    Wisconsin: baseUrl + '/logos/Wisconsin_Badgers_logo.png',
    Wofford: baseUrl + '/logos/Wofford_Terriers_logo.png',
    Wright_State: `${baseUrl}/logos/Wright_State_Raiders_logo.png`,
    Wyoming: baseUrl + '/logos/wyoming_retro_logo.png',
    Xavier: baseUrl + '/logos/xavier_logo.png',
    Yale: baseUrl + '/logos/Yale_Bulldogs.png',
    Youngstown_State: baseUrl + '/logos/Youngstown_State.png',

    Unknown: baseUrl + '/logos/unknown1.png',
    SEA_Supersonics: baseUrl + '/logos/supersonics.png',
    SEA_Seahawks: baseUrl + '/logos/SEA_Seahawks.png',
    BUF_Bills: baseUrl + '/logos/BUF_Bills.png',
    MIA_Dolphins: baseUrl + '/logos/MIA_Dolphins.png',
    NE_Patriots: baseUrl + '/logos/NE_Patriots.png',
    NY_Jets: baseUrl + '/logos/NY_Jets.png',
    BAL_Ravens: baseUrl + '/logos/BAL_Ravens.png',
    CIN_Bengals: baseUrl + '/logos/CIN_Bengals.png',
    CLE_Browns: baseUrl + '/logos/CLE_Browns.png',
    PIT_Steelers: baseUrl + '/logos/PIT_Steelers.png',
    HOU_Texans: baseUrl + '/logos/HOU_Texans.png',
    IND_Colts: baseUrl + '/logos/IND_Colts.png',
    JAX_Jaguars: baseUrl + '/logos/JAX_Jaguars.png',
    TEN_Titans: baseUrl + '/logos/Tennessee_Titans_logo.png',
    DEN_Broncos: baseUrl + '/logos/DEN_Broncos.png',
    KC_Chiefs: baseUrl + '/logos/KC_Chiefs.png',
    LV_Raiders: baseUrl + '/logos/LV_Raiders.png',
    LA_Chargers: baseUrl + '/logos/LA_Chargers.png',
    DAL_Cowboys: baseUrl + '/logos/DAL_Cowboys.png',
    NY_Giants: baseUrl + '/logos/NY_Giants.png',
    PHI_Eagles: baseUrl + '/logos/PHI_Eagles.png',
    WFT: baseUrl + '/logos/WFT.png',
    WAS_Commies: baseUrl + '/logos/Washington_Commanders_logo.png',
    CHI_Bears: baseUrl + '/logos/CHI_Bears.png',
    DET_Lions: baseUrl + '/logos/DET_Lions.png',
    GB_Packers: baseUrl + '/logos/GB_Packers.png',
    MN_Vikings: baseUrl + '/logos/MN_Vikings.png',
    ATL_Falcons: baseUrl + '/logos/ATL_Falcons.png',
    CAR_Panthers: baseUrl + '/logos/CAR_Panthers.png',
    NO_Saints: baseUrl + '/logos/NO_Saints.png',
    TB_Buccaneers: baseUrl + '/logos/TB_Buccaneers.png',
    ARI_Cardinals: baseUrl + '/logos/ARI_Cardinals.png',
    LA_Rams: baseUrl + '/logos/LA_Rams.png',
    SF_49ers: baseUrl + '/logos/SF_49ers.png',
    VAN_Sealions: baseUrl + '/logos/VAN_Sealions_2.png',
    VGK: baseUrl + '/logos/',
    BOS_Celtics: baseUrl + '/logos/BOS_Celtics.png',
    BRK_Nets: baseUrl + '/logos/BRK_Nets.png',
    NY_Knicks: baseUrl + '/logos/NY_Knicks.png',
    PHI_76ers: baseUrl + '/logos/PHI_76ers.png',
    TOR_Raptors: baseUrl + '/logos/TOR_Raptors.png',
    CHI_Bulls: baseUrl + '/logos/CHI_Bulls.png',
    CLE_Cavaliers: baseUrl + '/logos/CLE_Cavaliers.png',
    DET_Pistons: baseUrl + '/logos/DET_Pistons.png',
    IND_Pacers: baseUrl + '/logos/IND_Pacers.png',
    MIL_Bucks: baseUrl + '/logos/MIL_Bucks.png',
    ATL_Hawks: baseUrl + '/logos/ATL_Hawks.png',
    CHA_Hornets: baseUrl + '/logos/Charlotte_Hornets_Logo_1989.png',
    MIA_Heat: baseUrl + '/logos/MIA_Heat.png',
    ORL_Magic: baseUrl + '/logos/ORL_Magic.png',
    WAS_Wizards: baseUrl + '/logos/WAS_Wizards.png',
    DEN_Nuggets: baseUrl + '/logos/DEN_Nuggets.png',
    MIN_Timberwolves: baseUrl + '/logos/MIN_Timberwolves.png',
    OKC_Thunder: baseUrl + '/logos/OKC_Thunder.png',
    POR_Trailblazers: baseUrl + '/logos/POR_Trailblazers.png',
    UTA_Jazz: baseUrl + '/logos/UTA_Jazz.png',
    GS_Warriors: baseUrl + '/logos/GS_Warriors.png',
    LA_Clippers: baseUrl + '/logos/LA_Clippers.png',
    LA_Lakers: baseUrl + '/logos/LA_Lakers.png',
    PHO_Suns: baseUrl + '/logos/PHO_Suns.png',
    SAC_Kings: baseUrl + '/logos/SAC_Kings.png',
    DAL_Mavericks: baseUrl + '/logos/DAL_Mavericks.png',
    HOU_Rockets: baseUrl + '/logos/HOU_Rockets.png',
    MEM_Grizzlies: baseUrl + '/logos/MEM_Grizzlies.png',
    NO_Pelicans: baseUrl + '/logos/NO_Pelicans.png',
    SA_Spurs: baseUrl + '/logos/SA_Spurs.png',
    SD_Clippers: `${baseUrl}/logos/san_diego_clippers_logo.png`
};

export const ISLLogos = {
    ABCFighters: `${baseUrl}/logos/ABC_Fighters_logo.png`,
    Adelaide: `${baseUrl}/logos/Adelaide.png`,
    AELLimassol: `${baseUrl}/logos/AEL_logo.png`,
    Aguada: `${baseUrl}/logos/Aguada_logo.png`,
    AlAhly: `${baseUrl}/logos/AL_AHLY_logo.png`,
    AlRasheed: `${baseUrl}/logos/Al-Rasheed_SC_logo.png`,
    ALRiyadi: `${baseUrl}/logos/Al_Riyadi_Basketball_logo.png`,
    AlSadd: `${baseUrl}/logos/Al_Sadd_SC_logo.png`,
    AlNassr: `${baseUrl}/logos/Al_Nassr_BC.png`,
    AlHilal: `${baseUrl}/logos/Al_Hilal_SFC.png`,
    AlIttihad: `${baseUrl}/logos/Al-Ittihad_Ahli_of_Aleppo_SC_Emblem.png`,
    AlWahda: `${baseUrl}/logos/Al-Wahda_Damascus_logo.gif`,
    ALBA: `${baseUrl}/logos/Alba_Berlin_logo.png`,
    Alvark: `${baseUrl}/logos/Alvark_Tokyo_logo.png`,
    Alger: `${baseUrl}/logos/Logo_MCA_1921.png`,
    Anadolu: `${baseUrl}/logos/Anadolu_Efes_SK_logo.png`,
    Andorra: `${baseUrl}/logos/BC_Andorra_logo.png`,
    APOEL: `${baseUrl}/logos/APOEL_logo.png`,
    Aquila: `${baseUrl}/logos/Aquila_Basket_Trento_logo.png`,
    Asker: `${baseUrl}/logos/Asker_Aliens_logo.png`,
    ASDouanes: `${baseUrl}/logos/AS_Douanes_Basket_logo.png`,
    ASSale: `${baseUrl}/logos/AS_Sale_logo.png`,
    ASPolice: `${baseUrl}/logos/AS_Police_Basketball_logo.png`,
    Astana: `${baseUrl}/logos/BC_Astana_logo.png`,
    BahrainSC: `${baseUrl}/logos/BahrainClub.png`,
    Bakken: `${baseUrl}/logos/Bakken_Bears_logo.png`,
    Barangay: `${baseUrl}/logos/Barangay_Ginebra_San_Miguel_logo.png`,
    Barcelona: `${baseUrl}/logos/FC_Barcelona_logo.png`,
    Baerum: `${baseUrl}/logos/Baerum_Basket_logo.png`,
    Bayern: `${baseUrl}/logos/FC_Bayern_Munich_logo.png`,
    BCBalcan: `${baseUrl}/logos/BC_Balkan_logo.png`,
    BCBudivelnyk: `${baseUrl}/logos/BC_Budivelnik_Logo.png`,
    BCLulea: `${baseUrl}/logos/BC_Lulea_logo.png`,
    BCDnipro: `${baseUrl}/logos/BC_Dnipro_logo.png`,
    BCLietkabelis: `${baseUrl}/logos/BC_Lietkabelis_logo.png`,
    BeijingDucks: `${baseUrl}/logos/Beijing_Ducks.png`,
    Beira: `${baseUrl}/logos/Ferroviario_da_Beira.png`,
    BeitSahour: `${baseUrl}/logos/Beit_Sahour_logo.png`,
    Benfica: `${baseUrl}/logos/SL_Benfica_logo.png`,
    BocaJuniors: `${baseUrl}/logos/Boca_Juniors_logo.png`,
    Bourg: `${baseUrl}/logos/JL_Bourg_Basket_logo.png`,
    Brisbane: `${baseUrl}/logos/Brisbane.png`,
    BuducnostVoli: `${baseUrl}/logos/KK_Buducnost_logo.png`,
    CaballosdeCocle: `${baseUrl}/logos/Caballos_de_Cocle_logo.png`,
    Caledonia: `${baseUrl}/logos/Caledonia_Gladiators_logo.png`,
    CangrejerosSanturce: `${baseUrl}/logos/Cangrejeros_Basket_logo.jpeg`,
    CapeTown: `${baseUrl}/logos/Cape_Town_Tigers_logo.png`,
    CapitanesDeCiudad: `${baseUrl}/logos/Capitanes_de_Ciudad_de_Mexico_logo.png`,
    CazooBaskonia: `${baseUrl}/logos/Saski_Baskonia_logo.png`,
    CDValdivia: `${baseUrl}/logos/CD_Valdivia_logo.jpg`,
    Cibona: `${baseUrl}/logos/KK_Cibona_logo.png`,
    CityOilers: `${baseUrl}/logos/City_Oilers.png`,
    CobraSport: `${baseUrl}/logos/Cobra_Sport_SC_logo.png`,
    CrvenaZvezda: `${baseUrl}/logos/Crvena_zvezda.png`,
    CSKAMoscow: `${baseUrl}/logos/PBC_CSKA_Moscow_logo.png`,
    Daegu: `${baseUrl}/logos/Daegu_KOGAS_Pegasus_logo.png`,
    DaNang: `${baseUrl}/logos/DanangDragonLogo.png`,
    DinamoBucuresti: `${baseUrl}/logos/CS_Dinamo_Bucuresti_logo.png`,
    EspoirFukash: `${baseUrl}/logos/BC_Espoir_Fukash_logo.png`,
    Fenerbache: `${baseUrl}/logos/Fenerbahçe_logo.png`,
    FalcoSzombathely: `${baseUrl}/logos/Falco_KC_logo.png`,
    Flamengo: `${baseUrl}/logos/Flamengo_braz_logo.png`,
    FOG: `${baseUrl}/logos/Team_FOG_logo.png`,
    Franca: `${baseUrl}/logos/Franca_basquete_logo.png`,
    FuerzaMonterrey: `${baseUrl}/logos/Fuerza_Regia_Logo.png`,
    Fujian: `${baseUrl}/logos/Fujian_Sturgeons_logo.png`,
    GNBC: `${baseUrl}/logos/GNBC_Basketball_Club_logo.png`,
    Goyang: `${baseUrl}/logos/Carrot_Jumpers_logo.png`,
    GranCanaria: `${baseUrl}/logos/CB_Gran_Canaria_logo.png`,
    Grindavik: `${baseUrl}/logos/Grindavik_logo.png`,
    Guandong: `${baseUrl}/logos/Guangdong_Southern_Tigers.png`,
    Guangzhou: `${baseUrl}/logos/Guangzhou_Long_Lions_logo.png`,
    Hamburg: `${baseUrl}/logos/Hamburg_Towers_logo.png`,
    HapoelJerusalem: `${baseUrl}/logos/Hapoel_Jerusalem_BC_logo.png`,
    Heliopolis: `${baseUrl}/logos/Heliopolis_Sporting_Club_logo.png`,
    Heroes: `${baseUrl}/logos/Heroes_Den_Bosch_logo.png`,
    Hiroshima: `${baseUrl}/logos/Hiroshima_Dragonflies_logo.png`,
    HiTechBangkok: `${baseUrl}/logos/HiTech_Bangkok_City_logo.png`,
    InstitutoACC: `${baseUrl}/logos/Instituto_acc_cordoba_logo.png`,
    IR: `${baseUrl}/logos/IR_logo.png`,
    Jilin: `${baseUrl}/logos/Jilin_Northeast_Tigers.png`,
    KazmaSC: `${baseUrl}/logos/KazmaSC_logo.png`,
    KKCedevita: `${baseUrl}/logos/Cedevita_Olimpija_Ljubljana_logo.png`,
    KKPartizan: `${baseUrl}/logos/KK_Partizan_logo.png`,
    KualaLumpur: `${baseUrl}/logos/Kuala_Lumpur_Dragons_logo.png`,
    KuwaitSC: `${baseUrl}/logos/Kuwait_Sporting_Club_logo.png`,
    Kwara: `${baseUrl}/logos/Kwara_Falcons_logo.png`,
    LDLC: `${baseUrl}/logos/LDLC_Asvel_Dark.png`,
    Levanga: `${baseUrl}/logos/levanga_hokkaido_logo.png`,
    LibertadoresQueretaro: `${baseUrl}/logos/LIBT_LOGO.png`,
    LokomotivKuban: `${baseUrl}/logos/PBC_Lokomotiv-Kuban_logo.png`,
    London: `${baseUrl}/logos/London_Lions_logo.png`,
    Louvre: `${baseUrl}/logos/Louvre_Indonesia.png`,
    Maccabi: `${baseUrl}/logos/Maccabi_Tel_Aviv_BC_logo.png`,
    MahramTehran: `${baseUrl}/logos/mahram_bc_logo.png`,
    Manama: `${baseUrl}/logos/Manama_Club.png`,
    Manchester: `${baseUrl}/logos/ManchesterGiants.png`,
    Maputo: `${baseUrl}/logos/Ferroviario_de_Maputo_logo.png`,
    Melbourne: `${baseUrl}/logos/Melbourne_United_logo.png`,
    Metropolitans92: `${baseUrl}/logos/Metropolitans_92_logo.png`,
    Minas: `${baseUrl}/logos/Crest_of_Minas_Tenis_Clube.png`,
    MogiDasCruzes: `${baseUrl}/logos/Mogi_das_Cruzes_Basquete_logo.png`,
    Monaco: `${baseUrl}/logos/AS_Monaco_Basket_Logo.png`,
    Monastir: `${baseUrl}/logos/US_Monastirienne.png`,
    Nagoya: `${baseUrl}/logos/Nagoya_Diamond_Dolphins_logo.png`,
    NewZealand: `${baseUrl}/logos/New_Zealand_Breakers_logo.png`,
    NhaTrang: `${baseUrl}/logos/Nha_Trang_Dolphins_logo.png`,
    Norrkoping: `${baseUrl}/logos/Norrkoping_Dolphins_logo.png`,
    Nymburk: `${baseUrl}/logos/Basketball_Nymburk.png`,
    ObrasSanitarias: `${baseUrl}/logos/Club_obras_logo.png`,
    Olimpia: `${baseUrl}/logos/Olimpia_Milano_logo.png`,
    Olympiacos: `${baseUrl}/logos/Olympiacos_BC_logo.png`,
    Oostende: `${baseUrl}/logos/Filou_Oostende_logo.png`,
    Opava: `${baseUrl}/logos/BK_Opava_logo.png`,
    Otago: `${baseUrl}/logos/Otago_Nuggets_logo.png`,
    Panathinaikos: `${baseUrl}/logos/Panathinaikos_BC_logo.png`,
    Peja: `${baseUrl}/logos/KB_Peja_logo.png`,
    Perth: `${baseUrl}/logos/Perth_Wildcats_logo.png`,
    Petro: `${baseUrl}/logos/Atletico_Petroleos_Luanda.png`,
    Petrochimi: `${baseUrl}/logos/Petrochimi.png`,
    Prometey: `${baseUrl}/logos/BC_Prometey_logo.png`,
    Pyrinto: `${baseUrl}/logos/Tampereen_Pyrinto_logo.png`,
    Quimsa: `${baseUrl}/logos/Quimsa_logo.png`,
    RealEsteli: `${baseUrl}/logos/Real_Esteli_Baloncesto.png`,
    RealMadrid: `${baseUrl}/logos/Real_Madrid_CF.png`,
    REG: `${baseUrl}/logos/Rwanda_Energy_Group_logo.png`,
    Rivers: `${baseUrl}/logos/Rivers_Hoopers_logo.png`,
    Ryuku: `${baseUrl}/logos/Ryukyu_Golden_Kings_logo.png`,
    SabahBC: `${baseUrl}/logos/Sabah_BC_logo.png`,
    SagesseSC: `${baseUrl}/logos/CS_Sagesse_logo.png`,
    Saigon: `${baseUrl}/logos/Saigon_Heat_logo.png`,
    SanLorenzo: `${baseUrl}/logos/San_lorenzo_almagro_logo.png`,
    SanMiguel: `${baseUrl}/logos/San_Miguel_Beermen_logo.png`,
    SaoPaulo: `${baseUrl}/logos/Brasao_do_Sao_Paulo_Futebol_Clube.png`,
    SatriaMuda: `${baseUrl}/logos/SM_Pertamina_logo.png`,
    Seoul: `${baseUrl}/logos/Seoul_Samsung_Thunders_logo.png`,
    ShababAlAhli: `${baseUrl}/logos/Shabab_Al_Ahli_logo.png`,
    Singapore: `${baseUrl}/logos/Singapore_Slingers.png`,
    SLAC: `${baseUrl}/logos/SLAC_BC_logo.png`,
    SlaskWroclaw: `${baseUrl}/logos/Slask_Wroclaw_logo.png`,
    Shandong: `${baseUrl}/logos/Shandong_Golden_Stars.png`,
    Shanghai: `${baseUrl}/logos/Shanghai_Sharks_logo.png`,
    Shenzen: `${baseUrl}/logos/Shenzhen_Leopards_logo.png`,
    SouthChina: `${baseUrl}/logos/Scaa_badge.png`,
    SportingAlexandria: `${baseUrl}/logos/Alexandria_Sporting_Club_logo.png`,
    StadeMalien: `${baseUrl}/logos/Stade_Malien_logo.png`,
    Taipei: `${baseUrl}/logos/Fubon_Braves_logo.png`,
    TaiwanCity: `${baseUrl}/logos/Taoyuan_Leopards_logo.png`,
    Tasmania: `${baseUrl}/logos/Tasmania_JackJumpers_Logo.png`,
    Titanes: `${baseUrl}/logos/Titanes_de_Barranquilla.png`,
    TorpanPojat: `${baseUrl}/logos/Torpan_Pojat_logo.png`,
    Ulsan: `${baseUrl}/logos/Ulsan_Hyundai_Mobis_Phoebus.png`,
    UniversidadConcepcion: `${baseUrl}/logos/Universidad_de_Concepcion_Basquetebol_logo.png`,
    VEF: `${baseUrl}/logos/VEF_Riga_logo_90s.png`,
    Vladivostok: `${baseUrl}/logos/BC_Dynamo_Vladivostok.png`,
    Virtus: `${baseUrl}/logos/Virtus_Bologna_logo.png`,
    Whai: `${baseUrl}/logos/Whai_Basketball_logo.png`,
    Yaounde: `${baseUrl}/logos/FAP_Basketball_logo.png`,
    Zalgiris: `${baseUrl}/logos/BC_Žalgiris_logo.png`,
    ZamalekBC: `${baseUrl}/logos/ZamalekSC.png`,
    ZenitSP: `${baseUrl}/logos/FC_Zenit_logo.png`
};

export const FormationImages = {
    Big_Penny: `${baseUrl}/formations/3_2_6_big_penny_formation.png`,
    Dime_326: `${baseUrl}/formations/3_2_6_dime_formation.png`,
    Penny: `${baseUrl}/formations/3_2_6_penny_formation.png`,
    Base335: `${baseUrl}/formations/3_3_5_base_formation.png`,
    Nickel335: `${baseUrl}/formations/3_3_5_nickel_formation.png`,
    Over335: `${baseUrl}/formations/3_3_5_over_formation.png`,
    Heavy344: `${baseUrl}/formations/3_4_4_heavy_formation.png`,
    Bronco34: `${baseUrl}/formations/3_4_bronco_formation.png`,
    Eagle34: `${baseUrl}/formations/3_4_eagle_formation.png`,
    Okie34: `${baseUrl}/formations/3_4_okie_formation.png`,
    Big_Dime: `${baseUrl}/formations/4_1_6_big_dime_formation.png`,
    Dime416: `${baseUrl}/formations/4_1_6_dime_formation.png`,
    Base425: `${baseUrl}/formations/4_2_5_base_formation.png`,
    Nickel425: `${baseUrl}/formations/4_2_5_nickel_formation.png`,
    Over425: `${baseUrl}/formations/4_2_5_over_formation.png`,
    Base43: `${baseUrl}/formations/4_3_base_formation.png`,
    Heavy43: `${baseUrl}/formations/4_3_heavy_formation.png`,
    Light43: `${baseUrl}/formations/4_3_light_formation.png`,
    Over43: `${baseUrl}/formations/4_3_over_formation.png`,
    Base44: `${baseUrl}/formations/4_4_base_formation.png`,
    Heavy44: `${baseUrl}/formations/4_4_heavy_formation.png`,
    Jumbo44: `${baseUrl}/formations/4_4_jumbo_formation.png`,
    Over44: `${baseUrl}/formations/4_4_over_formation.png`,
    Under44: `${baseUrl}/formations/4_4_under_formation.png`,
    BigPistol: `${baseUrl}/formations/big_pistol_formation.png`,
    BigSpreadGun: `${baseUrl}/formations/big_spread_gun_formation.png`,
    DoubleTight: `${baseUrl}/formations/double_tight_formation.png`,
    DoubleWing: `${baseUrl}/formations/double_wing_formation.png`,
    DWSplit: `${baseUrl}/formations/double_wing_split_formation.png`,
    DWSpread: `${baseUrl}/formations/double_wing_spread_formation.png`,
    DWStrong: `${baseUrl}/formations/double_wing_strong_formation.png`,
    DWWide: `${baseUrl}/formations/double_wing_wide_formation.png`,
    EmptyGun: `${baseUrl}/formations/empty_gun_formation.png`,
    Flexbone: `${baseUrl}/formations/flexbone_formation.png`,
    FBGun: `${baseUrl}/formations/flexbone_gun_formation.png`,
    FBGunWide: `${baseUrl}/formations/flexbone_gun_wide_formation.png`,
    FBStrong: `${baseUrl}/formations/flexbone_strong_formation.png`,
    FBWide: `${baseUrl}/formations/flexbone_wide_formation.png`,
    HeavyPowerP: `${baseUrl}/formations/heavy_power_pistol_formation.png`,
    IFormHeavy: `${baseUrl}/formations/i_formation_heavy.png`,
    IForm: `${baseUrl}/formations/i_formation.png`,
    NearFar: `${baseUrl}/formations/near_far_formation.png`,
    Pistol: `${baseUrl}/formations/pistol_formation.png`,
    PonySpreadG: `${baseUrl}/formations/pony_spread_gun_formation.png`,
    PowerP: `${baseUrl}/formations/power_pistol_formation.png`,
    Singleback: `${baseUrl}/formations/singleback_formation.png`,
    SinglebackG: `${baseUrl}/formations/singleback_gun_formation.png`,
    SplitbackG: `${baseUrl}/formations/splitback_gun_formation.png`,
    Spread: `${baseUrl}/formations/spread_formation.png`,
    SpreadG: `${baseUrl}/formations/spread_gun_formation.png`,
    SpreadP: `${baseUrl}/formations/spread_pistol_formation.png`,
    WingSplitbackG: `${baseUrl}/formations/wing_split_back_gun_formation.png`,
    WingTDT: `${baseUrl}/formations/wing_t_double_tight_formation.png`,
    WingT: `${baseUrl}/formations/wing_t_formation.png`,
    WingTSplit: `${baseUrl}/formations/wing_t_split_formation.png`,
    Wishbone: `${baseUrl}/formations/wishbone_formation.png`,
    WishboneStrong: `${baseUrl}/formations/wishbone_strong_formation.png`,
    WishboneWide: `${baseUrl}/formations/wishbone_wide_formation.png`
};
