export default {
  LANDING: '/',
  APPROVE: '/admin-approve',
  MANAGE_USERS: '/admin-users',
  MANAGE_SIM: '/sim',
  USER: '/user',
  TEAM: '/team',
  ROSTER: '/team/roster',
  SCHEDULING: '/team/scheduling',
  RECRUITING_BOARD: '/team/recruits',
  AVAILABLE_TEAMS: '/availableteams',
  RECRUITING: '/recruiting',
  DEPTHCHART: '/depthchart',
  LOGIN: '/login',
  SIGNUP: '/signup',
};
