const SampleContent = [
  {
    name: "Aaron Kotar",
    position: "QB",
    archtype: "Scrambler",
    overall: "B",
    year: "(Sr)",
    height: "6'2\"",
    weight: "205 lbs",
    state: "Ohio",
    school: "Buckeye High",
    potential: "C",
    jersey: "12"
  },
  {
    name: "Marquise Mariota",
    position: "QB",
    archtype: "Balanced",
    overall: "A",
    year: "(Fr)",
    height: "6'4\"",
    weight: "235 lbs",
    state: "Hawaii",
    school: "St. Louis HS",
    potential: "C",
    jersey: "2"
  },
  {
    name: "Cal Beckam Jr",
    position: "WR",
    archtype: "Speed",
    overall: "C+",
    year: "So",
    height: "6'5\"",
    weight: "200 lbs",
    state: "Texas",
    school: "Midway Highschool",
    potential: "B-",
    jersey: "85"
  },
  {
    name: "Chris Cross",
    position: "DE",
    archtype: "Speed Rusher",
    overall: "A",
    year: "Jr",
    height: "6'7\"",
    weight: "268 lbs",
    state: "Georgia",
    school: "George Southwest CC",
    potential: "A",
    jersey: "72"
  },
  {
    name: "Quincy Sanford",
    position: "CB",
    archtype: "Ball Hawk",
    overall: "D",
    year: "Sr",
    height: "5'9\"",
    weight: "180 lbs",
    state: "Delaware",
    school: "Barack Obama HS",
    potential: "D",
    jersey: "30"
  },
  {
    name: "Beau Allen",
    position: "DT",
    archtype: "Nose Tackle",
    overall: "A",
    year: "(Sr)",
    height: "6'5\"",
    weight: "298 lbs",
    state: "Minnesota",
    school: "Minnetonka High School",
    potential: "B",
    jersey: "30"
  },
  {
    name: "Rob Adams",
    position: "OT",
    archtype: "Run Blocking",
    overall: "A",
    year: "Sr.",
    height: "6'3\"",
    weight: "289 lbs",
    state: "Florida",
    school: "Harmony",
    potential: "C",
    jersey: "61"
  },
  {
    name: "Jonas Skipper",
    position: "OG",
    archtype: "Balanced",
    overall: "A",
    year: "Sr.",
    height: "6'5\"",
    weight: "294 lbs",
    state: "Missouri",
    school: "Cassville",
    potential: "C+",
    jersey: "58"
  },
  {
    name: "Chris Butera",
    position: "OG",
    archtype: "Run Blocking",
    overall: "A",
    year: "Jr.",
    height: "6'5\"",
    weight: "306 lbs",
    state: "TX",
    school: "Manvel",
    potential: "B+",
    jersey: "63"
  },
  {
    name: "Chris Hinojosa",
    position: "ILB",
    archtype: "Field General",
    overall: "B",
    year: "Sr.",
    height: "6'0\"",
    weight: "234 lbs",
    state: "NJ",
    school: "West Long Branch",
    potential: "C+",
    jersey: "53"
  },
  {
    name: "Bobby Hammel",
    position: "OLB",
    archtype: "Pass Rush",
    overall: "B",
    year: "Sr.",
    height: "6'3\"",
    weight: "246 lbs",
    state: "NC",
    school: "Kinston",
    potential: "C+",
    jersey: "50"
  }
];

export default SampleContent;
